// Generated by scripts/techdeck/generate-resolution-contract.mjs --write. Do not edit.

export const MACHINE_EVIDENCE_SCHEMA_VERSION = '1.0' as const;
export const MACHINE_EVIDENCE_EXPORT_TYPE = 'msp_incident_closeout' as const;
export const machineEvidenceExportSchema = {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "urn:operatoros:techdeck:machine-evidence-export:1.0",
  "title": "MSP incident closeout export 1.0",
  "description": "Evidence contract. Unknown fields are untrusted extensions. Secret screening and aggregate byte/depth limits are separate ingestion requirements.",
  "type": "object",
  "maxProperties": 500,
  "properties": {
    "schema_version": {
      "type": "string",
      "const": "1.0"
    },
    "export_type": {
      "type": "string",
      "const": "msp_incident_closeout"
    },
    "incident": {
      "type": "object",
      "maxProperties": 500,
      "properties": {
        "incident_id": {
          "type": [
            "string",
            "null"
          ],
          "maxLength": 100000
        },
        "external_ticket_id": {
          "type": [
            "string",
            "null"
          ],
          "maxLength": 100000
        },
        "title": {
          "type": [
            "string",
            "null"
          ],
          "maxLength": 100000
        },
        "organization": {
          "type": [
            "string",
            "null"
          ],
          "maxLength": 100000
        },
        "client": {
          "type": [
            "string",
            "null"
          ],
          "maxLength": 100000
        },
        "technician": {
          "type": [
            "string",
            "null"
          ],
          "maxLength": 100000
        },
        "opened_at": {
          "type": [
            "string",
            "null"
          ],
          "maxLength": 100000
        },
        "closed_at": {
          "type": [
            "string",
            "null"
          ],
          "maxLength": 100000
        },
        "status": {
          "type": [
            "string",
            "null"
          ],
          "maxLength": 100000
        },
        "severity": {
          "type": [
            "string",
            "null"
          ],
          "maxLength": 100000
        },
        "business_impact": {
          "type": [
            "string",
            "null"
          ],
          "maxLength": 100000
        }
      },
      "additionalProperties": true
    },
    "affected_assets": {
      "type": "array",
      "maxItems": 2000,
      "items": {
        "type": "object",
        "maxProperties": 500,
        "properties": {
          "asset_type": {
            "type": [
              "string",
              "null"
            ],
            "maxLength": 100000
          },
          "hostname": {
            "type": [
              "string",
              "null"
            ],
            "maxLength": 100000
          },
          "device_name": {
            "type": [
              "string",
              "null"
            ],
            "maxLength": 100000
          },
          "manufacturer": {
            "type": [
              "string",
              "null"
            ],
            "maxLength": 100000
          },
          "model": {
            "type": [
              "string",
              "null"
            ],
            "maxLength": 100000
          },
          "serial_number": {
            "type": [
              "string",
              "null"
            ],
            "maxLength": 100000
          },
          "operating_system": {
            "type": [
              "string",
              "null"
            ],
            "maxLength": 100000
          },
          "os_version": {
            "type": [
              "string",
              "null"
            ],
            "maxLength": 100000
          },
          "os_build": {
            "type": [
              "string",
              "null"
            ],
            "maxLength": 100000
          },
          "ip_addresses": {
            "type": "array",
            "maxItems": 2000,
            "items": {
              "type": "string",
              "maxLength": 100000
            }
          },
          "mac_addresses": {
            "type": "array",
            "maxItems": 2000,
            "items": {
              "type": "string",
              "maxLength": 100000
            }
          },
          "role": {
            "type": [
              "string",
              "null"
            ],
            "maxLength": 100000
          }
        },
        "additionalProperties": true
      }
    },
    "environment": {
      "type": "object",
      "maxProperties": 500,
      "properties": {
        "domain": {
          "type": [
            "string",
            "null"
          ],
          "maxLength": 100000
        },
        "tenant": {
          "type": [
            "string",
            "null"
          ],
          "maxLength": 100000
        },
        "network": {
          "type": [
            "string",
            "null"
          ],
          "maxLength": 100000
        },
        "location": {
          "type": [
            "string",
            "null"
          ],
          "maxLength": 100000
        },
        "applications": {
          "type": "array",
          "maxItems": 2000,
          "items": {
            "type": "string",
            "maxLength": 100000
          }
        },
        "services": {
          "type": "array",
          "maxItems": 2000,
          "items": {
            "type": "string",
            "maxLength": 100000
          }
        },
        "vendors": {
          "type": "array",
          "maxItems": 2000,
          "items": {
            "type": "string",
            "maxLength": 100000
          }
        }
      },
      "additionalProperties": true
    },
    "issue": {
      "type": "object",
      "maxProperties": 500,
      "properties": {
        "summary": {
          "type": [
            "string",
            "null"
          ],
          "maxLength": 100000
        },
        "symptoms": {
          "type": "array",
          "maxItems": 2000,
          "items": {
            "type": "string",
            "maxLength": 100000
          }
        },
        "user_reported_symptoms": {
          "type": "array",
          "maxItems": 2000,
          "items": {
            "type": "string",
            "maxLength": 100000
          }
        },
        "technician_observed_symptoms": {
          "type": "array",
          "maxItems": 2000,
          "items": {
            "type": "string",
            "maxLength": 100000
          }
        },
        "error_codes": {
          "type": "array",
          "maxItems": 2000,
          "items": {
            "type": "string",
            "maxLength": 100000
          }
        },
        "event_ids": {
          "type": "array",
          "maxItems": 2000,
          "items": {
            "type": "string",
            "maxLength": 100000
          }
        },
        "error_messages": {
          "type": "array",
          "maxItems": 2000,
          "items": {
            "type": "string",
            "maxLength": 100000
          }
        },
        "affected_components": {
          "type": "array",
          "maxItems": 2000,
          "items": {
            "type": "string",
            "maxLength": 100000
          }
        },
        "first_observed_at": {
          "type": [
            "string",
            "null"
          ],
          "maxLength": 100000
        }
      },
      "additionalProperties": true
    },
    "evidence": {
      "type": "array",
      "maxItems": 2000,
      "items": {
        "type": "object",
        "maxProperties": 500,
        "properties": {
          "evidence_id": {
            "type": [
              "string",
              "null"
            ],
            "maxLength": 100000
          },
          "timestamp": {
            "type": [
              "string",
              "null"
            ],
            "maxLength": 100000
          },
          "type": {
            "type": [
              "string",
              "null"
            ],
            "maxLength": 100000
          },
          "source": {
            "type": [
              "string",
              "null"
            ],
            "maxLength": 100000
          },
          "description": {
            "type": [
              "string",
              "null"
            ],
            "maxLength": 100000
          },
          "value": {
            "type": [
              "string",
              "number",
              "boolean",
              "null"
            ],
            "maxLength": 100000
          },
          "units": {
            "type": [
              "string",
              "null"
            ],
            "maxLength": 100000
          },
          "path": {
            "type": [
              "string",
              "null"
            ],
            "maxLength": 100000
          },
          "confidence": {
            "type": [
              "string",
              "null"
            ],
            "enum": [
              "CONFIRMED",
              "HIGH",
              "MODERATE",
              "LOW",
              "UNKNOWN",
              null
            ]
          }
        },
        "additionalProperties": true
      }
    },
    "diagnostics": {
      "type": "array",
      "maxItems": 2000,
      "items": {
        "type": "object",
        "maxProperties": 500,
        "properties": {
          "sequence": {
            "type": [
              "integer",
              "null"
            ],
            "minimum": 0,
            "maximum": 2147483647
          },
          "timestamp": {
            "type": [
              "string",
              "null"
            ],
            "maxLength": 100000
          },
          "action": {
            "type": [
              "string",
              "null"
            ],
            "maxLength": 100000
          },
          "command": {
            "type": [
              "string",
              "null"
            ],
            "maxLength": 100000
          },
          "purpose": {
            "type": [
              "string",
              "null"
            ],
            "maxLength": 100000
          },
          "expected_result": {
            "type": [
              "string",
              "null"
            ],
            "maxLength": 100000
          },
          "actual_result": {
            "type": [
              "string",
              "null"
            ],
            "maxLength": 100000
          },
          "outcome": {
            "type": [
              "string",
              "null"
            ],
            "enum": [
              "SUCCESS",
              "FAILURE",
              "PARTIAL",
              "INCONCLUSIVE",
              "NOT_RUN",
              null
            ]
          },
          "risk_level": {
            "type": [
              "string",
              "null"
            ],
            "enum": [
              "NONE",
              "LOW",
              "MEDIUM",
              "HIGH",
              "CRITICAL",
              null
            ]
          }
        },
        "additionalProperties": true
      }
    },
    "commands_scripts": {
      "type": "array",
      "maxItems": 2000,
      "items": {
        "type": "object",
        "maxProperties": 500,
        "properties": {
          "sequence": {
            "type": [
              "integer",
              "null"
            ],
            "minimum": 0,
            "maximum": 2147483647
          },
          "type": {
            "type": [
              "string",
              "null"
            ],
            "maxLength": 100000
          },
          "language": {
            "type": [
              "string",
              "null"
            ],
            "maxLength": 100000
          },
          "command_or_script": {
            "type": [
              "string",
              "null"
            ],
            "maxLength": 100000
          },
          "purpose": {
            "type": [
              "string",
              "null"
            ],
            "maxLength": 100000
          },
          "result": {
            "type": [
              "string",
              "null"
            ],
            "maxLength": 100000
          },
          "successful": {
            "type": [
              "boolean",
              "null"
            ]
          },
          "destructive": {
            "type": [
              "boolean",
              "null"
            ]
          },
          "requires_elevation": {
            "type": [
              "boolean",
              "null"
            ]
          }
        },
        "additionalProperties": true
      }
    },
    "changes_made": {
      "type": "array",
      "maxItems": 2000,
      "items": {
        "type": "object",
        "maxProperties": 500,
        "properties": {
          "sequence": {
            "type": [
              "integer",
              "null"
            ],
            "minimum": 0,
            "maximum": 2147483647
          },
          "timestamp": {
            "type": [
              "string",
              "null"
            ],
            "maxLength": 100000
          },
          "change_type": {
            "type": [
              "string",
              "null"
            ],
            "maxLength": 100000
          },
          "target": {
            "type": [
              "string",
              "null"
            ],
            "maxLength": 100000
          },
          "before": {
            "type": [
              "string",
              "number",
              "boolean",
              "null"
            ],
            "maxLength": 100000
          },
          "after": {
            "type": [
              "string",
              "number",
              "boolean",
              "null"
            ],
            "maxLength": 100000
          },
          "reason": {
            "type": [
              "string",
              "null"
            ],
            "maxLength": 100000
          },
          "reversible": {
            "type": [
              "boolean",
              "null"
            ]
          },
          "rollback": {
            "type": [
              "string",
              "null"
            ],
            "maxLength": 100000
          }
        },
        "additionalProperties": true
      }
    },
    "failed_actions": {
      "type": "array",
      "maxItems": 2000,
      "items": {
        "type": "object",
        "maxProperties": 500,
        "properties": {
          "action": {
            "type": [
              "string",
              "null"
            ],
            "maxLength": 100000
          },
          "reason_failed": {
            "type": [
              "string",
              "null"
            ],
            "maxLength": 100000
          },
          "error": {
            "type": [
              "string",
              "null"
            ],
            "maxLength": 100000
          },
          "side_effect": {
            "type": [
              "string",
              "null"
            ],
            "maxLength": 100000
          },
          "lesson": {
            "type": [
              "string",
              "null"
            ],
            "maxLength": 100000
          }
        },
        "additionalProperties": true
      }
    },
    "successful_actions": {
      "type": "array",
      "maxItems": 2000,
      "items": {
        "type": "object",
        "maxProperties": 500,
        "properties": {
          "action": {
            "type": [
              "string",
              "null"
            ],
            "maxLength": 100000
          },
          "result": {
            "type": [
              "string",
              "null"
            ],
            "maxLength": 100000
          },
          "evidence": {
            "type": [
              "string",
              "null"
            ],
            "maxLength": 100000
          }
        },
        "additionalProperties": true
      }
    },
    "side_effects": {
      "type": "array",
      "maxItems": 2000,
      "items": {
        "type": "object",
        "maxProperties": 500,
        "properties": {
          "triggering_action": {
            "type": [
              "string",
              "null"
            ],
            "maxLength": 100000
          },
          "effect": {
            "type": [
              "string",
              "null"
            ],
            "maxLength": 100000
          },
          "severity": {
            "type": [
              "string",
              "null"
            ],
            "maxLength": 100000
          },
          "recovery_action": {
            "type": [
              "string",
              "null"
            ],
            "maxLength": 100000
          },
          "recovered": {
            "type": [
              "boolean",
              "null"
            ]
          }
        },
        "additionalProperties": true
      }
    },
    "root_cause": {
      "type": "object",
      "maxProperties": 500,
      "properties": {
        "summary": {
          "type": [
            "string",
            "null"
          ],
          "maxLength": 100000
        },
        "category": {
          "type": [
            "string",
            "null"
          ],
          "maxLength": 100000
        },
        "confidence": {
          "type": [
            "string",
            "null"
          ],
          "enum": [
            "CONFIRMED",
            "HIGH",
            "MODERATE",
            "LOW",
            "UNKNOWN",
            null
          ]
        },
        "evidence": {
          "type": "array",
          "maxItems": 2000,
          "items": {
            "type": "string",
            "maxLength": 100000
          }
        },
        "contributing_factors": {
          "type": "array",
          "maxItems": 2000,
          "items": {
            "type": "string",
            "maxLength": 100000
          }
        },
        "secondary_effects": {
          "type": "array",
          "maxItems": 2000,
          "items": {
            "type": "string",
            "maxLength": 100000
          }
        },
        "not_proven": {
          "type": "array",
          "maxItems": 2000,
          "items": {
            "type": "string",
            "maxLength": 100000
          }
        }
      },
      "additionalProperties": true
    },
    "resolution": {
      "type": "object",
      "maxProperties": 500,
      "properties": {
        "summary": {
          "type": [
            "string",
            "null"
          ],
          "maxLength": 100000
        },
        "final_actions": {
          "type": "array",
          "maxItems": 2000,
          "items": {
            "type": "string",
            "maxLength": 100000
          }
        },
        "permanent_fix": {
          "type": [
            "string",
            "null"
          ],
          "maxLength": 100000
        },
        "temporary_workaround": {
          "type": [
            "string",
            "null"
          ],
          "maxLength": 100000
        }
      },
      "additionalProperties": true
    },
    "validation": {
      "type": "object",
      "maxProperties": 500,
      "properties": {
        "performed": {
          "type": "array",
          "maxItems": 2000,
          "items": {
            "type": "string",
            "maxLength": 100000
          }
        },
        "successful": {
          "type": "array",
          "maxItems": 2000,
          "items": {
            "type": "string",
            "maxLength": 100000
          }
        },
        "failed": {
          "type": "array",
          "maxItems": 2000,
          "items": {
            "type": "string",
            "maxLength": 100000
          }
        },
        "pending": {
          "type": "array",
          "maxItems": 2000,
          "items": {
            "type": "string",
            "maxLength": 100000
          }
        }
      },
      "additionalProperties": true
    },
    "current_status": {
      "type": "object",
      "maxProperties": 500,
      "properties": {
        "primary_remediation": {
          "type": [
            "string",
            "null"
          ],
          "enum": [
            "COMPLETE",
            "INCOMPLETE",
            null
          ]
        },
        "user_functionality": {
          "type": [
            "string",
            "null"
          ],
          "enum": [
            "RESTORED",
            "DEGRADED",
            "UNKNOWN",
            null
          ]
        },
        "validation": {
          "type": [
            "string",
            "null"
          ],
          "enum": [
            "COMPLETE",
            "PARTIAL",
            "PENDING",
            null
          ]
        },
        "monitoring_required": {
          "type": [
            "string",
            "null"
          ],
          "enum": [
            "YES",
            "NO",
            null
          ]
        },
        "follow_up_required": {
          "type": [
            "string",
            "null"
          ],
          "enum": [
            "YES",
            "NO",
            null
          ]
        },
        "recommended_ticket_state": {
          "type": [
            "string",
            "null"
          ],
          "maxLength": 100000
        }
      },
      "additionalProperties": true
    },
    "follow_up": {
      "type": "array",
      "maxItems": 2000,
      "items": {
        "type": "object",
        "maxProperties": 500,
        "properties": {
          "action": {
            "type": [
              "string",
              "null"
            ],
            "maxLength": 100000
          },
          "priority": {
            "type": [
              "string",
              "null"
            ],
            "maxLength": 100000
          },
          "owner": {
            "type": [
              "string",
              "null"
            ],
            "maxLength": 100000
          },
          "due": {
            "type": [
              "string",
              "null"
            ],
            "maxLength": 100000
          }
        },
        "additionalProperties": true
      }
    },
    "classification": {
      "type": "object",
      "maxProperties": 500,
      "properties": {
        "category": {
          "type": [
            "string",
            "null"
          ],
          "maxLength": 100000
        },
        "subcategory": {
          "type": [
            "string",
            "null"
          ],
          "maxLength": 100000
        },
        "cause_type": {
          "type": [
            "string",
            "null"
          ],
          "maxLength": 100000
        },
        "platforms": {
          "type": "array",
          "maxItems": 2000,
          "items": {
            "type": "string",
            "maxLength": 100000
          }
        },
        "applications": {
          "type": "array",
          "maxItems": 2000,
          "items": {
            "type": "string",
            "maxLength": 100000
          }
        },
        "services": {
          "type": "array",
          "maxItems": 2000,
          "items": {
            "type": "string",
            "maxLength": 100000
          }
        },
        "technologies": {
          "type": "array",
          "maxItems": 2000,
          "items": {
            "type": "string",
            "maxLength": 100000
          }
        },
        "tags": {
          "type": "array",
          "maxItems": 2000,
          "items": {
            "type": "string",
            "maxLength": 100000
          }
        },
        "security_relevant": {
          "type": [
            "boolean",
            "null"
          ]
        },
        "hardware_relevant": {
          "type": [
            "boolean",
            "null"
          ]
        },
        "network_relevant": {
          "type": [
            "boolean",
            "null"
          ]
        },
        "kb_candidate": {
          "type": [
            "boolean",
            "null"
          ]
        },
        "automation_candidate": {
          "type": [
            "boolean",
            "null"
          ]
        },
        "recurrence_risk": {
          "type": [
            "string",
            "null"
          ],
          "maxLength": 100000
        }
      },
      "additionalProperties": true
    },
    "automation_opportunity": {
      "type": "object",
      "maxProperties": 500,
      "properties": {
        "candidate": {
          "type": [
            "boolean",
            "null"
          ]
        },
        "name": {
          "type": [
            "string",
            "null"
          ],
          "maxLength": 100000
        },
        "trigger": {
          "type": [
            "string",
            "null"
          ],
          "maxLength": 100000
        },
        "inputs": {
          "type": "array",
          "maxItems": 2000,
          "items": {
            "type": "string",
            "maxLength": 100000
          }
        },
        "diagnostic_logic": {
          "type": "array",
          "maxItems": 2000,
          "items": {
            "type": "string",
            "maxLength": 100000
          }
        },
        "safe_actions": {
          "type": "array",
          "maxItems": 2000,
          "items": {
            "type": "string",
            "maxLength": 100000
          }
        },
        "approval_required_actions": {
          "type": "array",
          "maxItems": 2000,
          "items": {
            "type": "string",
            "maxLength": 100000
          }
        },
        "risks": {
          "type": "array",
          "maxItems": 2000,
          "items": {
            "type": "string",
            "maxLength": 100000
          }
        },
        "estimated_time_savings_minutes": {
          "type": [
            "number",
            "null"
          ],
          "minimum": 0,
          "maximum": 525600
        }
      },
      "additionalProperties": true
    },
    "knowledge": {
      "type": "object",
      "maxProperties": 500,
      "properties": {
        "kb_title": {
          "type": [
            "string",
            "null"
          ],
          "maxLength": 100000
        },
        "one_line_resolution": {
          "type": [
            "string",
            "null"
          ],
          "maxLength": 100000
        },
        "warnings": {
          "type": "array",
          "maxItems": 2000,
          "items": {
            "type": "string",
            "maxLength": 100000
          }
        },
        "lessons_learned": {
          "type": "array",
          "maxItems": 2000,
          "items": {
            "type": "string",
            "maxLength": 100000
          }
        },
        "escalation_conditions": {
          "type": "array",
          "maxItems": 2000,
          "items": {
            "type": "string",
            "maxLength": 100000
          }
        },
        "reusable_ip_opportunities": {
          "type": "array",
          "maxItems": 2000,
          "items": {
            "type": "string",
            "maxLength": 100000
          }
        }
      },
      "additionalProperties": true
    },
    "artifact_log_references": {
      "type": "array",
      "maxItems": 2000,
      "items": {
        "type": "object",
        "maxProperties": 500,
        "properties": {
          "type": {
            "type": [
              "string",
              "null"
            ],
            "maxLength": 100000
          },
          "name": {
            "type": [
              "string",
              "null"
            ],
            "maxLength": 100000
          },
          "path_or_reference": {
            "type": [
              "string",
              "null"
            ],
            "maxLength": 100000
          },
          "description": {
            "type": [
              "string",
              "null"
            ],
            "maxLength": 100000
          }
        },
        "additionalProperties": true
      }
    },
    "security": {
      "type": "object",
      "maxProperties": 500,
      "properties": {
        "credentials_present": {
          "type": [
            "boolean",
            "null"
          ]
        },
        "credentials_redacted": {
          "type": [
            "boolean",
            "null"
          ]
        },
        "security_incident_suspected": {
          "type": [
            "boolean",
            "null"
          ]
        },
        "security_notes": {
          "type": [
            "string",
            "null"
          ],
          "maxLength": 100000
        }
      },
      "additionalProperties": true
    },
    "data_quality": {
      "type": "object",
      "maxProperties": 500,
      "properties": {
        "overall_confidence": {
          "type": [
            "string",
            "null"
          ],
          "enum": [
            "CONFIRMED",
            "HIGH",
            "MODERATE",
            "LOW",
            "UNKNOWN",
            null
          ]
        },
        "missing_important_information": {
          "type": "array",
          "maxItems": 2000,
          "items": {
            "type": "string",
            "maxLength": 100000
          }
        },
        "conflicting_information": {
          "type": "array",
          "maxItems": 2000,
          "items": {
            "type": "string",
            "maxLength": 100000
          }
        },
        "assumptions": {
          "type": "array",
          "maxItems": 2000,
          "items": {
            "type": "string",
            "maxLength": 100000
          }
        }
      },
      "additionalProperties": true
    }
  },
  "additionalProperties": true,
  "required": [
    "schema_version",
    "export_type",
    "incident",
    "affected_assets",
    "environment",
    "issue",
    "evidence",
    "diagnostics",
    "commands_scripts",
    "changes_made",
    "failed_actions",
    "successful_actions",
    "side_effects",
    "root_cause",
    "resolution",
    "validation",
    "current_status",
    "follow_up",
    "classification",
    "automation_opportunity",
    "knowledge",
    "artifact_log_references",
    "security",
    "data_quality"
  ]
} as const;
/** Unknown extension fields remain untrusted and are preserved only in screened source. */
export type MachineEvidenceExport = {
  "schema_version": "1.0";
  "export_type": "msp_incident_closeout";
  "incident": {
  "incident_id"?: string | null;
  "external_ticket_id"?: string | null;
  "title"?: string | null;
  "organization"?: string | null;
  "client"?: string | null;
  "technician"?: string | null;
  "opened_at"?: string | null;
  "closed_at"?: string | null;
  "status"?: string | null;
  "severity"?: string | null;
  "business_impact"?: string | null;
};
  "affected_assets": Array<{
  "asset_type"?: string | null;
  "hostname"?: string | null;
  "device_name"?: string | null;
  "manufacturer"?: string | null;
  "model"?: string | null;
  "serial_number"?: string | null;
  "operating_system"?: string | null;
  "os_version"?: string | null;
  "os_build"?: string | null;
  "ip_addresses"?: Array<string>;
  "mac_addresses"?: Array<string>;
  "role"?: string | null;
}>;
  "environment": {
  "domain"?: string | null;
  "tenant"?: string | null;
  "network"?: string | null;
  "location"?: string | null;
  "applications"?: Array<string>;
  "services"?: Array<string>;
  "vendors"?: Array<string>;
};
  "issue": {
  "summary"?: string | null;
  "symptoms"?: Array<string>;
  "user_reported_symptoms"?: Array<string>;
  "technician_observed_symptoms"?: Array<string>;
  "error_codes"?: Array<string>;
  "event_ids"?: Array<string>;
  "error_messages"?: Array<string>;
  "affected_components"?: Array<string>;
  "first_observed_at"?: string | null;
};
  "evidence": Array<{
  "evidence_id"?: string | null;
  "timestamp"?: string | null;
  "type"?: string | null;
  "source"?: string | null;
  "description"?: string | null;
  "value"?: string | number | boolean | null;
  "units"?: string | null;
  "path"?: string | null;
  "confidence"?: "CONFIRMED" | "HIGH" | "MODERATE" | "LOW" | "UNKNOWN" | null;
}>;
  "diagnostics": Array<{
  "sequence"?: number | null;
  "timestamp"?: string | null;
  "action"?: string | null;
  "command"?: string | null;
  "purpose"?: string | null;
  "expected_result"?: string | null;
  "actual_result"?: string | null;
  "outcome"?: "SUCCESS" | "FAILURE" | "PARTIAL" | "INCONCLUSIVE" | "NOT_RUN" | null;
  "risk_level"?: "NONE" | "LOW" | "MEDIUM" | "HIGH" | "CRITICAL" | null;
}>;
  "commands_scripts": Array<{
  "sequence"?: number | null;
  "type"?: string | null;
  "language"?: string | null;
  "command_or_script"?: string | null;
  "purpose"?: string | null;
  "result"?: string | null;
  "successful"?: boolean | null;
  "destructive"?: boolean | null;
  "requires_elevation"?: boolean | null;
}>;
  "changes_made": Array<{
  "sequence"?: number | null;
  "timestamp"?: string | null;
  "change_type"?: string | null;
  "target"?: string | null;
  "before"?: string | number | boolean | null;
  "after"?: string | number | boolean | null;
  "reason"?: string | null;
  "reversible"?: boolean | null;
  "rollback"?: string | null;
}>;
  "failed_actions": Array<{
  "action"?: string | null;
  "reason_failed"?: string | null;
  "error"?: string | null;
  "side_effect"?: string | null;
  "lesson"?: string | null;
}>;
  "successful_actions": Array<{
  "action"?: string | null;
  "result"?: string | null;
  "evidence"?: string | null;
}>;
  "side_effects": Array<{
  "triggering_action"?: string | null;
  "effect"?: string | null;
  "severity"?: string | null;
  "recovery_action"?: string | null;
  "recovered"?: boolean | null;
}>;
  "root_cause": {
  "summary"?: string | null;
  "category"?: string | null;
  "confidence"?: "CONFIRMED" | "HIGH" | "MODERATE" | "LOW" | "UNKNOWN" | null;
  "evidence"?: Array<string>;
  "contributing_factors"?: Array<string>;
  "secondary_effects"?: Array<string>;
  "not_proven"?: Array<string>;
};
  "resolution": {
  "summary"?: string | null;
  "final_actions"?: Array<string>;
  "permanent_fix"?: string | null;
  "temporary_workaround"?: string | null;
};
  "validation": {
  "performed"?: Array<string>;
  "successful"?: Array<string>;
  "failed"?: Array<string>;
  "pending"?: Array<string>;
};
  "current_status": {
  "primary_remediation"?: "COMPLETE" | "INCOMPLETE" | null;
  "user_functionality"?: "RESTORED" | "DEGRADED" | "UNKNOWN" | null;
  "validation"?: "COMPLETE" | "PARTIAL" | "PENDING" | null;
  "monitoring_required"?: "YES" | "NO" | null;
  "follow_up_required"?: "YES" | "NO" | null;
  "recommended_ticket_state"?: string | null;
};
  "follow_up": Array<{
  "action"?: string | null;
  "priority"?: string | null;
  "owner"?: string | null;
  "due"?: string | null;
}>;
  "classification": {
  "category"?: string | null;
  "subcategory"?: string | null;
  "cause_type"?: string | null;
  "platforms"?: Array<string>;
  "applications"?: Array<string>;
  "services"?: Array<string>;
  "technologies"?: Array<string>;
  "tags"?: Array<string>;
  "security_relevant"?: boolean | null;
  "hardware_relevant"?: boolean | null;
  "network_relevant"?: boolean | null;
  "kb_candidate"?: boolean | null;
  "automation_candidate"?: boolean | null;
  "recurrence_risk"?: string | null;
};
  "automation_opportunity": {
  "candidate"?: boolean | null;
  "name"?: string | null;
  "trigger"?: string | null;
  "inputs"?: Array<string>;
  "diagnostic_logic"?: Array<string>;
  "safe_actions"?: Array<string>;
  "approval_required_actions"?: Array<string>;
  "risks"?: Array<string>;
  "estimated_time_savings_minutes"?: number | null;
};
  "knowledge": {
  "kb_title"?: string | null;
  "one_line_resolution"?: string | null;
  "warnings"?: Array<string>;
  "lessons_learned"?: Array<string>;
  "escalation_conditions"?: Array<string>;
  "reusable_ip_opportunities"?: Array<string>;
};
  "artifact_log_references": Array<{
  "type"?: string | null;
  "name"?: string | null;
  "path_or_reference"?: string | null;
  "description"?: string | null;
}>;
  "security": {
  "credentials_present"?: boolean | null;
  "credentials_redacted"?: boolean | null;
  "security_incident_suspected"?: boolean | null;
  "security_notes"?: string | null;
};
  "data_quality": {
  "overall_confidence"?: "CONFIRMED" | "HIGH" | "MODERATE" | "LOW" | "UNKNOWN" | null;
  "missing_important_information"?: Array<string>;
  "conflicting_information"?: Array<string>;
  "assumptions"?: Array<string>;
};
};
export type ResolutionConfidence = 'CONFIRMED' | 'HIGH' | 'MODERATE' | 'LOW' | 'UNKNOWN';
export type ResolutionClaimKind = 'reported_fact' | 'supported_conclusion' | 'hypothesis' | 'unverified' | 'pending_validation';
