export default function Terms() {
  return (
    <div className="container max-w-3xl mx-auto py-12 px-4 font-sans prose prose-invert">
      <h1 className="text-4xl font-bold mb-8">Terms of Service</h1>
      <p className="text-sm font-mono text-muted-foreground mb-8">Last Updated: SYSTEM_CURRENT_DATE</p>
      
      <section className="space-y-4 text-foreground/80">
        <h2 className="text-2xl font-bold text-foreground">1. Acceptance of Terms</h2>
        <p>By accessing and using NinjaLaunchKit (the "Service"), you accept and agree to be bound by the terms and provision of this agreement.</p>
        
        <h2 className="text-2xl font-bold text-foreground mt-8">2. Description of Service</h2>
        <p>NinjaLaunchKit provides marketing copy generation tools for businesses and creators. We reserve the right to modify or discontinue the Service with or without notice to you.</p>

        <h2 className="text-2xl font-bold text-foreground mt-8">3. User Conduct</h2>
        <p>You agree to use the Service only for lawful purposes. You are solely responsible for the knowledge and adherence to any and all laws, rules, and regulations pertaining to your use of the Service.</p>

        <h2 className="text-2xl font-bold text-foreground mt-8">4. Generated Content</h2>
        <p>The copy generated by our Service is provided "as is". While we strive for high quality, we do not guarantee the performance or results of any marketing campaigns utilizing our generated content.</p>
      </section>
    </div>
  );
}