import { Ionicons } from "@expo/vector-icons";
import { LinearGradient } from "expo-linear-gradient";
import { useState } from "react";
import { Image, ImageBackground, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { useAuth } from "../lib/auth";
import { colors } from "../lib/theme";
import { Button, SectionTitle, Shell } from "./Shell";

const photos = {
  hero: require("../../assets/hero.png"),
  engine: require("../../assets/engine.jpg"),
  efi: require("../../assets/efi.jpg"),
  timing: require("../../assets/timing.jpg"),
  throttle: require("../../assets/throttle.jpg"),
};

const posts = [
  { type: "BUILD LOG", title: "The $900 junkyard K24 finally made boost", vehicle: "1994 Honda Civic CX", spec: "K24A2 · 8 PSI · 287 WHP", author: "Maya R.", image: photos.efi, likes: 419 },
  { type: "HOW-TO", title: "Rail-pressure drop without firing the parts cannon", vehicle: "2006 Ram 2500", spec: "5.9 Cummins · 312K miles", author: "Derek Cole", image: photos.engine, likes: 231 },
];

const listings = [
  { title: "Ported V8 cylinder head", price: "$685", seller: "Arc & Anvil", image: photos.engine },
  { title: "Polished V8 intake & EFI", price: "$950", seller: "Nate's Garage", image: photos.efi },
  { title: "Timing service hardware", price: "$142", seller: "LayerShift", image: photos.timing },
  { title: "LS throttle-body assembly", price: "$320", seller: "Trail Rat", image: photos.throttle },
];

export function FeedScreen() {
  const { user, launchOperatorOs } = useAuth();
  return (
    <Shell>
      {user ? <View style={styles.verified}><Ionicons name="shield-checkmark" size={15} color={colors.orangeHot} /><Text style={styles.verifiedLabel}>OPERATOROS VERIFIED</Text><Text style={styles.verifiedTenant} numberOfLines={1}>{user.tenant.name}</Text></View> : null}
      <ImageBackground source={photos.hero} style={styles.hero} imageStyle={styles.heroImage}>
        <LinearGradient colors={["rgba(7,8,8,.12)", "rgba(7,8,8,.55)", colors.ink]} style={StyleSheet.absoluteFill} />
        <View style={styles.heroContent}>
          <Text style={styles.kicker}>THE DIGITAL GARAGE IS OPEN</Text>
          <Text style={styles.heroTitle}>BUILT BY WRENCHERS.{"\n"}<Text>POWERED BY THE SHED.</Text></Text>
          <Text style={styles.heroCopy}>Document the build. Diagnose the problem. Trade the parts. Find the people who already broke—and fixed—what you&apos;re working on.</Text>
          <Button label={user ? "POST YOUR BUILD" : "CONTINUE WITH OPERATOROS"} icon={user ? "add" : "shield-checkmark-outline"} onPress={user ? undefined : () => void launchOperatorOs()} />
        </View>
      </ImageBackground>
      <View style={styles.metrics}><Metric value="12.4K" label="BUILDERS" /><Metric value="38K" label="FIXES" /><Metric value="4.9" label="SELLERS" /></View>
      <SectionTitle kicker="SHOP FEED / FOR YOU" title="WHAT'S HAPPENING IN THE GARAGE" />
      <View style={styles.stack}>{posts.map((post) => <PostCard key={post.title} {...post} />)}</View>
      <View style={styles.assistPromo}><View style={styles.assistIcon}><Ionicons name="hardware-chip-outline" size={25} color={colors.orangeHot} /></View><Text style={styles.kicker}>TORQUE ASSIST</Text><Text style={styles.cardTitle}>KNOW WHAT THE CODE REALLY MEANS.</Text><Text style={styles.copy}>Evidence-led test plans built from your vehicle, symptoms, and scan data.</Text><Button label="START A DIAGNOSIS" /></View>
    </Shell>
  );
}

function PostCard(post: typeof posts[number]) {
  const [liked, setLiked] = useState(false);
  return <View style={styles.card}><ImageBackground source={post.image} style={styles.postImage}><LinearGradient colors={["transparent", "rgba(6,7,7,.92)"]} style={StyleSheet.absoluteFill} /><Text style={styles.tag}>{post.type}</Text><Text style={styles.vehicle}>{post.vehicle}</Text><Text style={styles.spec}>{post.spec}</Text></ImageBackground><View style={styles.cardBody}><View style={styles.byline}><View style={styles.miniAvatar}><Text style={styles.miniAvatarText}>{post.author.split(" ").map(x => x[0]).join("")}</Text></View><Text style={styles.bylineText}>{post.author}<Text style={styles.muted}>  ·  24 min ago</Text></Text></View><Text style={styles.cardTitle}>{post.title}</Text><View style={styles.cardActions}><Pressable style={styles.actionButton} onPress={() => setLiked(!liked)}><Ionicons name={liked ? "heart" : "heart-outline"} size={20} color={liked ? colors.orangeHot : colors.muted} /><Text style={styles.actionText}>{post.likes + (liked ? 1 : 0)}</Text></Pressable><Pressable style={styles.actionButton}><Ionicons name="chatbubble-outline" size={19} color={colors.muted} /><Text style={styles.actionText}>63</Text></Pressable><Pressable style={[styles.actionButton, styles.save]}><Ionicons name="bookmark-outline" size={19} color={colors.muted} /><Text style={styles.actionText}>SAVE</Text></Pressable></View></View></View>;
}

export function AssistScreen() {
  const { user, launchOperatorOs } = useAuth();
  const [code, setCode] = useState("P0302");
  const [symptoms, setSymptoms] = useState("Rough idle, flashing CEL under load, fuel smell at startup");
  const [result, setResult] = useState(false);
  return <Shell title="Torque Assist"><SectionTitle kicker="AI DIAGNOSTICS / EVIDENCE FIRST" title="PARTS SECOND." /><View style={styles.formCard}><View style={styles.step}><Text style={styles.stepNumber}>01</Text><View><Text style={styles.formTitle}>WHAT IS THE VEHICLE DOING?</Text><Text style={styles.muted}>One plan uses 2 tokens</Text></View></View><Field label="OBD-II / MANUFACTURER CODE" value={code} onChangeText={(value) => setCode(value.toUpperCase())} /><Field label="SYMPTOMS, CONDITIONS & RECENT WORK" value={symptoms} onChangeText={setSymptoms} multiline /><Button label={result ? "REFRESH TEST PLAN" : "BUILD MY TEST PLAN"} icon="sparkles-outline" onPress={() => user ? setResult(true) : void launchOperatorOs()} /></View>{result ? <View style={styles.result}><View style={styles.confidence}><Text style={styles.confidenceText}>82% CONFIDENCE</Text></View><Text style={styles.cardTitle}>MISFIRE DETECTED ON CYLINDER 2</Text><Text style={styles.copy}>The load condition makes ignition breakdown most likely. Confirm it before buying parts.</Text>{["Swap coil 2 with coil 3", "Inspect and measure plug gap", "Run injector balance check"].map((step, index) => <View style={styles.test} key={step}><Text style={styles.testNumber}>0{index + 1}</Text><Text style={styles.testText}>{step}</Text><Ionicons name="chevron-forward" size={18} color={colors.muted} /></View>)}</View> : <View style={styles.empty}><Ionicons name="scan-circle-outline" size={54} color={colors.orangeHot} /><Text style={styles.cardTitle}>YOUR TEST PLAN WILL APPEAR HERE</Text><Text style={styles.copy}>Weigh the code against the exact vehicle and symptoms—then test the cheapest, fastest failure path first.</Text></View>}</Shell>;
}

function Field({ label, ...props }: { label: string; value: string; onChangeText: (value: string) => void; multiline?: boolean }) { return <View style={styles.field}><Text style={styles.fieldLabel}>{label}</Text><TextInput {...props} placeholderTextColor="#666C69" style={[styles.input, props.multiline && styles.textarea]} /></View>; }

export function BuildsScreen() {
  return <Shell title="Build Library"><SectionTitle kicker="BUILD LIBRARY" title="REAL WORK. FULLY DOCUMENTED." /><View style={styles.stack}>{posts.map((post, index) => <ImageBackground source={post.image} style={styles.buildCard} imageStyle={styles.buildImage} key={post.title}><LinearGradient colors={["rgba(7,8,8,.2)", "rgba(7,8,8,.96)"]} style={StyleSheet.absoluteFill} /><Text style={styles.buildNumber}>0{index + 1}</Text><Text style={styles.tag}>{post.type}</Text><View style={styles.buildContent}><Text style={styles.cardTitle}>{post.title}</Text><Text style={styles.copy}>{post.spec}</Text><Button label="OPEN BUILD JOURNAL" secondary /></View></ImageBackground>)}</View><View style={styles.blueprint}><Text style={styles.kicker}>FEATURED COLLECTION / 23 BUILDS</Text><Text style={styles.cardTitle}>FIRST-TIME ENGINE SWAP FIELD GUIDE</Text><Text style={styles.copy}>Organized by chassis, powertrain, budget, and fabrication level.</Text></View></Shell>;
}

export function MarketScreen() {
  return <Shell title="DIY Marketplace"><SectionTitle kicker="DIY MARKETPLACE" title="MADE IN GARAGES. BACKED BY REPUTATION." /><View style={styles.protection}><Ionicons name="shield-checkmark-outline" size={30} color={colors.orangeHot} /><View><Text style={styles.protectionTitle}>OPTIONAL TORQUESHED PROTECTION</Text><Text style={styles.muted}>Protected checkout, tracking, and dispute window.</Text></View></View><View style={styles.listingGrid}>{listings.map((item) => <View style={styles.listing} key={item.title}><Image source={item.image} style={styles.listingImage} /><View style={styles.listingBody}><Text style={styles.price}>{item.price}</Text><Text style={styles.listingTitle}>{item.title}</Text><Text style={styles.muted}>{item.seller}  ·  ★ 4.9</Text><Pressable style={styles.viewListing}><Text style={styles.viewListingText}>VIEW LISTING</Text><Ionicons name="arrow-forward" size={14} color={colors.orangeHot} /></Pressable></View></View>)}</View></Shell>;
}

export function GarageScreen() {
  const { user, launchOperatorOs, signOut } = useAuth();
  if (!user) return <Shell title="My Garage"><View style={styles.guestGarage}><View style={styles.guestIcon}><Ionicons name="speedometer-outline" size={38} color={colors.orangeHot} /></View><Text style={styles.kicker}>YOUR GARAGE STARTS HERE</Text><Text style={styles.heroTitle}>ONE IDENTITY.{"\n"}<Text>EVERY BUILD.</Text></Text><Text style={styles.copy}>Launch from OperatorOS to keep your vehicles, diagnostics, build journals, and marketplace reputation together.</Text><Button label="CONTINUE WITH OPERATOROS" icon="shield-checkmark-outline" onPress={() => void launchOperatorOs()} /></View></Shell>;
  return <Shell title="My Garage"><View style={styles.profile}><View style={styles.profileAvatar}><Text style={styles.profileAvatarText}>{user.displayName.slice(0, 2).toUpperCase()}</Text></View><Text style={styles.kicker}>MY TORQUESHED GARAGE</Text><Text style={styles.profileName}>{user.displayName}</Text><Text style={styles.muted}>{user.email}</Text><View style={styles.profileVerified}><Ionicons name="shield-checkmark" size={15} color={colors.green} /><Text style={styles.profileVerifiedText}>OPERATOROS VERIFIED · {user.tenant.name.toUpperCase()}</Text></View><View style={styles.profileStats}><Metric value="2" label="VEHICLES" /><Metric value="18" label="ENTRIES" /><Metric value="847" label="REP" /></View></View><SectionTitle kicker="ACTIVE BUILDS" title="YOUR MACHINES" />{[{ name: "1994 Honda Civic CX", spec: "K24A2 · Precision 5858 · 8 PSI", percent: "72%" }, { name: "2006 Ram 2500 SLT", spec: "5.9 Cummins · G56 · 312K miles", percent: "91%" }].map((car) => <View style={styles.vehicleCard} key={car.name}><View style={styles.vehicleTop}><Text style={styles.vehicleTopText}>ACTIVE BUILD</Text><Text style={styles.vehicleTopText}>{car.percent}</Text></View><Text style={styles.cardTitle}>{car.name}</Text><Text style={styles.copy}>{car.spec}</Text><View style={styles.progress}><View style={{ width: car.percent as `${number}%` }} /></View></View>)}<Pressable style={styles.signOut} onPress={() => void signOut()}><Ionicons name="log-out-outline" size={17} color={colors.muted} /><Text style={styles.signOutText}>SIGN OUT</Text></Pressable></Shell>;
}

function Metric({ value, label }: { value: string; label: string }) { return <View style={styles.metric}><Text style={styles.metricValue}>{value}</Text><Text style={styles.metricLabel}>{label}</Text></View>; }

const styles = StyleSheet.create({
  kicker: { color: colors.orangeHot, fontSize: 9, fontWeight: "900", letterSpacing: 1.5 }, muted: { color: colors.muted, fontSize: 11 }, copy: { marginTop: 10, color: colors.muted, fontSize: 13, lineHeight: 20 },
  hero: { minHeight: 600, justifyContent: "flex-end" }, heroImage: { resizeMode: "cover" }, heroContent: { padding: 20, paddingBottom: 32 }, heroTitle: { marginTop: 10, color: colors.paper, fontSize: 42, lineHeight: 40, fontWeight: "900", letterSpacing: -2, textTransform: "uppercase" },
  heroCopy: { marginVertical: 20, color: "#C0C3BF", fontSize: 14, lineHeight: 22 }, verified: { minHeight: 38, flexDirection: "row", alignItems: "center", gap: 8, paddingHorizontal: 16, borderBottomWidth: 1, borderBottomColor: "#54351F", backgroundColor: "#21150F" }, verifiedLabel: { color: colors.orangeHot, fontSize: 8, fontWeight: "900", letterSpacing: .8 }, verifiedTenant: { flex: 1, color: "#B6BAB7", fontSize: 9 },
  metrics: { flexDirection: "row", marginHorizontal: 16, marginTop: -1, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.panel }, metric: { flex: 1, alignItems: "center", paddingVertical: 16 }, metricValue: { color: colors.paper, fontSize: 19, fontWeight: "900" }, metricLabel: { marginTop: 3, color: colors.muted, fontSize: 7, fontWeight: "800", letterSpacing: .7 },
  stack: { gap: 14, paddingHorizontal: 16 }, card: { overflow: "hidden", borderWidth: 1, borderColor: colors.line, backgroundColor: colors.panel }, postImage: { height: 260, justifyContent: "flex-end", padding: 16 }, tag: { alignSelf: "flex-start", marginBottom: "auto", paddingHorizontal: 8, paddingVertical: 6, color: "#fff", backgroundColor: colors.orange, fontSize: 8, fontWeight: "900", letterSpacing: 1 },
  vehicle: { color: colors.paper, fontSize: 25, fontWeight: "900", letterSpacing: -.8, textTransform: "uppercase" }, spec: { marginTop: 4, color: "#B2B6B3", fontSize: 9, fontWeight: "700", letterSpacing: .5 }, cardBody: { padding: 18 }, byline: { flexDirection: "row", alignItems: "center", gap: 9 },
  miniAvatar: { width: 30, height: 30, alignItems: "center", justifyContent: "center", borderRadius: 15, borderWidth: 1, borderColor: "#70452C", backgroundColor: "#281A14" }, miniAvatarText: { color: colors.orangeHot, fontSize: 8, fontWeight: "900" }, bylineText: { color: colors.paper, fontSize: 11, fontWeight: "700" }, cardTitle: { marginTop: 16, color: colors.paper, fontSize: 25, lineHeight: 25, fontWeight: "900", letterSpacing: -1, textTransform: "uppercase" },
  cardActions: { flexDirection: "row", alignItems: "center", gap: 18, marginTop: 20, paddingTop: 14, borderTopWidth: 1, borderTopColor: colors.line }, actionButton: { flexDirection: "row", alignItems: "center", gap: 5 }, actionText: { color: colors.muted, fontSize: 9, fontWeight: "800" }, save: { marginLeft: "auto" }, assistPromo: { margin: 16, marginTop: 34, padding: 22, borderWidth: 1, borderColor: "#624026", backgroundColor: "#1C1410" }, assistIcon: { width: 48, height: 48, alignItems: "center", justifyContent: "center", marginBottom: 20, borderWidth: 1, borderColor: "#713F20", backgroundColor: "#2A180F" },
  formCard: { marginHorizontal: 16, padding: 20, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.panel }, step: { flexDirection: "row", gap: 12, alignItems: "center", paddingBottom: 18, borderBottomWidth: 1, borderBottomColor: colors.line }, stepNumber: { color: colors.orangeHot, fontSize: 11, fontWeight: "900" }, formTitle: { color: colors.paper, fontSize: 16, fontWeight: "900" },
  field: { marginTop: 20 }, fieldLabel: { color: "#B9BDBA", fontSize: 9, fontWeight: "800", letterSpacing: .7 }, input: { minHeight: 50, marginTop: 8, paddingHorizontal: 14, color: colors.paper, borderWidth: 1, borderColor: "#3A3F3D", backgroundColor: colors.panelLift }, textarea: { minHeight: 120, paddingTop: 14, textAlignVertical: "top" }, result: { margin: 16, padding: 22, borderWidth: 1, borderColor: "#34533E", backgroundColor: colors.panel }, confidence: { alignSelf: "flex-start", paddingHorizontal: 8, paddingVertical: 6, backgroundColor: "#173322" }, confidenceText: { color: colors.green, fontSize: 8, fontWeight: "900", letterSpacing: .7 }, test: { flexDirection: "row", alignItems: "center", gap: 12, paddingVertical: 16, borderBottomWidth: 1, borderBottomColor: colors.line }, testNumber: { color: colors.orangeHot, fontSize: 9, fontWeight: "900" }, testText: { flex: 1, color: colors.paper, fontSize: 12, fontWeight: "700" }, empty: { minHeight: 300, alignItems: "center", justifyContent: "center", margin: 16, padding: 30, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.panel },
  buildCard: { minHeight: 400, justifyContent: "flex-end", padding: 20, overflow: "hidden", borderWidth: 1, borderColor: colors.line }, buildImage: { resizeMode: "cover" }, buildNumber: { position: "absolute", top: 10, right: 16, color: "rgba(255,255,255,.28)", fontSize: 54, fontWeight: "900" }, buildContent: { marginTop: 70 }, blueprint: { margin: 16, padding: 24, borderWidth: 1, borderColor: "#304A63", backgroundColor: "#111B23" },
  protection: { flexDirection: "row", alignItems: "center", gap: 14, marginHorizontal: 16, marginBottom: 18, padding: 16, borderWidth: 1, borderColor: "#644126", backgroundColor: "#201610" }, protectionTitle: { color: colors.paper, fontSize: 11, fontWeight: "900" }, listingGrid: { flexDirection: "row", flexWrap: "wrap", gap: 12, paddingHorizontal: 16 }, listing: { width: "48%", overflow: "hidden", borderWidth: 1, borderColor: colors.line, backgroundColor: colors.panel }, listingImage: { width: "100%", height: 150 }, listingBody: { padding: 13 }, price: { color: colors.orangeHot, fontSize: 21, fontWeight: "900" }, listingTitle: { minHeight: 50, marginVertical: 8, color: colors.paper, fontSize: 16, fontWeight: "900", textTransform: "uppercase" }, viewListing: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginTop: 12, paddingTop: 12, borderTopWidth: 1, borderTopColor: colors.line }, viewListingText: { color: colors.paper, fontSize: 8, fontWeight: "900", letterSpacing: .5 },
  guestGarage: { minHeight: 620, justifyContent: "center", padding: 24 }, guestIcon: { width: 64, height: 64, alignItems: "center", justifyContent: "center", marginBottom: 24, borderWidth: 1, borderColor: "#673D23", backgroundColor: "#281810" }, profile: { alignItems: "center", margin: 16, padding: 25, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.panel }, profileAvatar: { width: 74, height: 74, alignItems: "center", justifyContent: "center", marginBottom: 18, borderRadius: 37, borderWidth: 2, borderColor: "#75452A", backgroundColor: "#2A1A13" }, profileAvatarText: { color: colors.orangeHot, fontSize: 18, fontWeight: "900" }, profileName: { marginTop: 8, color: colors.paper, fontSize: 34, fontWeight: "900", textTransform: "uppercase" }, profileVerified: { flexDirection: "row", alignItems: "center", gap: 6, marginTop: 16, padding: 8, borderWidth: 1, borderColor: "#315139", backgroundColor: "#14221A" }, profileVerifiedText: { color: colors.green, fontSize: 8, fontWeight: "900" }, profileStats: { width: "100%", flexDirection: "row", marginTop: 24, borderTopWidth: 1, borderTopColor: colors.line }, vehicleCard: { marginHorizontal: 16, marginBottom: 12, padding: 20, borderWidth: 1, borderColor: "#523722", backgroundColor: colors.panel }, vehicleTop: { flexDirection: "row", justifyContent: "space-between" }, vehicleTopText: { color: colors.orangeHot, fontSize: 8, fontWeight: "900", letterSpacing: .7 }, progress: { height: 5, marginTop: 20, backgroundColor: colors.line }, signOut: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8, margin: 16, padding: 14 }, signOutText: { color: colors.muted, fontSize: 9, fontWeight: "900", letterSpacing: .7 },
});
