import { expect, test, type Page } from '@playwright/test';
import { Client } from 'pg';
import { establishParitySession } from './parity-auth';

const exactHost=process.env.E2E_PRODUCTION_HOSTS==='1';
const WEB=process.env.E2E_SNAPPROOFOS_URL??(exactHost?'https://snapproofos.operatoros.net':(process.env.E2E_WEB_URL??'http://127.0.0.1:5000'));
const API=process.env.E2E_API_URL??'http://127.0.0.1:5001';
const viewports=[{name:'desktop',width:1440,height:1000},{name:'tablet',width:900,height:1000},{name:'mobile',width:390,height:844}] as const;

async function labelled(page:Page){const failures=await page.locator('input,select,textarea').evaluateAll(controls=>controls.flatMap(control=>{const node=control as HTMLInputElement;const box=node.getBoundingClientRect();if(!box.width||!box.height||getComputedStyle(node).visibility==='hidden')return[];return node.getAttribute('aria-label')||node.getAttribute('aria-labelledby')||node.closest('label')?[]:[node.outerHTML.slice(0,120)];}));expect(failures).toEqual([]);}

async function exactHostSession(page:Page){const databaseUrl=process.env.DATABASE_URL;if(!databaseUrl)throw new Error('DATABASE_URL is required');const email=`phase32-${Date.now()}@example.com`;const password='Phase32-Disposable-Only-9!';const registration=await page.request.post(`${API}/v1/auth/register`,{headers:{host:'auth.operatoros.net','x-forwarded-host':'auth.operatoros.net','x-forwarded-proto':'https'},data:{email,password,name:'Phase 32 Exact Host'}});expect(registration.status(),await registration.text()).toBe(202);const pg=new Client({connectionString:databaseUrl});await pg.connect();try{const identity=await pg.query<{user_id:string;tenant_id:string}>('select id as user_id,current_tenant_id as tenant_id from users where email=$1',[email]);const elite=await pg.query<{id:string}>("select id from subscription_plans where slug='elite' and is_active=true limit 1");await pg.query("insert into subscriptions(user_id,plan_id,status,current_period_start,current_period_end,tenant_id,scope_type) values($1,$2,'active',now(),now()+interval '30 days',$3,'tenant')",[identity.rows[0]!.user_id,elite.rows[0]!.id,identity.rows[0]!.tenant_id]);await pg.query("insert into tenant_modules(tenant_id,module_id,status,source,allow_all_members) select $1,id,'enabled','included',true from modules where slug='snapproofos' on conflict do nothing",[identity.rows[0]!.tenant_id]);}finally{await pg.end();}await page.goto(`${WEB}/jobs`);await expect(page).toHaveURL(/^https:\/\/auth\.operatoros\.net\/login\?/);await page.getByTestId('input-email').fill(email);await page.getByTestId('input-password').fill(password);await Promise.all([page.waitForURL(/^https:\/\/snapproofos\.operatoros\.net\/jobs/),page.getByTestId('button-login').click()]);}

test.describe('Phase 32 SnapProofOS field product contract',()=>{test.setTimeout(240_000);test('desktop tablet and mobile routes preserve field-console usability and accessibility',async({page})=>{if(exactHost)await exactHostSession(page);else await establishParitySession(page.request);await page.emulateMedia({reducedMotion:'reduce',colorScheme:'dark'});const prefix=exactHost?'':'/modules/snapproofos';const routes=[['/customers','snapproofos-customers'],['/jobs','snapproofos-jobs'],['/capture','snapproofos-capture'],['/work','snapproofos-work'],['/costs','snapproofos-costs'],['/templates','snapproofos-templates'],['/team','snapproofos-team'],['/activity','snapproofos-activity'],['/branding','snapproofos-branding'],['/reports','snapproofos-reports'],['/review','snapproofos-review']] as const;for(const viewport of viewports){await page.setViewportSize(viewport);for(const[route,id]of routes){const response=await page.goto(`${WEB}${prefix}${route}`,{waitUntil:'networkidle'});expect(response?.status(),route).toBeLessThan(400);await expect(page.getByTestId('snapproofos-workspace')).toBeVisible();await expect(page.locator(`#${id}`)).toBeVisible();await expect(page.locator('body')).not.toContainText(/coming soon|not implemented|placeholder action|fake report/i);expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth),`${viewport.name} ${route} overflow`).toBeLessThanOrEqual(1);await labelled(page);}await page.goto(`${WEB}${prefix}/jobs`,{waitUntil:'networkidle'});await page.screenshot({path:`test-results/playwright/snapproofos-phase32-${viewport.name}.png`,fullPage:true,animations:'disabled'});}});});
