import { Link } from "wouter";
import { Button } from "@/components/ui/button";
import { ArrowLeft } from "lucide-react";

export function PrivacyPage() {
  return (
    <div className="min-h-screen bg-background">
      <header className="border-b">
        <div className="max-w-3xl mx-auto px-6 py-4">
          <Link href="/">
            <Button variant="ghost" size="sm" className="gap-1.5">
              <ArrowLeft className="h-4 w-4" /> Back to BrandForge
            </Button>
          </Link>
        </div>
      </header>
      <main className="max-w-3xl mx-auto px-6 py-12 prose prose-sm dark:prose-invert">
        <h1 className="text-3xl font-bold tracking-tight">Privacy Policy</h1>
        <p className="text-muted-foreground text-sm">Last updated: April 1, 2026</p>

        <h2>1. Information We Collect</h2>
        <p>BrandForge collects information you provide directly, including your name, email address, and workspace data. We also collect usage data such as feature interactions and session duration to improve the service.</p>

        <h2>2. How We Use Your Information</h2>
        <p>We use your information to provide and maintain BrandForge, personalize AI-generated content to your brand, process transactions, and communicate important updates about the service.</p>

        <h2>3. Data Isolation</h2>
        <p>Each workspace operates in a fully isolated tenant environment. Your brand data, generated content, and analytics are never shared between workspaces or with other users. AI models do not retain your data between sessions.</p>

        <h2>4. Data Security</h2>
        <p>We implement industry-standard security measures including encrypted data transmission (TLS 1.3), access-controlled storage, and tenant-scoped authentication to protect your information.</p>

        <h2>5. Data Retention</h2>
        <p>Your data is retained for the duration of your active subscription. Upon cancellation, data is preserved for 30 days before permanent deletion. You may request immediate data export or deletion at any time from Settings.</p>

        <h2>6. Third-Party Services</h2>
        <p>BrandForge integrates with third-party AI providers for content generation. These providers process data according to their own privacy policies, but BrandForge only sends the minimum context necessary for generation.</p>

        <h2>7. Your Rights</h2>
        <p>You have the right to access, correct, export, or delete your personal data. Contact us at privacy@brandforge.com for any data-related requests.</p>

        <h2>8. Changes to This Policy</h2>
        <p>We may update this policy from time to time. Significant changes will be communicated via email or in-app notification at least 30 days before taking effect.</p>
      </main>
    </div>
  );
}

export function TermsPage() {
  return (
    <div className="min-h-screen bg-background">
      <header className="border-b">
        <div className="max-w-3xl mx-auto px-6 py-4">
          <Link href="/">
            <Button variant="ghost" size="sm" className="gap-1.5">
              <ArrowLeft className="h-4 w-4" /> Back to BrandForge
            </Button>
          </Link>
        </div>
      </header>
      <main className="max-w-3xl mx-auto px-6 py-12 prose prose-sm dark:prose-invert">
        <h1 className="text-3xl font-bold tracking-tight">Terms of Service</h1>
        <p className="text-muted-foreground text-sm">Last updated: April 1, 2026</p>

        <h2>1. Acceptance of Terms</h2>
        <p>By accessing or using BrandForge, you agree to be bound by these Terms of Service. If you do not agree, you may not use the service.</p>

        <h2>2. Service Description</h2>
        <p>BrandForge is a multi-tenant marketing operating system that provides brand management, AI-powered content generation, campaign planning, scheduling, analytics, and reporting tools.</p>

        <h2>3. Accounts and Workspaces</h2>
        <p>You are responsible for maintaining the security of your account and workspace. Each workspace is isolated; you are responsible for all activity within workspaces you own or administer.</p>

        <h2>4. Subscription and Billing</h2>
        <p>Paid plans are billed monthly or annually as selected. You may upgrade, downgrade, or cancel at any time from Settings. Refunds follow our standard refund policy — unused portions of annual subscriptions are prorated.</p>

        <h2>5. AI-Generated Content</h2>
        <p>Content generated by BrandForge's AI tools is owned by you. BrandForge does not claim ownership of generated content. AI outputs are suggestions and should be reviewed before publishing.</p>

        <h2>6. Acceptable Use</h2>
        <p>You agree not to use BrandForge to generate harmful, misleading, or illegal content. We reserve the right to suspend accounts that violate this policy.</p>

        <h2>7. Service Availability</h2>
        <p>We strive for 99.9% uptime but do not guarantee uninterrupted access. Scheduled maintenance will be communicated in advance. AI credit usage is subject to plan limits.</p>

        <h2>8. Limitation of Liability</h2>
        <p>BrandForge is provided "as is." We are not liable for indirect, incidental, or consequential damages arising from your use of the service, including any business decisions made based on AI-generated recommendations.</p>

        <h2>9. Termination</h2>
        <p>Either party may terminate this agreement at any time. Upon termination, your data will be retained for 30 days before permanent deletion. You may export your data at any time before deletion.</p>

        <h2>10. Changes to Terms</h2>
        <p>We may update these terms from time to time. Continued use of BrandForge after changes constitutes acceptance. Material changes will be communicated via email at least 30 days in advance.</p>
      </main>
    </div>
  );
}
