import Link from 'next/link';
import { ArrowRight, Check, Crosshair, Layers3, Palette, Rocket, ShieldCheck } from 'lucide-react';

const plans = [
  { name: 'Free', detail: '2 kits per month, TXT export, tactical watermark, one unlocked visual brief.', features: ['20-template catalog previews', 'Deterministic generation', 'Facebook visual brief'] },
  { name: 'Pro', detail: 'Unlimited kits, five brands, all export formats, all nine visual briefs.', features: ['Shared AI refinement + fallback', 'Email and SMS sequences', 'Unwatermarked exports'] },
  { name: 'Agency', detail: 'Unlimited brands, white-label delivery, client-ready commercial workflows.', features: ['White-label exports', 'Client workspace entitlement', 'All premium templates'] },
];

const shell: React.CSSProperties = { minHeight: '100vh', color: '#fafafa', background: 'radial-gradient(circle at 20% 0%,rgba(127,29,29,.34),transparent 38%),#050506', colorScheme: 'dark' };
const card: React.CSSProperties = { border: '1px solid rgba(248,113,113,.22)', borderRadius: 20, background: 'linear-gradient(145deg,rgba(24,24,27,.96),rgba(9,9,11,.98))', padding: 22 };

function Chrome({ children }: { children: React.ReactNode }) {
  return <div style={shell}><header style={{ maxWidth: 1180, margin: '0 auto', padding: '22px clamp(18px,4vw,44px)', display: 'flex', alignItems: 'center', gap: 14 }}><div style={{ width: 42, height: 42, borderRadius: 13, display: 'grid', placeItems: 'center', background: 'linear-gradient(145deg,#ef4444,#450a0a)' }}><Rocket size={22} /></div><Link href="/" style={{ color: '#fff', textDecoration: 'none', fontWeight: 950, fontSize: 20 }}>Ninja Launch Kit</Link><nav aria-label="Public navigation" style={{ marginLeft: 'auto', display: 'flex', gap: 15, alignItems: 'center' }}><Link href="/pricing" style={{ color: '#d4d4d8' }}>Pricing</Link><Link href="/contact" style={{ color: '#d4d4d8' }}>Contact</Link><Link href="/login" style={{ color: '#fff', textDecoration: 'none', padding: '9px 13px', borderRadius: 10, background: '#b91c1c' }}>Sign in</Link></nav></header>{children}<footer style={{ maxWidth: 1180, margin: '0 auto', padding: '36px clamp(18px,4vw,44px)', color: '#a1a1aa', display: 'flex', flexWrap: 'wrap', gap: 16 }}><span>© Shotgun Ninjas Productions, LLC</span><Link href="/terms" style={{ color: '#d4d4d8' }}>Terms</Link><Link href="/privacy" style={{ color: '#d4d4d8' }}>Privacy</Link></footer></div>;
}

function Home() {
  return <Chrome><main><section style={{ maxWidth: 1180, margin: '0 auto', padding: '76px clamp(18px,4vw,44px) 54px', display: 'grid', gridTemplateColumns: 'minmax(0,1.25fr) minmax(300px,.75fr)', gap: 34, alignItems: 'center' }}><div><span style={{ color: '#fca5a5', letterSpacing: '.2em', fontWeight: 900, fontSize: 12 }}>FROM BRIEF TO LAUNCH-READY</span><h1 style={{ fontSize: 'clamp(42px,7vw,82px)', lineHeight: .95, margin: '14px 0 22px', maxWidth: 850 }}>Build the whole launch. <span style={{ color: '#ef4444' }}>Miss nothing.</span></h1><p style={{ color: '#d4d4d8', fontSize: 19, lineHeight: 1.65, maxWidth: 760 }}>Turn a short business brief into landing copy, ad campaigns, email and SMS, social posts, FAQ, CTAs, flyer copy, a checklist, and nine real production briefs.</p><div style={{ display: 'flex', gap: 12, flexWrap: 'wrap', marginTop: 28 }}><Link href="/signup" style={{ color: '#fff', textDecoration: 'none', background: 'linear-gradient(135deg,#dc2626,#7f1d1d)', padding: '13px 18px', borderRadius: 11, fontWeight: 900, display: 'inline-flex', gap: 8 }}>Build a launch kit <ArrowRight size={18} /></Link><Link href="/pricing" style={{ color: '#fff', textDecoration: 'none', border: '1px solid rgba(248,113,113,.3)', padding: '13px 18px', borderRadius: 11 }}>Compare plans</Link></div></div><aside style={{ ...card, transform: 'rotate(1deg)' }}><Crosshair color="#f87171" /><h2>One controlled output package</h2>{['Landing + offer copy','Paid and organic campaigns','Email + SMS sequences','FAQ, CTAs, QR/flyer copy','Nine visual-promo briefs','Audited TXT / Markdown / JSON'].map((item) => <p key={item} style={{ display: 'flex', gap: 8, color: '#d4d4d8' }}><Check size={17} color="#4ade80" />{item}</p>)}</aside></section><section style={{ maxWidth: 1180, margin: '0 auto', padding: '24px clamp(18px,4vw,44px) 70px', display: 'grid', gridTemplateColumns: 'repeat(3,minmax(0,1fr))', gap: 14 }}>{[[Layers3,'20 niche templates','Compiler-derived from the pinned product source.'],[Palette,'Nine creative briefs','Dimensions, composition, palette, tools, and plan enforcement.'],[ShieldCheck,'OperatorOS controlled','Central identity, entitlement, billing, credits, audit, and AI providers.']].map(([Icon,title,copy]: any) => <article key={title} style={card}><Icon color="#f87171" /><h2>{title}</h2><p style={{ color: '#a1a1aa', lineHeight: 1.6 }}>{copy}</p></article>)}</section></main></Chrome>;
}

function Pricing() {
  return <Chrome><main style={{ maxWidth: 1180, margin: '0 auto', padding: '70px clamp(18px,4vw,44px)' }}><span style={{ color: '#fca5a5', letterSpacing: '.2em', fontWeight: 900 }}>OPERATOROS ENTITLEMENTS</span><h1 style={{ fontSize: 'clamp(40px,6vw,68px)', margin: '10px 0' }}>Choose your launch capability.</h1><p style={{ color: '#a1a1aa', fontSize: 18 }}>OperatorOS remains the billing source of truth. Checkout and plan changes happen in the parent platform.</p><div style={{ display: 'grid', gridTemplateColumns: 'repeat(3,minmax(0,1fr))', gap: 16, marginTop: 30 }}>{plans.map((plan) => <article key={plan.name} style={{ ...card, borderColor: plan.name === 'Pro' ? '#ef4444' : 'rgba(248,113,113,.22)' }}><h2 style={{ fontSize: 30 }}>{plan.name}</h2><p style={{ color: '#d4d4d8', minHeight: 72 }}>{plan.detail}</p>{plan.features.map((feature) => <p key={feature} style={{ display: 'flex', gap: 8 }}><Check size={16} color="#4ade80" />{feature}</p>)}<Link href="/signup" style={{ display: 'block', textAlign: 'center', color: '#fff', textDecoration: 'none', background: '#991b1b', padding: 12, borderRadius: 10, fontWeight: 900, marginTop: 20 }}>Continue in OperatorOS</Link></article>)}</div></main></Chrome>;
}

function Legal({ privacy = false }: { privacy?: boolean }) {
  return <Chrome><main style={{ maxWidth: 850, margin: '0 auto', padding: '66px clamp(18px,4vw,44px)' }}><h1>{privacy ? 'Privacy' : 'Terms of service'}</h1><p style={{ color: '#a1a1aa' }}>Last updated August 12, 2026</p><div style={{ ...card, lineHeight: 1.75, color: '#d4d4d8' }}>{privacy ? <><h2>Data and authority</h2><p>Ninja Launch Kit stores tenant-scoped business briefs, generated launch assets, brand profiles, revisions, and export history. OperatorOS controls identity, membership, roles, entitlements, billing, provider configuration, and security audit events.</p><h2>Generation privacy</h2><p>Generation prompts exclude platform secrets and should not contain regulated, confidential, or unnecessary personal data. Provider use is recorded by provenance without exposing secret values.</p><h2>Retention and access</h2><p>Soft-deleted product records remain recoverable according to the OperatorOS retention policy. Tenant and user boundaries apply to every authenticated record and download.</p></> : <><h2>Product use</h2><p>You are responsible for reviewing generated copy, claims, destination links, consent language, brand assets, licensing, and legal disclosures before publication. Generated material is a draft, not proof of performance or approval.</p><h2>Plans and billing</h2><p>Plan limits, upgrades, credits, and billing are governed by OperatorOS. Locked content is unavailable until the required entitlement is active.</p><h2>Acceptable use</h2><p>Do not use the service for deceptive claims, unsolicited messaging, rights-infringing assets, unlawful offers, or attempts to cross tenant boundaries.</p></>}</div></main></Chrome>;
}

function Contact() {
  return <Chrome><main style={{ maxWidth: 850, margin: '0 auto', padding: '70px clamp(18px,4vw,44px)' }}><span style={{ color: '#fca5a5', letterSpacing: '.2em', fontWeight: 900 }}>MISSION SUPPORT</span><h1 style={{ fontSize: 'clamp(40px,6vw,66px)' }}>Talk to the OperatorOS team.</h1><div style={card}><p style={{ color: '#d4d4d8', lineHeight: 1.7 }}>For product, plan, account, or launch-workflow help, contact Shotgun Ninjas Productions. Do not send secrets, payment credentials, or sensitive customer data by email.</p><a href="mailto:support@shotgunninjas.com?subject=Ninja%20Launch%20Kit%20support" style={{ display: 'inline-flex', color: '#fff', background: '#991b1b', padding: '12px 16px', borderRadius: 10, textDecoration: 'none', fontWeight: 900 }}>support@shotgunninjas.com</a></div></main></Chrome>;
}

export default async function NinjaLaunchKitPublicPage({ params }: { params: Promise<{ page: string }> }) {
  const { page } = await params;
  if (page === 'pricing') return <Pricing />;
  if (page === 'contact') return <Contact />;
  if (page === 'terms') return <Legal />;
  if (page === 'privacy') return <Legal privacy />;
  return <Home />;
}
