import { createHash, randomBytes } from 'node:crypto';
import type { FastifyInstance, FastifyReply, FastifyRequest } from 'fastify';
import { sql } from 'drizzle-orm';
import { db } from '../db.js';
import { writeAudit } from '../lib/audit.js';
import { requireTenantMember, requireTenantModuleAccess, requireTenantModuleWriteAccess } from '../lib/tenant-auth.js';
import { appendActivityEvent, listActivityEvents } from '../lib/shared-usage-activity.js';
import { requestSharedExport } from '../lib/shared-schedules-exports.js';
import { TORQUESHED_PRODUCT_EXPORT_TYPE } from '../lib/torqueshed-product-export.js';
import { requireTenantPeer, socialCamel, torqueShedSocialModuleId } from '../lib/torqueshed-social-service.js';

const readGuards = [requireTenantMember, requireTenantModuleAccess('torqueshed')];
const writeGuards = [...readGuards, requireTenantModuleWriteAccess];
type Context = { tenantId: string; role: 'owner'|'admin'|'member'; viaPlatformRole: boolean };
class InputError extends Error { constructor(message: string, readonly code='TORQUESHED_INPUT_INVALID', readonly status=400){super(message);} }
const tenant = (request: FastifyRequest) => ((request as any).tenantContext as Context).tenantId;
const actor = (request: FastifyRequest) => String((request as any).user.id);
const canManage = (request: FastifyRequest) => { const c=(request as any).tenantContext as Context; return c.viaPlatformRole||c.role==='owner'||c.role==='admin'||(request as any).tenantModuleAccessLevel==='manager'; };
const camel = (row: unknown) => socialCamel(row as Record<string, any>);
const list = (rows: unknown[]) => rows.map(camel);
function body(request: FastifyRequest){if(!request.body||typeof request.body!=='object'||Array.isArray(request.body))throw new InputError('A JSON object is required');return request.body as Record<string,unknown>;}
function textValue(value: unknown,name:string,max=5000,required=false){if(value===undefined||value===null||value===''){if(required)throw new InputError(`${name} is required`);return null;}if(typeof value!=='string')throw new InputError(`${name} must be text`);const v=value.trim();if((required&&!v)||v.length>max)throw new InputError(`${name} is invalid`);return v;}
function id(request: FastifyRequest,name='id'){const value=(request.params as Record<string,unknown>)[name];if(typeof value!=='string'||!/^[0-9a-f-]{36}$/i.test(value))throw new InputError(`${name} is invalid`);return value;}
function intValue(value:unknown,name:string,min=0,max=2147483647){if(value===undefined||value===null||value==='')return null;const n=Number(value);if(!Number.isSafeInteger(n)||n<min||n>max)throw new InputError(`${name} is invalid`);return n;}
function enumValue<T extends string>(value:unknown,name:string,values:readonly T[],fallback:T):T{if(value===undefined||value===null||value==='')return fallback;if(typeof value!=='string'||!values.includes(value as T))throw new InputError(`${name} is invalid`);return value as T;}
function sendError(reply:FastifyReply,error:unknown){if(error instanceof InputError)return reply.code(error.status).send({error:error.message,code:error.code});const pg=error as {code?:string};if(pg?.code==='23503')return reply.code(404).send({error:'Related record not found',code:'TORQUESHED_NOT_FOUND'});if(pg?.code==='23505')return reply.code(409).send({error:'Matching record already exists',code:'TORQUESHED_CONFLICT'});throw error;}
async function audit(request:FastifyRequest,targetType:string,targetId:string,action:string,after?:Record<string,unknown>){await writeAudit({actorUserId:actor(request),tenantId:tenant(request),targetType,targetId,action,after,extra:{moduleSlug:'torqueshed',phase:28}},request);}
async function activity(request:FastifyRequest,objectType:string,objectId:string,eventType:string,summary:string,metadata?:Record<string,unknown>){return appendActivityEvent({tenantId:tenant(request),moduleId:await torqueShedSocialModuleId(),actorUserId:actor(request),objectType,objectId,eventType,summary,metadata,correlationId:request.id});}
async function ownedBuild(request:FastifyRequest,buildId:string,write=false){const result=await db.execute(sql`SELECT * FROM torqueshed_builds WHERE tenant_id=${tenant(request)} AND id=${buildId} AND archived_at IS NULL AND (${canManage(request)} OR owner_user_id=${actor(request)} OR (${!write} AND visibility IN ('tenant','public_build'))) LIMIT 1`);return result.rows[0] as Record<string,any>|undefined;}
async function visibleDiagnostic(request:FastifyRequest,diagnosticId:string){const result=await db.execute(sql`SELECT d.*,v.year,v.make,v.model,v.nickname,v.vin_last6 FROM torqueshed_diagnostic_sessions d JOIN torqueshed_vehicles v ON v.tenant_id=d.tenant_id AND v.id=d.vehicle_id WHERE d.tenant_id=${tenant(request)} AND d.id=${diagnosticId} AND d.archived_at IS NULL AND (${canManage(request)} OR d.owner_user_id=${actor(request)} OR d.visibility='tenant') LIMIT 1`);return result.rows[0] as Record<string,any>|undefined;}
async function mayCreateShare(request:FastifyRequest,resourceType:string,resourceId:string){
  if(resourceType==='build')return Boolean(await ownedBuild(request,resourceId,true));
  if(resourceType==='diagnostic_report'){const result=await db.execute(sql`SELECT id FROM torqueshed_diagnostic_sessions WHERE tenant_id=${tenant(request)} AND id=${resourceId} AND archived_at IS NULL AND (${canManage(request)} OR owner_user_id=${actor(request)})`);return Boolean(result.rows[0]);}
  if(resourceType==='vehicle_history'){const result=await db.execute(sql`SELECT id FROM torqueshed_vehicles WHERE tenant_id=${tenant(request)} AND id=${resourceId} AND archived_at IS NULL AND (${canManage(request)} OR owner_user_id=${actor(request)})`);return Boolean(result.rows[0]);}
  if(resourceType==='community_post'){const result=await db.execute(sql`SELECT id FROM torqueshed_community_posts WHERE tenant_id=${tenant(request)} AND id=${resourceId} AND archived_at IS NULL AND status='published' AND visibility='public' AND (${canManage(request)} OR author_user_id=${actor(request)})`);return Boolean(result.rows[0]);}
  if(resourceType==='marketplace_listing'){const result=await db.execute(sql`SELECT id FROM torqueshed_marketplace_listings WHERE tenant_id=${tenant(request)} AND id=${resourceId} AND archived_at IS NULL AND status='published' AND (${canManage(request)} OR seller_user_id=${actor(request)})`);return Boolean(result.rows[0]);}
  return false;
}
async function bayAccess(request:FastifyRequest,bayId:string,post=false){const result=await db.execute(sql`SELECT b.*,m.role AS member_role,m.left_at FROM torqueshed_live_bays b LEFT JOIN torqueshed_live_bay_members m ON m.tenant_id=b.tenant_id AND m.bay_id=b.id AND m.user_id=${actor(request)} WHERE b.tenant_id=${tenant(request)} AND b.id=${bayId} AND (${canManage(request)} OR m.left_at IS NULL AND m.user_id IS NOT NULL OR (${!post} AND b.visibility='tenant')) LIMIT 1`);return result.rows[0] as Record<string,any>|undefined;}
async function consumeBayRate(request:FastifyRequest){const start=new Date(Math.floor(Date.now()/60000)*60000);const result=await db.execute(sql`INSERT INTO torqueshed_live_bay_rate_windows(tenant_id,user_id,window_started_at,message_count) VALUES(${tenant(request)},${actor(request)},${start},1) ON CONFLICT(tenant_id,user_id,window_started_at) DO UPDATE SET message_count=torqueshed_live_bay_rate_windows.message_count+1 RETURNING message_count`);if(Number(result.rows[0]?.message_count)>30)throw new InputError('Live bay message rate limit exceeded','TORQUESHED_RATE_LIMITED',429);}

export async function registerTorqueShedWebApiRoutes(app:FastifyInstance):Promise<void>{
  app.get('/v1/modules/torqueshed/builds/:id/workspace',{preHandler:readGuards},async(request,reply)=>{try{const buildId=id(request);const build=await ownedBuild(request,buildId);if(!build)return reply.code(404).send({error:'Build not found',code:'TORQUESHED_NOT_FOUND'});const [stages,tasks,journal,parts]=await Promise.all([db.execute(sql`SELECT * FROM torqueshed_build_stages WHERE tenant_id=${tenant(request)} AND build_id=${buildId} AND archived_at IS NULL ORDER BY position,id`),db.execute(sql`SELECT * FROM torqueshed_build_tasks WHERE tenant_id=${tenant(request)} AND build_id=${buildId} AND archived_at IS NULL ORDER BY position,id`),db.execute(sql`SELECT * FROM torqueshed_build_journal_entries WHERE tenant_id=${tenant(request)} AND build_id=${buildId} AND archived_at IS NULL ORDER BY occurred_at DESC,id DESC`),db.execute(sql`SELECT * FROM torqueshed_build_parts WHERE tenant_id=${tenant(request)} AND build_id=${buildId} AND archived_at IS NULL ORDER BY created_at DESC,id DESC`)]);return {build:camel(build),stages:list(stages.rows),tasks:list(tasks.rows),journal:list(journal.rows),parts:list(parts.rows)};}catch(error){return sendError(reply,error);}});
  app.post('/v1/modules/torqueshed/builds/:id/journal',{preHandler:writeGuards},async(request,reply)=>{try{const buildId=id(request);if(!await ownedBuild(request,buildId,true))return reply.code(404).send({error:'Build not found',code:'TORQUESHED_NOT_FOUND'});const b=body(request);const stageId=textValue(b.stageId,'stageId',36);const entryType=enumValue(b.entryType,'entryType',['entry','milestone','stage_update','part_update','cost_update'] as const,'entry');const result=await db.execute(sql`INSERT INTO torqueshed_build_journal_entries(tenant_id,build_id,author_user_id,stage_id,entry_type,title,body,mileage,cost_minor,labor_minutes,visibility,occurred_at) VALUES(${tenant(request)},${buildId},${actor(request)},${stageId},${entryType},${textValue(b.title,'title',180,true)},${textValue(b.body,'body',20000)},${intValue(b.mileage,'mileage',0,10000000)},${intValue(b.costMinor,'costMinor')},${intValue(b.laborMinutes,'laborMinutes')},${enumValue(b.visibility,'visibility',['private','tenant','public'] as const,'private')},${b.occurredAt?new Date(String(b.occurredAt)):new Date()}) RETURNING *`);const row=camel(result.rows[0]);await activity(request,'torqueshed_build',buildId,`journal_${entryType}`,String(row.title),{journalEntryId:row.id});await audit(request,'torqueshed_build_journal_entry',String(row.id),'created',row);return reply.code(201).send({entry:row});}catch(error){return sendError(reply,error);}});
  app.post('/v1/modules/torqueshed/builds/:id/parts',{preHandler:writeGuards},async(request,reply)=>{try{const buildId=id(request);if(!await ownedBuild(request,buildId,true))return reply.code(404).send({error:'Build not found',code:'TORQUESHED_NOT_FOUND'});const b=body(request);const result=await db.execute(sql`INSERT INTO torqueshed_build_parts(tenant_id,build_id,stage_id,name,manufacturer,part_number,category,status,quantity,unit_cost_minor,currency,installed_at,notes,created_by_user_id,updated_by_user_id) VALUES(${tenant(request)},${buildId},${textValue(b.stageId,'stageId',36)},${textValue(b.name,'name',180,true)},${textValue(b.manufacturer,'manufacturer',120)},${textValue(b.partNumber,'partNumber',120)},${textValue(b.category,'category',80)},${enumValue(b.status,'status',['planned','ordered','installed','removed'] as const,'planned')},${intValue(b.quantity,'quantity',1,100000)??1},${intValue(b.unitCostMinor,'unitCostMinor')},${(textValue(b.currency,'currency',3)||'USD').toUpperCase()},${b.installedAt?new Date(String(b.installedAt)):null},${textValue(b.notes,'notes',10000)},${actor(request)},${actor(request)}) RETURNING *`);const row=camel(result.rows[0]);await activity(request,'torqueshed_build',buildId,'part_added',String(row.name),{partId:row.id});return reply.code(201).send({part:row});}catch(error){return sendError(reply,error);}});
  app.patch('/v1/modules/torqueshed/build-parts/:id',{preHandler:writeGuards},async(request,reply)=>{try{const partId=id(request),b=body(request),expected=intValue(b.expectedVersion,'expectedVersion',1);if(!expected)throw new InputError('expectedVersion is required');const result=await db.execute(sql`UPDATE torqueshed_build_parts p SET status=${enumValue(b.status,'status',['planned','ordered','installed','removed'] as const,'planned')},installed_at=CASE WHEN ${b.installedAt!==undefined} THEN ${b.installedAt?new Date(String(b.installedAt)):null} ELSE installed_at END,notes=CASE WHEN ${b.notes!==undefined} THEN ${textValue(b.notes,'notes',10000)} ELSE notes END,version=version+1,updated_at=NOW(),updated_by_user_id=${actor(request)} FROM torqueshed_builds bld WHERE p.tenant_id=${tenant(request)} AND p.id=${partId} AND p.version=${expected} AND p.archived_at IS NULL AND bld.tenant_id=p.tenant_id AND bld.id=p.build_id AND (${canManage(request)} OR bld.owner_user_id=${actor(request)}) RETURNING p.*`);if(!result.rows[0])return reply.code(409).send({error:'Part changed or not found',code:'TORQUESHED_VERSION_CONFLICT'});return {part:camel(result.rows[0])};}catch(error){return sendError(reply,error);}});

  app.post('/v1/modules/torqueshed/live-bays',{preHandler:writeGuards},async(request,reply)=>{try{const b=body(request);const vehicleId=textValue(b.vehicleId,'vehicleId',36),buildId=textValue(b.buildId,'buildId',36),diagnosticId=textValue(b.diagnosticId,'diagnosticId',36);if(!vehicleId&&!buildId&&!diagnosticId)throw new InputError('A vehicle, build, or diagnostic context is required');const result=await db.transaction(async tx=>{const inserted=await tx.execute(sql`INSERT INTO torqueshed_live_bays(tenant_id,owner_user_id,vehicle_id,build_id,diagnostic_session_id,title,visibility) VALUES(${tenant(request)},${actor(request)},${vehicleId},${buildId},${diagnosticId},${textValue(b.title,'title',180,true)},${enumValue(b.visibility,'visibility',['private','tenant'] as const,'private')}) RETURNING *`);const bay=inserted.rows[0] as Record<string,unknown>;await tx.execute(sql`INSERT INTO torqueshed_live_bay_members(tenant_id,bay_id,user_id,role) VALUES(${tenant(request)},${String(bay.id)},${actor(request)},'owner')`);return bay;});const row=camel(result);await activity(request,'torqueshed_live_bay',String(row.id),'opened',String(row.title));return reply.code(201).send({bay:row});}catch(error){return sendError(reply,error);}});
  app.get('/v1/modules/torqueshed/live-bays',{preHandler:readGuards},async(request)=>{const result=await db.execute(sql`SELECT b.*,m.role AS member_role FROM torqueshed_live_bays b LEFT JOIN torqueshed_live_bay_members m ON m.tenant_id=b.tenant_id AND m.bay_id=b.id AND m.user_id=${actor(request)} AND m.left_at IS NULL WHERE b.tenant_id=${tenant(request)} AND (${canManage(request)} OR m.user_id IS NOT NULL OR b.visibility='tenant') ORDER BY b.updated_at DESC LIMIT 100`);return {bays:list(result.rows)};});
  app.get('/v1/modules/torqueshed/live-bays/:id',{preHandler:readGuards},async(request,reply)=>{try{const bayId=id(request);const bay=await bayAccess(request,bayId);if(!bay)return reply.code(404).send({error:'Live bay not found',code:'TORQUESHED_NOT_FOUND'});const after=intValue((request.query as Record<string,unknown>).after,'after',0)??0;const messages=await db.execute(sql`SELECT m.*,p.display_name AS sender_display_name FROM torqueshed_live_bay_messages m LEFT JOIN torqueshed_social_profiles p ON p.tenant_id=m.tenant_id AND p.user_id=m.sender_user_id AND p.archived_at IS NULL WHERE m.tenant_id=${tenant(request)} AND m.bay_id=${bayId} AND m.sequence>${after} AND m.archived_at IS NULL ORDER BY m.sequence LIMIT 250`);await db.execute(sql`UPDATE torqueshed_live_bay_members SET last_seen_sequence=${Number(bay.last_sequence)} WHERE tenant_id=${tenant(request)} AND bay_id=${bayId} AND user_id=${actor(request)}`);return {bay:camel(bay),messages:list(messages.rows),cursor:Number(bay.last_sequence)};}catch(error){return sendError(reply,error);}});
  app.post('/v1/modules/torqueshed/live-bays/:id/members',{preHandler:writeGuards},async(request,reply)=>{try{const bayId=id(request);const bay=await bayAccess(request,bayId,true);if(!bay||(String(bay.owner_user_id)!==actor(request)&&!canManage(request)))return reply.code(404).send({error:'Live bay not found',code:'TORQUESHED_NOT_FOUND'});const b=body(request),userId=textValue(b.userId,'userId',36,true)!;await requireTenantPeer(tenant(request),userId);const result=await db.execute(sql`INSERT INTO torqueshed_live_bay_members(tenant_id,bay_id,user_id,role,left_at) VALUES(${tenant(request)},${bayId},${userId},${enumValue(b.role,'role',['collaborator','viewer'] as const,'collaborator')},NULL) ON CONFLICT(tenant_id,bay_id,user_id) DO UPDATE SET role=EXCLUDED.role,left_at=NULL RETURNING *`);return reply.code(201).send({member:camel(result.rows[0])});}catch(error){return sendError(reply,error);}});
  app.post('/v1/modules/torqueshed/live-bays/:id/messages',{preHandler:writeGuards},async(request,reply)=>{try{const bayId=id(request);const bay=await bayAccess(request,bayId,true);if(!bay)return reply.code(404).send({error:'Live bay not found',code:'TORQUESHED_NOT_FOUND'});if(bay.status!=='active')return reply.code(409).send({error:'Live bay is closed',code:'TORQUESHED_BAY_CLOSED'});if(bay.member_role==='viewer')return reply.code(403).send({error:'Viewer cannot post',code:'TORQUESHED_BAY_READ_ONLY'});await consumeBayRate(request);const b=body(request),clientId=textValue(b.clientMessageId,'clientMessageId',120,true)!;const outcome=await db.transaction(async tx=>{const existing=await tx.execute(sql`SELECT * FROM torqueshed_live_bay_messages WHERE tenant_id=${tenant(request)} AND bay_id=${bayId} AND sender_user_id=${actor(request)} AND client_message_id=${clientId}`);if(existing.rows[0])return {row:existing.rows[0],duplicate:true};const claimed=await tx.execute(sql`UPDATE torqueshed_live_bays SET last_sequence=last_sequence+1,updated_at=NOW(),version=version+1 WHERE tenant_id=${tenant(request)} AND id=${bayId} AND status='active' RETURNING last_sequence`);if(!claimed.rows[0])throw new InputError('Live bay is closed','TORQUESHED_BAY_CLOSED',409);const inserted=await tx.execute(sql`INSERT INTO torqueshed_live_bay_messages(tenant_id,bay_id,sequence,sender_user_id,client_message_id,kind,body,metadata) VALUES(${tenant(request)},${bayId},${Number(claimed.rows[0].last_sequence)},${actor(request)},${clientId},${enumValue(b.kind,'kind',['message','evidence'] as const,'message')},${textValue(b.body,'body',5000,true)},${JSON.stringify(typeof b.metadata==='object'&&b.metadata&&!Array.isArray(b.metadata)?b.metadata:{})}::jsonb) RETURNING *`);return {row:inserted.rows[0],duplicate:false};});if(!outcome.duplicate)await activity(request,'torqueshed_live_bay',bayId,'message_posted','Live bay message posted',{sequence:(outcome.row as any).sequence});return reply.code(outcome.duplicate?200:201).send({message:camel(outcome.row),duplicate:outcome.duplicate});}catch(error){return sendError(reply,error);}});
  app.post('/v1/modules/torqueshed/live-bays/:id/close',{preHandler:writeGuards},async(request,reply)=>{try{const bayId=id(request);const result=await db.execute(sql`UPDATE torqueshed_live_bays SET status='closed',closed_at=NOW(),updated_at=NOW(),version=version+1 WHERE tenant_id=${tenant(request)} AND id=${bayId} AND status='active' AND (${canManage(request)} OR owner_user_id=${actor(request)}) RETURNING *`);if(!result.rows[0])return reply.code(404).send({error:'Live bay not found',code:'TORQUESHED_NOT_FOUND'});await activity(request,'torqueshed_live_bay',bayId,'closed','Live bay closed');return {bay:camel(result.rows[0])};}catch(error){return sendError(reply,error);}});

  app.get('/v1/modules/torqueshed/diagnostics/:id/report',{preHandler:readGuards},async(request,reply)=>{try{const diagnosticId=id(request);const diagnostic=await visibleDiagnostic(request,diagnosticId);if(!diagnostic)return reply.code(404).send({error:'Diagnostic not found',code:'TORQUESHED_NOT_FOUND'});const [codes,entries,attachments,assist]=await Promise.all([db.execute(sql`SELECT code,description,code_status,freeze_frame,observed_at FROM torqueshed_diagnostic_trouble_codes WHERE tenant_id=${tenant(request)} AND diagnostic_session_id=${diagnosticId} AND archived_at IS NULL ORDER BY observed_at,id`),db.execute(sql`SELECT kind,title,value_text,value_numeric,unit,reference_min,reference_max,outcome,metadata,observed_at FROM torqueshed_diagnostic_entries WHERE tenant_id=${tenant(request)} AND diagnostic_session_id=${diagnosticId} AND archived_at IS NULL ORDER BY observed_at,id`),db.execute(sql`SELECT id,original_name,declared_mime_type,scan_status,sha256,created_at FROM shared_attachments WHERE tenant_id=${tenant(request)} AND module_id=${await torqueShedSocialModuleId()} AND object_type='torqueshed_diagnostic' AND object_id=${diagnosticId} AND deleted_at IS NULL ORDER BY created_at,id`),db.execute(sql`SELECT id,status,provider,provider_model,response_json,created_at FROM torqueshed_assist_requests WHERE tenant_id=${tenant(request)} AND diagnostic_session_id=${diagnosticId} ORDER BY created_at DESC LIMIT 20`)]);return {report:{generatedAt:new Date().toISOString(),diagnostic:camel(diagnostic),troubleCodes:list(codes.rows),observations:list(entries.rows),evidence:list(attachments.rows),torqueAssist:list(assist.rows),privacy:{vinMasked:diagnostic.vin_last6?`***${diagnostic.vin_last6}`:null,tenantScoped:true}}};}catch(error){return sendError(reply,error);}});
  app.get('/v1/modules/torqueshed/marketplace/sellers/:userId',{preHandler:readGuards},async(request,reply)=>{try{const sellerId=id(request,'userId');await requireTenantPeer(tenant(request),sellerId);const [profile,listings,counts]=await Promise.all([db.execute(sql`SELECT display_name,bio,locality,region,avatar_attachment_id,created_at FROM torqueshed_social_profiles WHERE tenant_id=${tenant(request)} AND user_id=${sellerId} AND archived_at IS NULL LIMIT 1`),db.execute(sql`SELECT id,title,price_minor,currency,status,created_at FROM torqueshed_marketplace_listings WHERE tenant_id=${tenant(request)} AND seller_user_id=${sellerId} AND status='published' AND archived_at IS NULL ORDER BY created_at DESC LIMIT 50`),db.execute(sql`SELECT (SELECT COUNT(*) FROM torqueshed_community_posts WHERE tenant_id=${tenant(request)} AND author_user_id=${sellerId} AND status='published' AND archived_at IS NULL)::int AS posts,(SELECT COUNT(*) FROM torqueshed_community_comments WHERE tenant_id=${tenant(request)} AND author_user_id=${sellerId} AND status='published' AND archived_at IS NULL)::int AS comments,(SELECT COUNT(*) FROM torqueshed_community_post_reactions r JOIN torqueshed_community_posts p ON p.tenant_id=r.tenant_id AND p.id=r.post_id WHERE p.tenant_id=${tenant(request)} AND p.author_user_id=${sellerId} AND p.status='published')::int AS reactions_received,(SELECT COUNT(*) FROM torqueshed_community_follows WHERE tenant_id=${tenant(request)} AND followed_user_id=${sellerId})::int AS followers,(SELECT COUNT(*) FROM torqueshed_social_moderation_actions WHERE tenant_id=${tenant(request)} AND target_user_id=${sellerId} AND action IN ('suspend','ban'))::int AS enforcement_actions`)]);const c=counts.rows[0] as any;const score=Math.max(0,Number(c.posts)*5+Number(c.comments)*2+Number(c.reactions_received)+Number(c.followers)*3-Number(c.enforcement_actions)*25);return {seller:{userId:sellerId,profile:profile.rows[0]?camel(profile.rows[0]):null,contributionReputation:{score,basis:{posts:Number(c.posts),comments:Number(c.comments),reactionsReceived:Number(c.reactions_received),followers:Number(c.followers),enforcementActions:Number(c.enforcement_actions)},disclaimer:'Community contribution signal only; not a transaction rating or payment guarantee.'},listings:list(listings.rows)}};}catch(error){return sendError(reply,error);}});
  app.get('/v1/modules/torqueshed/search',{preHandler:readGuards},async(request)=>{const q=textValue((request.query as Record<string,unknown>).q,'q',120,true)!;const like=`%${q}%`;const [vehicles,builds,diagnostics,listings,posts]=await Promise.all([db.execute(sql`SELECT id,nickname,year,make,model,'vehicle' AS result_type FROM torqueshed_vehicles WHERE tenant_id=${tenant(request)} AND archived_at IS NULL AND (${canManage(request)} OR owner_user_id=${actor(request)} OR visibility IN ('tenant','public_build')) AND (nickname ILIKE ${like} OR make ILIKE ${like} OR model ILIKE ${like}) LIMIT 20`),db.execute(sql`SELECT id,title,status,'build' AS result_type FROM torqueshed_builds WHERE tenant_id=${tenant(request)} AND archived_at IS NULL AND (${canManage(request)} OR owner_user_id=${actor(request)} OR visibility IN ('tenant','public_build')) AND (title ILIKE ${like} OR description ILIKE ${like}) LIMIT 20`),db.execute(sql`SELECT id,title,status,'diagnostic' AS result_type FROM torqueshed_diagnostic_sessions WHERE tenant_id=${tenant(request)} AND archived_at IS NULL AND (${canManage(request)} OR owner_user_id=${actor(request)} OR visibility='tenant') AND (title ILIKE ${like} OR customer_concern ILIKE ${like}) LIMIT 20`),db.execute(sql`SELECT id,title,status,'marketplace_listing' AS result_type FROM torqueshed_marketplace_listings WHERE tenant_id=${tenant(request)} AND archived_at IS NULL AND status='published' AND (title ILIKE ${like} OR description ILIKE ${like}) LIMIT 20`),db.execute(sql`SELECT id,title,status,'community_post' AS result_type FROM torqueshed_community_posts WHERE tenant_id=${tenant(request)} AND archived_at IS NULL AND status='published' AND visibility='public' AND (title ILIKE ${like} OR body ILIKE ${like}) LIMIT 20`)]);return {query:q,results:list([...vehicles.rows,...builds.rows,...diagnostics.rows,...listings.rows,...posts.rows])};});
  app.get('/v1/modules/torqueshed/activity',{preHandler:readGuards},async(request)=>{const result=await listActivityEvents({tenantId:tenant(request),moduleId:await torqueShedSocialModuleId(),cursor:textValue((request.query as Record<string,unknown>).cursor,'cursor',200),limit:intValue((request.query as Record<string,unknown>).limit,'limit',1,100)??25});return {events:list(result.events),nextCursor:result.nextCursor};});
  app.get('/v1/modules/torqueshed/notifications',{preHandler:readGuards},async(request)=>{const result=await db.execute(sql`SELECT id,title,message,level,created_at,read_at FROM shared_notifications WHERE tenant_id=${tenant(request)} AND module_id=${await torqueShedSocialModuleId()} AND user_id=${actor(request)} ORDER BY created_at DESC LIMIT 100`);return {notifications:list(result.rows)};});
  app.get('/v1/modules/torqueshed/settings',{preHandler:readGuards},async(request)=>{const result=await db.execute(sql`INSERT INTO torqueshed_user_settings(tenant_id,user_id) VALUES(${tenant(request)},${actor(request)}) ON CONFLICT(tenant_id,user_id) DO NOTHING RETURNING *`);if(result.rows[0])return {settings:camel(result.rows[0])};const existing=await db.execute(sql`SELECT * FROM torqueshed_user_settings WHERE tenant_id=${tenant(request)} AND user_id=${actor(request)}`);return {settings:camel(existing.rows[0])};});
  app.put('/v1/modules/torqueshed/settings',{preHandler:writeGuards},async(request,reply)=>{try{const b=body(request);const result=await db.execute(sql`INSERT INTO torqueshed_user_settings(tenant_id,user_id,units,reduced_motion,default_garage_visibility,profile_discoverable,community_notifications,marketplace_notifications,garage_notifications) VALUES(${tenant(request)},${actor(request)},${enumValue(b.units,'units',['imperial','metric'] as const,'imperial')},${Boolean(b.reducedMotion)},${enumValue(b.defaultGarageVisibility,'defaultGarageVisibility',['private','tenant','public_build'] as const,'private')},${b.profileDiscoverable!==false},${b.communityNotifications!==false},${b.marketplaceNotifications!==false},${b.garageNotifications!==false}) ON CONFLICT(tenant_id,user_id) DO UPDATE SET units=EXCLUDED.units,reduced_motion=EXCLUDED.reduced_motion,default_garage_visibility=EXCLUDED.default_garage_visibility,profile_discoverable=EXCLUDED.profile_discoverable,community_notifications=EXCLUDED.community_notifications,marketplace_notifications=EXCLUDED.marketplace_notifications,garage_notifications=EXCLUDED.garage_notifications,version=torqueshed_user_settings.version+1,updated_at=NOW() RETURNING *`);await audit(request,'torqueshed_user_settings',String((result.rows[0] as any).id),'updated');return {settings:camel(result.rows[0])};}catch(error){return sendError(reply,error);}});
  app.post('/v1/modules/torqueshed/exports',{preHandler:writeGuards},async(request,reply)=>{try{const b=body(request),key=textValue(request.headers['idempotency-key'],'Idempotency-Key',200,true)!;const result=await requestSharedExport({tenantId:tenant(request),moduleId:await torqueShedSocialModuleId(),requestedByUserId:actor(request),exportType:TORQUESHED_PRODUCT_EXPORT_TYPE,format:enumValue(b.format,'format',['json','csv'] as const,'json'),filters:typeof b.filters==='object'&&b.filters&&!Array.isArray(b.filters)?b.filters as Record<string,unknown>:{},idempotencyKey:key,correlationId:request.id});return reply.code(result.duplicate?200:202).send(result);}catch(error){return sendError(reply,error);}});
  app.get('/v1/modules/torqueshed/exports',{preHandler:readGuards},async(request)=>{const result=await db.execute(sql`SELECT id,format,status,result_attachment_id,last_error_code,created_at,completed_at,expires_at FROM shared_exports WHERE tenant_id=${tenant(request)} AND module_id=${await torqueShedSocialModuleId()} AND requested_by_user_id=${actor(request)} AND export_type=${TORQUESHED_PRODUCT_EXPORT_TYPE} ORDER BY created_at DESC LIMIT 100`);return {exports:list(result.rows)};});
  app.post('/v1/modules/torqueshed/share-links',{preHandler:writeGuards},async(request,reply)=>{try{const b=body(request),resourceType=enumValue(b.resourceType,'resourceType',['build','diagnostic_report','vehicle_history','community_post','marketplace_listing'] as const,'build'),resourceId=textValue(b.resourceId,'resourceId',36,true)!;if(!await mayCreateShare(request,resourceType,resourceId))return reply.code(404).send({error:'Shareable record not found',code:'TORQUESHED_NOT_FOUND'});const token=randomBytes(32).toString('base64url'),hash=createHash('sha256').update(token).digest('hex');const expiresAt=b.expiresAt?new Date(String(b.expiresAt)):new Date(Date.now()+7*86400000);const result=await db.execute(sql`INSERT INTO torqueshed_share_links(tenant_id,token_hash,resource_type,resource_id,created_by_user_id,allow_download,expires_at) VALUES(${tenant(request)},${hash},${resourceType},${resourceId},${actor(request)},${Boolean(b.allowDownload)},${expiresAt}) RETURNING id,resource_type,resource_id,allow_download,expires_at,created_at`);await audit(request,'torqueshed_share_link',String((result.rows[0] as any).id),'created');return reply.code(201).send({shareLink:{...camel(result.rows[0]),token,url:`/v1/public/torqueshed/share/${token}`}});}catch(error){return sendError(reply,error);}});
  app.delete('/v1/modules/torqueshed/share-links/:id',{preHandler:writeGuards},async(request,reply)=>{try{const linkId=id(request);const result=await db.execute(sql`UPDATE torqueshed_share_links SET revoked_at=NOW() WHERE tenant_id=${tenant(request)} AND id=${linkId} AND revoked_at IS NULL AND (${canManage(request)} OR created_by_user_id=${actor(request)}) RETURNING id,revoked_at`);if(!result.rows[0])return reply.code(404).send({error:'Share link not found',code:'TORQUESHED_NOT_FOUND'});await audit(request,'torqueshed_share_link',linkId,'revoked');return {shareLink:camel(result.rows[0])};}catch(error){return sendError(reply,error);}});

  app.get('/v1/public/torqueshed/share/:token',async(request,reply)=>{const raw=String((request.params as any).token||'');if(raw.length<40)return reply.code(404).send({error:'Share link not found',code:'TORQUESHED_SHARE_NOT_FOUND'});const hash=createHash('sha256').update(raw).digest('hex');const found=await db.execute(sql`UPDATE torqueshed_share_links SET access_count=access_count+1,last_accessed_at=NOW() WHERE token_hash=${hash} AND revoked_at IS NULL AND (expires_at IS NULL OR expires_at>NOW()) RETURNING *`);const link=found.rows[0] as any;if(!link)return reply.code(404).send({error:'Share link not found',code:'TORQUESHED_SHARE_NOT_FOUND'});if(link.resource_type==='build'){const [build,journal,parts]=await Promise.all([db.execute(sql`SELECT id,title,description,status,visibility,started_at,target_at,completed_at,updated_at FROM torqueshed_builds WHERE tenant_id=${link.tenant_id} AND id=${link.resource_id} AND archived_at IS NULL AND visibility='public_build'`),db.execute(sql`SELECT entry_type,title,body,mileage,occurred_at FROM torqueshed_build_journal_entries WHERE tenant_id=${link.tenant_id} AND build_id=${link.resource_id} AND visibility='public' AND archived_at IS NULL ORDER BY occurred_at`),db.execute(sql`SELECT name,manufacturer,part_number,category,status,quantity,installed_at FROM torqueshed_build_parts WHERE tenant_id=${link.tenant_id} AND build_id=${link.resource_id} AND archived_at IS NULL ORDER BY created_at`)]);if(!build.rows[0])return reply.code(404).send({error:'Shared build unavailable',code:'TORQUESHED_SHARE_UNAVAILABLE'});return {resourceType:'build',build:camel(build.rows[0]),journal:list(journal.rows),parts:list(parts.rows),allowDownload:Boolean(link.allow_download)};}
    if(link.resource_type==='diagnostic_report'){const diagnostic=await db.execute(sql`SELECT id,title,customer_concern,symptoms,confirmed_cause,repair_performed,verification,resolution,status,opened_at,resolved_at FROM torqueshed_diagnostic_sessions WHERE tenant_id=${link.tenant_id} AND id=${link.resource_id} AND archived_at IS NULL`);if(!diagnostic.rows[0])return reply.code(404).send({error:'Shared report unavailable',code:'TORQUESHED_SHARE_UNAVAILABLE'});const [codes,entries]=await Promise.all([db.execute(sql`SELECT code,description,code_status,observed_at FROM torqueshed_diagnostic_trouble_codes WHERE tenant_id=${link.tenant_id} AND diagnostic_session_id=${link.resource_id} AND archived_at IS NULL ORDER BY observed_at`),db.execute(sql`SELECT kind,title,value_text,value_numeric,unit,outcome,observed_at FROM torqueshed_diagnostic_entries WHERE tenant_id=${link.tenant_id} AND diagnostic_session_id=${link.resource_id} AND archived_at IS NULL ORDER BY observed_at`)]);return {resourceType:'diagnostic_report',report:{diagnostic:camel(diagnostic.rows[0]),troubleCodes:list(codes.rows),observations:list(entries.rows)},allowDownload:Boolean(link.allow_download)};}
    if(link.resource_type==='vehicle_history'){const vehicle=await db.execute(sql`SELECT id,nickname,year,make,model,trim,engine,transmission,drivetrain,current_mileage,ownership_status,updated_at FROM torqueshed_vehicles WHERE tenant_id=${link.tenant_id} AND id=${link.resource_id} AND archived_at IS NULL AND visibility='public_build'`);if(!vehicle.rows[0])return reply.code(404).send({error:'Shared vehicle unavailable',code:'TORQUESHED_SHARE_UNAVAILABLE'});const history=await db.execute(sql`SELECT kind,title,description,mileage,occurred_at,status FROM torqueshed_service_records WHERE tenant_id=${link.tenant_id} AND vehicle_id=${link.resource_id} AND archived_at IS NULL ORDER BY occurred_at DESC LIMIT 250`);return {resourceType:'vehicle_history',vehicle:camel(vehicle.rows[0]),history:list(history.rows),allowDownload:Boolean(link.allow_download)};}
    if(link.resource_type==='community_post'){const post=await db.execute(sql`SELECT p.id,p.title,p.body,p.created_at,p.updated_at,t.name AS topic_name,sp.display_name AS author_display_name FROM torqueshed_community_posts p LEFT JOIN torqueshed_community_topics t ON t.tenant_id=p.tenant_id AND t.id=p.topic_id LEFT JOIN torqueshed_social_profiles sp ON sp.tenant_id=p.tenant_id AND sp.user_id=p.author_user_id AND sp.archived_at IS NULL WHERE p.tenant_id=${link.tenant_id} AND p.id=${link.resource_id} AND p.status='published' AND p.visibility='public' AND p.archived_at IS NULL`);if(!post.rows[0])return reply.code(404).send({error:'Shared post unavailable',code:'TORQUESHED_SHARE_UNAVAILABLE'});const comments=await db.execute(sql`SELECT c.id,c.body,c.created_at,sp.display_name AS author_display_name FROM torqueshed_community_comments c LEFT JOIN torqueshed_social_profiles sp ON sp.tenant_id=c.tenant_id AND sp.user_id=c.author_user_id AND sp.archived_at IS NULL WHERE c.tenant_id=${link.tenant_id} AND c.post_id=${link.resource_id} AND c.status='published' AND c.archived_at IS NULL ORDER BY c.created_at LIMIT 250`);return {resourceType:'community_post',post:camel(post.rows[0]),comments:list(comments.rows)};}
    if(link.resource_type==='marketplace_listing'){const listing=await db.execute(sql`SELECT l.id,l.listing_type,l.condition,l.title,l.description,l.price_minor,l.currency,l.negotiable,l.locality,l.region,l.created_at,l.expires_at,c.name AS category_name,p.display_name AS seller_display_name FROM torqueshed_marketplace_listings l JOIN torqueshed_marketplace_categories c ON c.tenant_id=l.tenant_id AND c.id=l.category_id LEFT JOIN torqueshed_social_profiles p ON p.tenant_id=l.tenant_id AND p.user_id=l.seller_user_id AND p.archived_at IS NULL WHERE l.tenant_id=${link.tenant_id} AND l.id=${link.resource_id} AND l.status='published' AND l.archived_at IS NULL`);if(!listing.rows[0])return reply.code(404).send({error:'Shared listing unavailable',code:'TORQUESHED_SHARE_UNAVAILABLE'});return {resourceType:'marketplace_listing',listing:camel(listing.rows[0]),transactionBoundary:'TorqueShed does not process payment, escrow, shipping, title, or transaction guarantees.'};}
    return reply.code(404).send({error:'Shared resource unavailable',code:'TORQUESHED_SHARE_UNAVAILABLE'});
  });
}
