export const DATABASE_RELEASE_CONTRACT = Object.freeze({
  contractVersion: 1,
  releaseVersion: 38,
  mode: 'idempotent-apply',
  destructive: false,
  rollback: 'restore-to-new-database-and-switch-traffic',
});

export const DATABASE_RELEASE_STEPS = Object.freeze([
  { id: 'base_tables', kind: 'ddl' },
  { id: 'extended_tables', kind: 'ddl' },
  { id: 'saas_tables', kind: 'ddl' },
  { id: 'tenant_tables', kind: 'ddl' },
  { id: 'directory_tables', kind: 'ddl' },
  { id: 'module_tables', kind: 'ddl' },
  { id: 'tradeflowkit_tables', kind: 'ddl' },
  { id: 'techdeck_tables', kind: 'ddl' },
  { id: 'pulsedesk_tables', kind: 'ddl' },
  { id: 'torqueshed_tables', kind: 'ddl' },
  { id: 'faultlinelab_tables', kind: 'ddl' },
  { id: 'ninja_pool_hall_tables', kind: 'ddl' },
  { id: 'brandforgeos_tables', kind: 'ddl' },
  { id: 'shared_service_tables', kind: 'ddl' },
  { id: 'shared_platform_tables', kind: 'ddl' },
  { id: 'snapproofos_tables', kind: 'ddl' },
  { id: 'studyforge_tables', kind: 'ddl' },
  { id: 'ninja_launch_kit_tables', kind: 'ddl' },
  { id: 'callcommand_tables', kind: 'ddl' },
  { id: 'ninjamation_tables', kind: 'ddl' },
  { id: 'outcall_tables', kind: 'ddl' },
  { id: 'plans_and_admin', kind: 'seed' },
  { id: 'launch_fix_pre_seed', kind: 'repair' },
  { id: 'platform_components', kind: 'seed' },
  { id: 'module_catalog', kind: 'seed' },
  { id: 'personal_tenant_backfill', kind: 'backfill' },
  { id: 'super_admin_bootstrap', kind: 'backfill' },
  { id: 'demo_tenant_seed', kind: 'seed' },
  { id: 'launch_fix_post_seed', kind: 'repair' },
  { id: 'free_account_app_backfill', kind: 'backfill' },
  { id: 'tradeflowkit_saved_views', kind: 'ddl' },
  { id: 'tradeflowkit_lead_operations', kind: 'ddl' },
  { id: 'tradeflowkit_public_operations', kind: 'ddl' },
  { id: 'outcall_product_operations', kind: 'ddl' },
  { id: 'techdeck_literal_tables', kind: 'ddl' },
  { id: 'pulsedesk_literal_tables', kind: 'ddl' },
  { id: 'operatoros_messaging_compliance_tables', kind: 'ddl' },
  { id: 'torqueshed_web_api_tables', kind: 'ddl' },
] as const);
