import { guidePage } from './page';
import type { HelpGuide } from './types';

const fault = 'https://faultlinelab.operatoros.net';
const pool = 'https://operatorpoolhall.operatoros.net';
const brand = 'https://brandforgeos.operatoros.net';
const snap = 'https://snapproofos.operatoros.net';
const study = 'https://studyforge-ai.operatoros.net';
const deploy = 'https://deployops.operatoros.net';
const call = 'https://callcommand-ai.operatoros.net';
const script = 'https://scriptops.operatoros.net';
const outcall = 'https://outcall.operatoros.net';

export const FAULTLINELAB_GUIDE: HelpGuide = {
  id: 'faultlinelab', name: 'FaultlineLab', kind: 'companion-application', accent: '#a78bfa',
  description: 'Hands-on diagnostic challenges, team assignments, scored investigations, challenge authoring, and learning reports.',
  availability: 'Available now', startHref: `${fault}/`,
  pages: [
    guidePage(fault, 'fault-overview', 'Learning operations overview', '/', 'See assigned investigations, recent attempts, skill coverage, and the areas that need more practice.', ['Review current assignments, recent attempts, completion, streaks, and badges.', 'Open a published challenge or resume an investigation.', 'Go to investigation history, authoring, or reports when your role allows it.']),
    guidePage(fault, 'fault-challenges', 'Challenge library', '/challenges', 'Find a reviewed diagnostic case and start working through the clues.', ['Search by discipline, category, difficulty, or status.', 'Open the challenge and review its scenario, safety notes, and available actions.', 'Start a standard, daily, or approved Chaos-mode attempt.', 'The attempt keeps the exact challenge revision used for fair scoring.']),
    guidePage(fault, 'fault-investigation', 'Investigation', '/sessions', 'Run the available checks, unlock clues, identify the cause, and test your reasoning.', ['Open or resume an investigation.', 'Choose from the diagnostic actions provided by the challenge.', 'Unlock and inspect clues in order.', 'Submit the root cause and the fix you recommend.', 'Review your score, feedback, and completed attempt.']),
    guidePage(fault, 'fault-assignments', 'Assignments', '/assignments', 'Assign published challenges and follow each learner’s progress.', ['Choose an available team member and published challenge.', 'Set a due date or learning goal.', 'Review assigned, started, completed, and overdue work.', 'Open the related attempt when your role allows it.'], { access: 'Challenge assignment requires an approved team role.' }),
    guidePage(fault, 'fault-runs', 'Runs and progress', '/runs', 'Review scored attempts, solved challenges, streaks, badges, and personal history.', ['Filter attempts by status, challenge, date, or score.', 'Open an attempt and its feedback.', 'Review solved count, streak, badges, and progression.', 'Managers can review team results only when their role allows it.']),
    guidePage(fault, 'fault-evidence', 'Evidence', '/evidence', 'See which checks and clues supported each submitted diagnosis.', ['Search by attempt or challenge.', 'Review the chosen action, observation, clue order, and time.', 'Keep private learner work limited to the right learner and team.', 'Export results through Reports when allowed.']),
    guidePage(fault, 'fault-authoring', 'Authoring', '/authoring', 'Create, test, revise, publish, export, and retire diagnostic challenges for your team.', ['Create a draft case and scenario.', 'Define the available actions, clue order, possible causes, fix, scoring, and safety notes.', 'Run the built-in checks and fix problems before publishing.', 'Publish a new revision or retire future starts without changing completed attempts.', 'Export approved challenge data.'], { access: 'Approved challenge authors, organization administrators, or platform administrators.' }),
    guidePage(fault, 'fault-reports', 'Reports', '/reports', 'Review individual and team results, solved cases, and practice gaps.', ['Choose your own results or a team view you are allowed to see.', 'Review completion, scores, challenges, categories, and progress.', 'Create a downloadable report from completed attempts.', 'Use the results as training history, not as an unsupported professional certification.']),
    guidePage(fault, 'fault-settings', 'Workspace rules and access', '/settings', 'Review how training cases, scoring, private proof, authoring, and team access are handled.', ['Confirm your current organization and FaultlineLab role.', 'Review the safe challenge-command and score boundaries.', 'Check whether your role can assign or publish team challenges.', 'Use OperatorOS for account, membership, plan, or app-access changes.']),
  ],
};

export const POOL_HALL_GUIDE: HelpGuide = {
  id: 'ninja-pool-hall', name: 'Operator Pool Hall', kind: 'companion-application', accent: '#22d3ee',
  description: 'Practice, CPU 8-ball, local hot-seat play, protected online rooms, match history, player progress, and table settings.',
  availability: 'Available now. Online play may remain unavailable until the live match service is ready.', startHref: `${pool}/`,
  pages: [
    guidePage(pool, 'pool-hall', 'Hall', '/', 'Choose a play mode and see your recent results and progress.', ['Start practice, CPU 8-ball, local hot-seat, or available online play.', 'Review recent matches and progression.', 'Open rules, settings, history, or your player profile.']),
    guidePage(pool, 'pool-practice', 'Practice', '/practice', 'Clear the rack at your pace and save a practice summary.', ['Start or reset a free-shoot table.', 'Aim, set power, shoot, and continue after the rules are applied.', 'Review shot and rack feedback.', 'Finish and save the practice summary.']),
    guidePage(pool, 'pool-cpu', 'Vs CPU', '/cpu', 'Play a complete 8-ball match against the house opponent.', ['Start a new CPU match.', 'Take turns under the displayed group, foul, turn, and win rules.', 'Resume the saved match after a refresh when available.', 'Finish and record the result and statistics.']),
    guidePage(pool, 'pool-local', 'Local match', '/local', 'Play a two-player hot-seat match on one device and save the result.', ['Set the two local player names.', 'Start an 8-ball match and alternate turns.', 'Follow foul, group, eight-ball, and win feedback.', 'Finish and save the match result.']),
    guidePage(pool, 'pool-online', 'Online', '/online', 'Host, join, play, and reconnect to a protected room when online play is available.', ['Check online availability before creating a room.', 'Host or join with the room flow.', 'Take a valid turn and wait for confirmation before continuing.', 'Reconnect to the saved room after an interruption.', 'Leave or finish after the match service confirms the result.'], { notes: ['When online play is unavailable, use Practice, Vs CPU, or Local match.'] }),
    guidePage(pool, 'pool-history', 'History and stats', '/history', 'Review saved results, aggregates, and player progression.', ['Filter saved practice and match results.', 'Review wins, losses, racks, shots, fouls, and mode summaries.', 'Open a retained match result where supported.', 'Use server results rather than client-only animation state.']),
    guidePage(pool, 'pool-profile', 'Profile', '/profile', 'Review your player profile, results, and progression.', ['Confirm the signed-in account and organization.', 'Review your display name, progression, and saved statistics.', 'Use OperatorOS for password, email, or membership changes.']),
    guidePage(pool, 'pool-settings', 'Rules and settings', '/settings', 'Configure player feedback, table speed, and supported rule variations.', ['Review the active ruleset.', 'Set allowed feedback and table preferences.', 'Save preferences and verify them after reload.', 'Reset to supported defaults if the table becomes confusing.']),
  ],
};

export const BRANDFORGE_GUIDE: HelpGuide = {
  id: 'brandforgeos', name: 'BrandForgeOS', kind: 'companion-application', accent: '#f0abfc',
  description: 'Reusable brand kits, audience profiles, campaigns, content drafts, approvals, calendars, performance tracking, and exports.',
  availability: 'Available now for brand kits, campaign production, local logo files, review, calendar, reporting, and exports. Direct publishing connections are not available yet.', startHref: `${brand}/`,
  pages: [
    guidePage(brand, 'brand-dashboard', 'Dashboard', '/', 'See active brands, campaigns, deadlines, approvals, and performance in one creative workspace.', ['If the workspace is empty, create the brand, define the audience, and start the first campaign.', 'Work from late content and campaigns through approvals and scheduling gaps.', 'Use the main action to open the item that needs work.', 'Confirm the selected organization before using shared assets.']),
    guidePage(brand, 'brand-brands', 'Brands', '/brands', 'Build reusable brand kits with voice, positioning, colors, type, rules, and approved assets.', ['Create and edit a brand profile.', 'Save the approved voice, positioning, color palette, typography, rules, and asset links.', 'Review brand details and connected campaigns.', 'Keep passwords, secret values, and private customer data out of creative fields.']),
    guidePage(brand, 'brand-personas', 'Personas', '/personas', 'Describe the people each offer serves so campaigns begin with a focused message.', ['Create and edit an audience profile.', 'Record needs, motivations, objections, preferred channels, and research notes.', 'Choose that audience in campaign briefs.', 'Label assumptions clearly instead of presenting them as confirmed research.']),
    guidePage(brand, 'brand-campaigns', 'Campaigns', '/campaigns', 'Keep the brief, offer, audience, content, tasks, and approvals together through launch preparation.', ['Create a campaign and choose its brand, audience, goal, offer, and dates.', 'Manage the brief and expected deliverables.', 'Track planning, production, review, approval, scheduling, and completion.', 'Review the calendar, assets, results, and exports tied to the campaign.']),
    guidePage(brand, 'brand-content', 'Content and assets', '/content', 'Create and compare campaign copy, landing-page drafts, and asset records before approval.', ['Create or edit a deliverable.', 'Attach the correct brand and campaign.', 'Keep drafts, revisions, and the selected output together.', 'Submit the work for human review before use.', 'Upload only approved private assets.']),
    guidePage(brand, 'brand-calendar', 'Content calendar', '/calendar', 'Plan campaign deliverables, spot late work, and see what needs review next.', ['Create or move a calendar item.', 'Choose the campaign, deliverable, channel, owner, and planned date.', 'Filter upcoming, overdue, or completed work.', 'Use “Record publication” only after the content was published elsewhere.']),
    guidePage(brand, 'brand-approvals', 'Approvals', '/approvals', 'Check campaign work before it is exported or recorded as published elsewhere.', ['Open the review queue.', 'Review the brand, draft, creation details, and required corrections.', 'Approve or reject the work when your role allows it.', 'Add a clear decision note so the team knows what changed.'], { access: 'Approval actions require an approved manager or administrator role.' }),
    guidePage(brand, 'brand-ai', 'AI workflows', '/ai-workflows', 'Turn the saved brand, audience, offer, and channels into a first draft for review.', ['Choose the brand, campaign, reference material, and purpose.', 'Review whether the AI service is connected and how much usage the request needs.', 'Create a draft and review what it was based on.', 'Edit, reject, or submit the result for approval.', 'If the service fails, confirm that usage was not charged twice before retrying.']),
    guidePage(brand, 'brand-analytics', 'Analytics', '/analytics', 'Review recorded campaign results and decide what to continue, change, or stop.', ['Record or import supported campaign results.', 'Filter by campaign, channel, date, or measure.', 'Review trends and recommendations tied to those results.', 'Open the related campaign or deliverable to act.']),
    guidePage(brand, 'brand-reports', 'Reports and exports', '/reports', 'Create and download campaign reports and files your team or client can review.', ['Choose the brand, campaign, content, calendar, or result set to include.', 'Create the report or export.', 'Review its status, verification details, and included data.', 'Download it when your role allows it.']),
    guidePage(brand, 'brand-integrations', 'Connections and exports', '/integrations', 'Move approved work into the tools your team uses and see which direct publishing connections are available.', ['Download a logo as SVG or PNG for import into Canva or Figma.', 'Send an approved campaign to Deploy Ops for a complete campaign package.', 'Check whether direct advertising, social, email, analytics, CRM, or webhook connections are available before relying on them.', 'Record an external publication only after a person verifies it and supplies the published URL, post ID, or campaign receipt.'], { access: 'Brand editors may create files and send approved work; organization administrators control any future connections.' }),
    guidePage(brand, 'brand-settings', 'Workspace profile', '/settings', 'Keep the business profile, goals, and preferred channels that guide campaign work.', ['Review the current industry, business type, products, ideal customer, market, goals, and channels.', 'Correct the profile before creating new campaign drafts.', 'Use Plan and Security to review usage.', 'Use OperatorOS for account, membership, plan, or app-access changes.']),
  ],
};

export const SNAPPROOF_GUIDE: HelpGuide = {
  id: 'snapproofos', name: 'SnapProofOS', kind: 'companion-application', accent: '#2dd4bf',
  description: 'Customer field work, private photo and file capture, findings, review, branded reports, secure sharing, and record retention.',
  availability: 'Available now. File uploads and some document formats require the related services to be ready.', startHref: `${snap}/`,
  pages: [
    guidePage(snap, 'snap-overview', 'Proof operations overview', '/', 'See active jobs, missing proof, work awaiting review, and reports ready to deliver.', ['If the workspace is empty, add a customer, create a job, and capture the first photos or files.', 'Work through overdue jobs, submitted proof, report approvals, and open findings.', 'Use the main action to open the job or review item directly.', 'Confirm the selected organization before handling private files.']),
    guidePage(snap, 'snap-customers', 'Customers', '/customers', 'Keep each customer connected to their jobs, proof packages, and reports.', ['Create, search, open, and edit customers.', 'Review linked jobs, cases, reports, and activity.', 'Archive a customer only when linked work and retention rules allow it.']),
    guidePage(snap, 'snap-projects', 'Projects', '/projects', 'Use each job as a workspace for the people, proof, findings, costs, and final report.', ['Browse active job workspaces.', 'Review status, customer, assignment, dates, findings, costs, photos, and files.', 'Open the job to make changes.']),
    guidePage(snap, 'snap-jobs', 'Jobs', '/jobs', 'Plan customer work, collect the required proof, and move each job through review to delivery.', ['Create and edit a customer job.', 'Assign team members, dates, scope, and status.', 'Open the job for capture, findings, notes, costs, review, and reports.', 'Complete or archive it when the page confirms linked records are ready.']),
    guidePage(snap, 'snap-capture', 'Capture', '/capture', 'Add private photos and files from the field, even when the device must upload them later.', ['Choose the correct job.', 'Capture or select an approved file type.', 'Review the file checks and upload result under Technical details.', 'Retry only a failed upload so a confirmed file is not duplicated.', 'Keep the file private unless an approved report or share includes it.']),
    guidePage(snap, 'snap-work', 'Findings and notes', '/work', 'Record what was found, what was done, and the internal notes needed for review.', ['Choose the correct job.', 'Create or edit a finding.', 'Add an internal note without replacing earlier notes.', 'Review the author, time, revision, and supporting proof.']),
    guidePage(snap, 'snap-costs', 'Parts and labor', '/costs', 'Track job parts, labor, and customer value alongside the completed work.', ['Add a part, labor, or other supported cost.', 'Link it to the correct job.', 'Review quantity, amount, vendor, and totals.', 'Edit or archive entries only while job and report rules allow it.']),
    guidePage(snap, 'snap-templates', 'Templates', '/templates', 'Create reusable job checklists so technicians collect the right proof every time.', ['Create or edit a template.', 'Define the scope, steps, required proof, and report defaults.', 'Apply it to a new or eligible job.', 'Review the copied checklist before field use.']),
    guidePage(snap, 'snap-cases', 'Evidence cases', '/cases', 'Keep photos, files, findings, decisions, reports, and retention details together for one piece of work.', ['Create and open a case.', 'Connect the jobs, proof, findings, reviewers, and reports.', 'Review status, legal hold, retention date, and activity.', 'Archive it only after the page confirms every requirement is met.']),
    guidePage(snap, 'snap-evidence', 'File verification', '/evidence', 'Inspect private photos and files, confirm they are unchanged, and keep their history available.', ['Review file details, safety scan, file-verification code, and origin under Technical details.', 'Open private files only when your current organization and role allow it.', 'Use the verification result to confirm a file has not changed.', 'Link proof to findings, review, reports, and history.', 'Never publish raw private-file URLs.']),
    guidePage(snap, 'snap-findings', 'Case findings', '/findings', 'Document the finding, resolution, next step, and internal review notes for the active job.', ['Create or update a finding.', 'Link the supporting photos or files.', 'Record severity, conclusion, and next action.', 'Add review notes without changing earlier history.']),
    guidePage(snap, 'snap-review', 'Review', '/review', 'Check submitted proof, completed jobs, and reports before customer delivery.', ['Open the work waiting for review.', 'Check the photos, files, findings, privacy, and completeness.', 'Approve or reject it with a clear decision note.', 'Confirm the decision appears in the job history.'], { access: 'Approved reviewer, organization administrator, owner, or platform administrator.' }),
    guidePage(snap, 'snap-reports', 'Reports', '/reports', 'Create a branded customer report from approved job details, findings, costs, photos, and files.', ['Choose an approved job and report template.', 'Create the report from the current job details.', 'Review its revision, status, branding, verification details, findings, and proof.', 'Create a new report revision instead of changing a report that was already approved.']),
    guidePage(snap, 'snap-share', 'Secure sharing', '/share', 'Create an expiring report link and revoke it whenever access should end.', ['Choose an approved report.', 'Set the expiration and available access options.', 'Create the link and deliver it through an approved channel.', 'Review link activity and revoke it when no longer needed.']),
    guidePage(snap, 'snap-exports', 'Exports', '/exports', 'Create PDF or DOCX reports and approved proof packages for delivery or recordkeeping.', ['Choose what to include and the file format.', 'Create the export.', 'Review its status, verification details, and included content.', 'Download it when your role allows it.', 'If a format is unavailable, connect the required service rather than treating the export as complete.']),
    guidePage(snap, 'snap-custody', 'Chain of custody', '/custody', 'See when each photo, file, and review decision was added or changed.', ['Choose a case or proof item.', 'Review capture, access, file-check, review, report, sharing, hold, and archive events in order.', 'Check that the history has no unexplained gap.', 'This history does not grant access to another organization’s private files.']),
    guidePage(snap, 'snap-retention', 'Retention', '/retention', 'Set review dates, legal holds, and when completed proof can be archived.', ['Review records approaching their retention dates.', 'Set or update the approved retention policy.', 'Place or release a legal hold with a reason.', 'Archive only when the page confirms the record is eligible.'], { access: 'Approved manager, organization administrator, owner, or platform administrator.' }),
    guidePage(snap, 'snap-team', 'Team', '/team', 'Choose organization members who can own or review proof work.', ['Search available members.', 'Review each role and assignment eligibility.', 'Use OperatorOS to invite, remove, or change members.']),
    guidePage(snap, 'snap-activity', 'Activity', '/activity', 'See recent field actions, decisions, and updates across your organization.', ['Filter job, capture, review, report, sharing, and retention activity.', 'Open the related record.', 'Use the person, action, and support reference to investigate an unexpected change.']),
    guidePage(snap, 'snap-branding', 'Branding', '/branding', 'Set the logo, colors, and business details used on customer reports.', ['Set the report name, colors, and contact details.', 'Upload approved brand assets.', 'Preview the report presentation.', 'Keep customer proof and secret values out of brand settings.'], { access: 'Organization administrator, owner, or platform administrator.' }),
    guidePage(snap, 'snap-settings', 'Privacy, review, and access', '/settings', 'Review how private files, approvals, controlled share links, and account access are handled.', ['Review private-file download protection.', 'Confirm which roles may collect, submit, approve, hold, or archive work.', 'Use controlled links for customer reports and deliver them through an approved external channel.', 'Use OperatorOS for account, membership, plan, or app-access changes.']),
  ],
};

export const STUDYFORGE_GUIDE: HelpGuide = {
  id: 'studyforge-ai', name: 'StudyForge AI', kind: 'companion-application', accent: '#c4b5fd',
  description: 'Private study material, complete study sets, flashcards, quizzes, sessions, AI-assisted drafts, progress, and exports.',
  availability: 'Available now. AI drafting requires the related service and available usage.', startHref: `${study}/`,
  pages: [
    guidePage(study, 'study-dashboard', 'Dashboard', '/', 'Continue active study sets, prepare for exams, and focus on the material that needs more work.', ['If the workspace is empty, set your learning rhythm and create one complete set from existing notes.', 'Start with the nearest exam, weakest quiz result, or interrupted study set.', 'Use the main action to resume the next learning step.', 'Add the notes or documents you want AI Studio to use before requesting a draft.']),
    guidePage(study, 'study-sources', 'Sources and notes', '/sources', 'Keep private notes and approved documents connected to the study sets they support.', ['Create subjects and learning-material records.', 'Write private notes or upload an approved document.', 'Review privacy, excerpts, file checks, and where the material is used.', 'Use the material in AI Studio without sharing it with another organization.']),
    guidePage(study, 'study-sets', 'Study sets', '/sets', 'Create and organize sets with review material, flashcards, quizzes, and a study plan.', ['Create folders and sets.', 'Add or edit the title, description, and supporting material.', 'Move learning material through draft, review, and published states.', 'Return later and continue the same set.']),
    guidePage(study, 'study-flashcards', 'Flashcards', '/flashcards', 'Practice published cards and let each result shape when the material comes back.', ['Choose a deck you can access.', 'Reveal each answer and record how well you remembered it.', 'StudyForge schedules the next review for you.', 'Review your card history without changing another learner’s progress.']),
    guidePage(study, 'study-quizzes', 'Quizzes', '/quizzes', 'Create, publish, take, and grade quizzes with saved results.', ['Review or edit the draft questions.', 'Publish only after a person reviews them.', 'Start and submit an attempt.', 'Review the calculated score, answer feedback, and prior attempts.']),
    guidePage(study, 'study-sessions', 'Sessions and plans', '/sessions', 'Follow study plans, run focused sessions, track countdowns, and mark work complete.', ['Create or open a study plan.', 'Start a timed or untimed session.', 'Complete the planned flashcard, quiz, or reading work.', 'Record completion and review prior sessions.']),
    guidePage(study, 'study-studio', 'AI Studio', '/studio', 'Turn approved notes and documents into editable learning drafts.', ['Choose the learning material and what you want to practice.', 'Check whether AI-assisted creation and usage are available.', 'Create editable flashcards, a quiz, or a study plan.', 'Compare any quoted passage with your original notes, edit the draft, and publish only after review.']),
    guidePage(study, 'study-progress', 'Progress and exports', '/progress', 'Review scores, recall, study sessions, activity, and downloadable progress records.', ['Filter your progress by set, subject, or date.', 'Review quiz scores, flashcard recall, plans, and session trends.', 'Create a supported export.', 'Download only your own results or a team view your role allows.']),
    guidePage(study, 'study-settings', 'Plan and usage', '/settings', 'Review what your StudyForge AI plan includes and how much of the monthly allowance has been used.', ['Review AI generations and quiz attempts for the current month.', 'Check the number of flashcards allowed in each set and other plan limits.', 'Confirm the current organization and StudyForge AI access.', 'Use OperatorOS for account, membership, billing, or app access.']),
  ],
};

export const DEPLOY_OPS_GUIDE: HelpGuide = {
  id: 'ninja-launch-kit', name: 'Deploy Ops', kind: 'companion-application', accent: '#67e8f9',
  description: 'Complete campaign-launch packages with reusable templates, generated copy, visual-production briefs, launch tasks, approvals, and reviewed downloads.',
  availability: 'Available now for campaign preparation, review, and export. Deploy Ops does not publish, send, purchase, or deploy through an external service.', startHref: `${deploy}/dashboard`,
  pages: [
    guidePage(deploy, 'deploy-dashboard', 'Dashboard', '/dashboard', 'See campaign packages, overdue launch tasks, review checks, exports, and the next campaign action.', ['If the workspace is empty, choose a business template and answer the campaign brief.', 'Start with unfinished packages, overdue checklist work, missing exports, and launches awaiting external confirmation.', 'Use the main action to open the exact package or review item.', 'Treat every external delivery as incomplete until a person verifies and records it.']),
    guidePage(deploy, 'deploy-releases', 'Campaign launch packages', '/projects', 'Keep the brief, generated campaign materials, visual directions, tasks, files, reviews, and revisions together.', ['Create a package from a real offer and target customer.', 'Review the landing, ad, email, SMS, social, FAQ, flyer, checklist, and visual briefs.', 'Use the launch workspace for owners, phases, milestones, tasks, and supporting files.', 'Record external completion only after checking the publishing tool and entering the confirmation reference.']),
    guidePage(deploy, 'deploy-templates', 'Templates', '/templates', 'Start from one of 20 business-specific campaign structures instead of a blank brief.', ['Search or browse the business templates.', 'Preview the target market and package structure.', 'Load the template into the builder.', 'Replace every example assumption with the real offer before generation.']),
    guidePage(deploy, 'deploy-configuration', 'Campaign brief', '/brief', 'Capture the business, target customer, offer, desired action, pain point, tone, brand, channels, and deadline once.', ['Complete the required brief fields.', 'Choose the built-in generator or request AI refinement when the shared service is available.', 'Preview without consuming generation allowance.', 'Generate only when the inputs are ready for team review.']),
    guidePage(deploy, 'deploy-artifacts', 'Campaign deliverables', '/deliverables', 'Review the complete copy package and nine visual-production briefs before handing work to a designer or publisher.', ['Check every claim, price, date, link, and call to action.', 'Compare the deliverables with the approved offer and brand.', 'Use the launch workspace for supporting files and approval tasks.', 'Keep passwords, secret values, and customer data out of the package.']),
    guidePage(deploy, 'deploy-readiness', 'Launch checklist and review', '/review', 'Find missing campaign work, collect approval, and prepare the files for external publishing.', ['Complete the required launch tasks and review checks.', 'Approve the exact copy, visuals, links, dates, prices, and audience.', 'Create the campaign export before leaving the workspace.', 'Leave the launch incomplete while any required item is missing.', 'After publishing elsewhere, record the publishing receipt, campaign URL or post ID, or reviewer and timestamp.']),
    guidePage(deploy, 'deploy-exports', 'Campaign downloads', '/exports', 'Download approved campaign packages and revisit files already prepared for your team.', ['Choose the saved package and an allowed format.', 'Create the download.', 'Confirm the package is complete, branded correctly, and ready for the person publishing it.', 'Download it for the person using the external publishing tool.']),
    guidePage(deploy, 'deploy-settings', 'Settings', '/settings', 'Review plan limits, usage, brand-profile allowance, export options, and organization administration.', ['Review your organization, role, app access, and generation usage.', 'Check kit limits, brand-profile limits, watermarking, and white-label access.', 'Use the readable settings summary instead of raw internal statistics.', 'Use OperatorOS for account, membership, billing, or app access.']),
  ],
};

export const CALLCOMMAND_GUIDE: HelpGuide = {
  id: 'callcommand-ai', name: 'CallCommand AI', kind: 'companion-application', accent: '#5eead4',
  description: 'AI-assisted phone intake, call history, consent-aware recordings and transcripts, follow-up work, and MSP routing.',
  availability: 'Available for setup and testing. Live Twilio and MSP workflows require approved service connections.', startHref: `${call}/`,
  pages: [
    guidePage(call, 'call-switchboard', 'Switchboard', '/', 'See setup progress, clearly labeled simulations or live call activity confirmed by the phone service, caller outcomes, and follow-ups that need attention.', ['If setup is incomplete, work through the listed requirements in order.', 'Use guided setup to review number options, create the receptionist, select a workflow, run a simulation, and check connected services.', 'CallCommand is currently available for setup and simulation until a live phone connection passes its checks.', 'Going live requires administrator approval and a successful phone-service check.']),
    guidePage(call, 'call-calls', 'Calls', '/calls', 'Review summaries, timelines, recordings, transcripts, and the follow-up work created from each call.', ['Search and filter calls by status, channel, organization, or date.', 'Open a call and review its history.', 'Review purpose, consent, confidence, connected service, outcome, and linked work.', 'Use test connections only when the page labels them clearly.']),
    guidePage(call, 'call-recordings', 'Recordings', '/recordings', 'Listen to available call recordings when consent and your team role allow it.', ['Filter call recordings.', 'Confirm consent and connection status before playback.', 'Review how long the recording will be kept and who can access it.', 'If a recording is missing or unavailable, the page will not create substitute audio.']),
    guidePage(call, 'call-transcripts', 'Transcripts', '/transcripts', 'Read saved transcripts and keep automated analysis separate from what the caller actually said.', ['Open a transcript you are allowed to review.', 'Review timestamps, processing status, and redactions.', 'Request supported processing when the related service is connected.', 'Check automated conclusions against the transcript.']),
    guidePage(call, 'call-analysis', 'Analysis', '/analysis', 'Review summaries, tone, urgency, extracted details, and the call path.', ['Choose a saved call or transcript.', 'Review whether the result came from a connected AI service or built-in rules.', 'Confirm the issue, urgency, caller identity, and routing details.', 'Send suggestions into follow-up work only after a person reviews them.']),
    guidePage(call, 'call-actions', 'Actions', '/actions', 'Review the tickets, leads, tasks, cases, and alerts created from calls.', ['Review queued, completed, failed, or suppressed follow-up work.', 'Confirm the correct organization and support relationship before proceeding.', 'Use the supported retry action so the same work is not created twice.', 'Account changes, credentials, destructive actions, and unsupported automation remain blocked.']),
    guidePage(call, 'call-automations', 'Automations', '/automations', 'Decide how the receptionist handles calls and what follow-up work it may create.', ['Create or edit a receptionist profile.', 'Build and test a call workflow revision.', 'Set business hours, routing, consent, and allowed actions.', 'Activate only a reviewed workflow.', 'Use the emergency shutoff if a connection or policy should no longer be trusted.']),
    guidePage(call, 'call-numbers', 'Numbers and channels', '/numbers', 'Connect phone lines, set business hours and consent behavior, and choose approved transfer destinations.', ['Register an approved phone number or channel.', 'Set the incoming-call purpose and organization routing.', 'Maintain only approved transfer destinations.', 'Check call-notification setup and channel status.'], { access: 'Organization administrator, owner, or platform administrator.' }),
    guidePage(call, 'call-providers', 'Connected services', '/providers', 'Manage phone and MSP connections, current health, safety shutoffs, and problems needing attention.', ['Enter protected credentials and public callback details in their proper fields.', 'Confirm incoming notifications and destination routing.', 'Test the approved connection.', 'Review health, the latest error, recent activity, and the safety shutoff.', 'Never place full credentials in ordinary browser fields or notes.'], { access: 'Organization administrator, owner, or platform administrator.' }),
    guidePage(call, 'call-organizations', 'Organizations and support contacts', '/organizations', 'Connect callers with the right support organization, trusted line, and contact.', ['Choose an organization from the shared Directory.', 'Create or update its support profile.', 'Connect trusted phone lines and support contacts.', 'Create, replace, revoke, and review support links.', 'Unrecognized callers cannot trigger automated support work.']),
    guidePage(call, 'call-compliance', 'Compliance and call records', '/compliance', 'Review consent, prohibited actions, safety levels, change history, and setup requirements.', ['Review consent and do-not-contact status.', 'Review the policy and allowed actions.', 'Follow a call from intake through organization match, case, action, and connected-service result.', 'Use setup checks and emergency shutoffs to keep unsafe automation disabled.']),
    guidePage(call, 'call-settings', 'Settings', '/settings', 'Manage follow-up defaults, incident controls, team access, and safety limits.', ['Review the organization, team role, CallCommand access, connected services, and incident status.', 'Set the available defaults.', 'Enable or disable supported incident behavior.', 'Use OperatorOS for account, membership, billing, or app access.']),
  ],
};

export const SCRIPT_OPS_GUIDE: HelpGuide = {
  id: 'ninjamation', name: 'Script Ops', kind: 'companion-application', accent: '#7dd3fc',
  description: 'Reviewed defensive scripts, revision history, approved-library updates, AI-assisted drafts, human approval, and download history.',
  availability: 'Available now for script review and delivery. Scripts are downloaded for external use; Script Ops does not run them.', startHref: `${script}/library`,
  pages: [
    guidePage(script, 'script-dashboard', 'Dashboard', '/dashboard', 'See approved scripts, drafts awaiting review, library update issues, and recent downloads.', ['If the workspace is empty, search the reviewed library before creating a script.', 'Start with critical safety findings, approval work, failed imports, and missing approved versions.', 'Draft a script only when the library has no suitable reviewed option.', 'Keep approval in human hands and run scripts through your normal external tools.']),
    guidePage(script, 'script-library', 'Script library', '/library', 'Search, inspect, save, and download the exact approved script version your technician needs.', ['Search by platform, category, tag, approval, or risk.', 'Open the script and review its purpose, prerequisites, findings, revision, and recorded file check.', 'Save useful entries as favorites.', 'Download only the current approved version and inspect it before use.'], { notes: ['Script Ops delivers reviewed source code. It does not run scripts in the browser, web server, or API.'] }),
    guidePage(script, 'script-sources', 'Library updates', '/sources', 'Import changes from approved libraries and review any update problems.', ['Review the approved script catalogs.', 'Start a library update when your role allows it.', 'Review created, updated, skipped, rejected, and failed entries.', 'Retry supported failures. Missing entries remain available for review instead of being deleted.'], { access: 'Library update controls require an organization administrator.' }),
    guidePage(script, 'script-ai', 'AI drafting', '/generate', 'Create a defensive script draft, check it for risk, and send it through human review.', ['Describe the task, target platform, inputs, safety needs, validation, and rollback.', 'Check whether the AI service and usage are available.', 'Create one draft.', 'Review the safety findings and what the draft was based on.', 'Edit and submit it for review; run it only through your approved external process.']),
    guidePage(script, 'script-review', 'Review queue', '/review', 'Review, approve, reject, request changes to, or retire scripts without running them.', ['Open a pending revision and review the code, origin, findings, documentation, and recorded file check.', 'Resolve critical findings before approval.', 'Approve, reject, request changes, or retire it when your role allows.', 'Confirm the approved revision and decision appear in history.'], { access: 'Approval decisions require an organization administrator, owner, or platform administrator.' }),
    guidePage(script, 'script-downloads', 'Download history', '/runs', 'See who downloaded each approved script revision and when.', ['Filter by script, revision, user, or date.', 'Review the approved revision, recorded file check, person, and request details.', 'Download again only from the current approved revision.', 'This history confirms delivery, not whether the script ran successfully elsewhere.']),
    guidePage(script, 'script-versions', 'Versions', '/versions', 'Compare script revisions, safety findings, approval decisions, and library updates.', ['Open the revision history for a script.', 'Compare details and safety findings.', 'Review which revision is current and approved.', 'Create a new draft instead of changing an approved revision.']),
    guidePage(script, 'script-settings', 'Settings', '/settings', 'Manage usage, team access, approval preferences, and library update rules.', ['Review your organization, team role, Script Ops access, AI usage, and connected service.', 'Review approved script libraries and approval policy.', 'Use OperatorOS for account, membership, billing, or app access.']),
    guidePage(script, 'script-admin', 'Administration', '/admin', 'Create drafts, manage approved script libraries, and control review policy.', ['Create a draft from an approved script file or manual input.', 'Review library update rules and update status.', 'Manage available administration settings.', 'Keep script execution outside Script Ops.'], { access: 'Organization administrator, owner, or platform administrator.' }),
  ],
};

export const OUTCALL_GUIDE: HelpGuide = {
  id: 'outcall', name: 'OutCall', kind: 'companion-application', accent: '#c4b5fd',
  description: 'Discreet exit assistance using one verified personal number, private trigger phrases, scheduled calls, history, privacy, and safety controls.',
  availability: 'Coming soon. Live calls require an approved calling service and a verified personal number.', startHref: `${outcall}/`,
  pages: [
    guidePage(outcall, 'outcall-overview', 'OutCall overview', '/', 'Check your safety acknowledgement, verified number, assistance profile, schedule, and call-service readiness.', ['Review whether the safety acknowledgement is current.', 'Confirm one personal mobile number.', 'Review the neutral assistance profile and call-service status.', 'Open schedules, triggers, calls, or privacy controls.'], { notes: ['OutCall is not an emergency or monitoring service and does not replace contacting local emergency services.'] }),
    guidePage(outcall, 'outcall-contacts', 'Verified destination and rescue profiles', '/contacts', 'Prepare neutral assistance messages for your verified number without creating a bulk contact list.', ['Create or edit a neutral assistance profile.', 'Choose only the personal number you verified.', 'Review the call script, caller ID, keypad choices, and privacy limits.', 'OutCall does not support arbitrary recipients or bulk audiences.']),
    guidePage(outcall, 'outcall-schedules', 'Schedules', '/schedules', 'Request an immediate or future call to your verified number.', ['Choose the profile, timing, and brief context.', 'Check number verification, call-service readiness, request limits, and safety requirements.', 'Create the schedule once.', 'Cancel before the calling service attempts it when allowed.', 'Review the request and confirmed delivery result.']),
    guidePage(outcall, 'outcall-triggers', 'Private triggers', '/campaigns', 'Choose private SMS phrases that request one assistance call.', ['Create a private trigger phrase.', 'Link your verified number and assistance profile.', 'Review activation, duplicate-request protection, request limits, and number masking.', 'Disable or replace a phrase that may be compromised.', 'OutCall does not support bulk campaigns.']),
    guidePage(outcall, 'outcall-calls', 'Calls', '/calls', 'See whether each call was requested, scheduled, attempted, confirmed, failed, or canceled.', ['Filter and open call requests.', 'Review the masked number, profile, trigger, calling service, and status history.', 'Cancel an eligible future call.', 'If the calling service has not confirmed the outcome, OutCall shows it as unknown.']),
    guidePage(outcall, 'outcall-reminders', 'Reminders', '/reminders', 'Schedule a future exit-assistance call without marketing messages or audience targeting.', ['Choose your verified number and neutral profile.', 'Set one future time.', 'Check the call service and number verification.', 'Cancel or review the resulting schedule.']),
    guidePage(outcall, 'outcall-verification', 'Verification', '/verification', 'Confirm ownership of the only mobile number OutCall may call.', ['Enter your personal mobile number.', 'Request a verification code from the connected service.', 'Enter the code before it expires.', 'Review whether verification succeeded, expired, failed, or reached the request limit.', 'Verify the new number again after a change.']),
    guidePage(outcall, 'outcall-delivery', 'Delivery readiness', '/delivery', 'Check whether setup is complete and whether the calling service can confirm delivery.', ['Review the calling service, notifications, public callback address, request limit, and number verification.', 'Run only the available test call.', 'Review the last request, notification, error, and delivery result.', 'Live actions stay unavailable until every required check is complete.']),
    guidePage(outcall, 'outcall-history', 'History', '/history', 'Review prior call requests and outcomes.', ['Filter by date, status, profile, or trigger.', 'Open the masked request and calling-service history.', 'Review cancellation, attempt, answer, keypad, delivery, or failure details.', 'Use the Privacy page for exports.']),
    guidePage(outcall, 'outcall-compliance', 'Privacy and safety', '/compliance', 'Export or delete private data and review why OutCall is not an emergency service.', ['Review saved profiles, triggers, schedules, calls, and delivery details.', 'Create a privacy export when your role allows it.', 'Delete private OutCall data only after signing in again and resolving linked records.', 'Review number masking, retention, consent, and emergency notices.']),
    guidePage(outcall, 'outcall-settings', 'Settings', '/settings', 'Manage setup, privacy, approved access, and OutCall safety limits.', ['Review the organization, team role, OutCall access, number verification, and calling service.', 'Review the safety acknowledgement and available defaults.', 'Use OperatorOS for account, membership, billing, or app access.']),
  ],
};

export const COMPANION_MODULE_GUIDES = [
  FAULTLINELAB_GUIDE,
  POOL_HALL_GUIDE,
  BRANDFORGE_GUIDE,
  SNAPPROOF_GUIDE,
  STUDYFORGE_GUIDE,
  DEPLOY_OPS_GUIDE,
  CALLCOMMAND_GUIDE,
  SCRIPT_OPS_GUIDE,
  OUTCALL_GUIDE,
] as const;
