import { guidePage } from './page';
import type { HelpGuide } from './types';

const fault = 'https://faultlinelab.operatoros.net';
const pool = 'https://operatorpoolhall.operatoros.net';
const brand = 'https://brandforgeos.operatoros.net';
const snap = 'https://snapproofos.operatoros.net';
const study = 'https://studyforge-ai.operatoros.net';
const deploy = 'https://deployops.operatoros.net';
const call = 'https://callcommand-ai.operatoros.net';
const script = 'https://scriptops.operatoros.net';
const outcall = 'https://outcall.operatoros.net';

export const FAULTLINELAB_GUIDE: HelpGuide = {
  id: 'faultlinelab', name: 'FaultlineLab', kind: 'companion-application', accent: '#a78bfa',
  description: 'Diagnostic challenges, evidence-led investigations, assignments, durable attempts, authoring, proof, and learning reports.',
  availability: 'Active module', startHref: `${fault}/`,
  pages: [
    guidePage(fault, 'fault-overview', 'Learning operations overview', '/', 'See assignments, recent runs, challenge coverage, daily work, and durable skill progress.', ['Review current assignments, recent attempts, completion, streak, and badge posture.', 'Open a published challenge or resume an investigation.', 'Navigate to evidence, authoring, or reports when authorized.']),
    guidePage(fault, 'fault-challenges', 'Challenge library', '/challenges', 'Find compiler-published diagnostic cases and start a bounded investigation.', ['Search and filter by discipline, category, difficulty, or status.', 'Open challenge detail and review scenario, safety, and allowed actions.', 'Start a standard, daily, or approved Chaos-mode attempt.', 'Keep immutable challenge-version provenance with the run.']),
    guidePage(fault, 'fault-investigation', 'Investigation', '/sessions', 'Follow the evidence through allowlisted diagnostic actions and a server-scored conclusion.', ['Open or resume a durable session.', 'Run only the action options supplied by the challenge.', 'Unlock and inspect evidence in sequence.', 'Submit root cause and remediation proof.', 'Review server-owned score, feedback, and completed attempt state.']),
    guidePage(fault, 'fault-assignments', 'Assignments', '/assignments', 'Assign published challenges and track tenant-scoped learning work.', ['Create an assignment for an allowed member and published challenge.', 'Set due date or learning context.', 'Review assigned, started, completed, and overdue state.', 'Open the associated run without exposing another tenant’s progress.'], { access: 'Assignment creation and management require an authorized tenant role.' }),
    guidePage(fault, 'fault-runs', 'Runs and progress', '/runs', 'Review scored attempts, solved challenges, streaks, badges, and personal history.', ['Filter attempts by status, challenge, date, or score.', 'Open immutable run detail and feedback.', 'Review solved count, streak, badge, and progression summaries.', 'Distinguish personal history from manager-authorized tenant outcomes.']),
    guidePage(fault, 'fault-evidence', 'Evidence', '/evidence', 'Trace investigation actions and private proof back to durable attempts.', ['Search evidence by run or challenge.', 'Inspect action, observation, unlock order, timestamp, and integrity context.', 'Keep private proof tenant- and user-scoped.', 'Export only through an authorized report flow.']),
    guidePage(fault, 'fault-authoring', 'Authoring', '/authoring', 'Create, validate, revise, publish, export, and retire tenant-scoped diagnostic cases.', ['Create a draft case and structured scenario.', 'Define allowlisted actions, evidence graph, causes, remediation, scoring, and safety.', 'Run deterministic validation and repair blocking issues.', 'Publish an immutable version or retire future starts without rewriting old attempts.', 'Export approved case data.'], { access: 'Authorized challenge authors, organization administrators, or platform administrators.' }),
    guidePage(fault, 'fault-reports', 'Reports', '/reports', 'Review personal and authorized tenant learning outcomes without inventing certificates.', ['Choose personal or authorized team scope.', 'Review completion, score, challenge, category, and progress summaries.', 'Generate a bounded export from durable attempts.', 'Treat results as learning evidence, not an unsupported certification.']),
    guidePage(fault, 'fault-settings', 'Settings', '/settings', 'Review access, scoring, evidence, export, and challenge-authority boundaries.', ['Confirm OperatorOS identity, organization, role, and entitlement.', 'Review published scoring and evidence rules.', 'Inspect authoring and export permissions.', 'Open OperatorOS for account, membership, plan, or module-access changes.']),
  ],
};

export const POOL_HALL_GUIDE: HelpGuide = {
  id: 'ninja-pool-hall', name: 'Operator Pool Hall', kind: 'companion-application', accent: '#22d3ee',
  description: 'Practice, deterministic CPU 8-ball, local hot-seat, protected online rooms, history, profile, and table settings.',
  availability: 'Active module; online play may be disabled until relay acceptance is complete', startHref: `${pool}/`,
  pages: [
    guidePage(pool, 'pool-hall', 'Hall', '/', 'Choose the supported play mode and review current player posture.', ['Start practice, CPU 8-ball, local hot-seat, or available online play.', 'Review recent match and progression summaries.', 'Open rules, settings, history, or player profile.']),
    guidePage(pool, 'pool-practice', 'Practice', '/practice', 'Clear the rack at your pace and persist a practice summary.', ['Start or reset a free-shoot table.', 'Aim, set power, shoot, and continue after deterministic rule resolution.', 'Review shot and rack feedback.', 'Finish and save the practice summary.']),
    guidePage(pool, 'pool-cpu', 'Vs CPU', '/cpu', 'Play a complete deterministic 8-ball match against the house opponent.', ['Start a new CPU match.', 'Take turns under server-owned ball-group, foul, turn, and win rules.', 'Resume persisted match state after a refresh when available.', 'Finish and record the result and statistics.']),
    guidePage(pool, 'pool-local', 'Local match', '/local', 'Play and persist a two-player hot-seat match on one device.', ['Set the two local player labels.', 'Start an 8-ball match and alternate turns.', 'Follow foul, group, eight-ball, and win feedback.', 'Finish and save one authoritative match result.']),
    guidePage(pool, 'pool-online', 'Online', '/online', 'Host, join, play, and reconnect to server-verified rooms when online play is enabled.', ['Review online availability before creating a room.', 'Host or join using the bounded room flow.', 'Submit only valid turn actions and wait for server confirmation.', 'Reconnect to persisted room state after interruption.', 'Leave or finish without claiming a result the server did not confirm.'], { notes: ['When online play is disabled, use Practice, Vs CPU, or Local match. The guide remains available so the disabled state is understandable.'] }),
    guidePage(pool, 'pool-history', 'History and stats', '/history', 'Review saved results, aggregates, and player progression.', ['Filter saved practice and match results.', 'Review wins, losses, racks, shots, fouls, and mode summaries.', 'Open a retained match result where supported.', 'Use server results rather than client-only animation state.']),
    guidePage(pool, 'pool-profile', 'Profile', '/profile', 'Review progression and player identity under OperatorOS.', ['Confirm the OperatorOS-owned identity and organization.', 'Review display name, progression, and durable statistics.', 'Open OperatorOS for credential, email, or membership changes.']),
    guidePage(pool, 'pool-settings', 'Rules and settings', '/settings', 'Configure player feedback, table speed, and supported rule variations.', ['Review the active ruleset.', 'Set allowed feedback and table preferences.', 'Save preferences and verify them after reload.', 'Reset to supported defaults if the table becomes confusing.']),
  ],
};

export const BRANDFORGE_GUIDE: HelpGuide = {
  id: 'brandforgeos', name: 'BrandForgeOS', kind: 'companion-application', accent: '#f0abfc',
  description: 'Brand kits, personas, campaigns, content, approvals, calendars, provider-aware AI drafting, analytics, and exports.',
  availability: 'Active module; generation and delivery depend on configured providers', startHref: `${brand}/`,
  pages: [
    guidePage(brand, 'brand-dashboard', 'Dashboard', '/', 'Coordinate brands, campaigns, assets, approvals, usage, and measurable launch work.', ['If the workspace is empty, follow the three first-value steps for brand, audience, and controlled campaign generation.', 'Work the Campaign Flow Brief from top to bottom: overdue publishing, late campaigns, approvals, then scheduling gaps.', 'Use the primary action to open the exact owning route.', 'Confirm the selected organization before using shared assets.']),
    guidePage(brand, 'brand-brands', 'Brands', '/brands', 'Maintain durable brand kits, voice, visual rules, assets, and audience evidence.', ['Create and edit a brand profile.', 'Store approved voice, positioning, palette, typography, rules, and asset references.', 'Review brand detail and linked campaigns.', 'Keep secrets and private customer data out of public creative fields.']),
    guidePage(brand, 'brand-personas', 'Personas', '/personas', 'Maintain evidence-aware audience profiles used by campaigns.', ['Create and edit an audience persona.', 'Record needs, motivations, objections, channels, and evidence notes.', 'Select personas in campaign briefs.', 'Avoid presenting assumptions as verified research.']),
    guidePage(brand, 'brand-campaigns', 'Campaigns', '/campaigns', 'Move briefs, offers, content, and approval state through a durable workflow.', ['Create a campaign and select brand, audience, goal, offer, and dates.', 'Manage persisted brief and deliverable records.', 'Track draft, review, approved, scheduled, and completed states.', 'Review linked calendar, assets, analytics, and export history.']),
    guidePage(brand, 'brand-content', 'Content and assets', '/content', 'Create reviewable copy and asset records without presenting disabled generation as complete.', ['Create or edit content deliverables.', 'Attach approved brand and campaign context.', 'Store generation provenance, drafts, revisions, and selected output.', 'Submit for human review before use.', 'Manage private uploaded assets through validated storage.']),
    guidePage(brand, 'brand-calendar', 'Content calendar', '/calendar', 'Schedule persisted campaign deliverables and review upcoming work.', ['Create or move a calendar item.', 'Link campaign, deliverable, channel, owner, and planned date.', 'Filter upcoming, overdue, or completed work.', 'Confirm scheduling state without implying external publication.']),
    guidePage(brand, 'brand-approvals', 'Approvals', '/approvals', 'Review campaign and deliverable state before release or export.', ['Open the review queue.', 'Inspect brand context, draft, provenance, and required corrections.', 'Approve or reject through authorized server actions.', 'Record decision notes and preserve audit history.'], { access: 'Approval actions require an authorized manager or administrator role.' }),
    guidePage(brand, 'brand-ai', 'AI workflows', '/ai-workflows', 'Generate review-ready drafts with recorded provenance and honest provider state.', ['Choose an authorized brand, campaign, source context, and generation purpose.', 'Review provider readiness and metered usage before submitting.', 'Create a bounded draft and inspect provenance.', 'Edit, reject, or submit the result for human approval.', 'Confirm that provider failure does not consume usage more than once.']),
    guidePage(brand, 'brand-analytics', 'Analytics', '/analytics', 'Review persisted campaign performance and recommendations.', ['Record or import allowed campaign metrics.', 'Filter by campaign, channel, date, or metric.', 'Review trends and source-backed recommendations.', 'Open the owning campaign or deliverable for action.']),
    guidePage(brand, 'brand-reports', 'Reports and exports', '/reports', 'Create and retrieve authorized creative-operation reports and exports.', ['Choose brand, campaign, content, calendar, or analytics scope.', 'Generate a durable report/export record.', 'Review status, checksum, and included data.', 'Download only authorized artifacts.']),
    guidePage(brand, 'brand-integrations', 'Integrations', '/integrations', 'Configure controlled provider connections without weakening OperatorOS authority.', ['Review available provider types and readiness.', 'Store secret references server-side rather than raw values in the browser.', 'Test, disable, or revoke a connection.', 'Review bounded errors and last-known health.'], { access: 'Organization administrator, owner, or platform administrator.' }),
    guidePage(brand, 'brand-settings', 'Settings', '/settings', 'Review onboarding, plan usage, security, and creative workspace preferences.', ['Confirm organization, role, entitlement, and usage context.', 'Set allowed workspace preferences and defaults.', 'Review provider and upload boundaries.', 'Open OperatorOS for identity, membership, plan, or access changes.']),
  ],
};

export const SNAPPROOF_GUIDE: HelpGuide = {
  id: 'snapproofos', name: 'SnapProofOS', kind: 'companion-application', accent: '#2dd4bf',
  description: 'Customer field work, private capture, evidence integrity, findings, review, reports, secure sharing, custody, and retention.',
  availability: 'Active module; uploads and generated document formats depend on configured services', startHref: `${snap}/`,
  pages: [
    guidePage(snap, 'snap-overview', 'Evidence operations overview', '/', 'See jobs, captured proof, review pressure, approved delivery, and documented value.', ['If the workspace is empty, follow customer, job, and capture as the shortest proof-to-delivery path.', 'Work the Proof-to-Delivery Brief from overdue jobs through evidence, report, case, and finding review.', 'Use the direct case or queue link instead of reconstructing the workflow from the navigation.', 'Confirm tenant and access context before handling private evidence.']),
    guidePage(snap, 'snap-customers', 'Customers', '/customers', 'Manage tenant-scoped customers and their related proof jobs.', ['Create, search, open, and edit customer records.', 'Review linked jobs, cases, reports, and activity.', 'Archive only when dependencies and retention rules permit.']),
    guidePage(snap, 'snap-projects', 'Projects', '/projects', 'Use durable jobs as project workspaces without introducing a duplicate project authority.', ['Browse project-like job workspaces.', 'Review status, customer, assignment, dates, findings, costs, and evidence.', 'Open the canonical job record for changes.']),
    guidePage(snap, 'snap-jobs', 'Jobs', '/jobs', 'Plan and progress customer proof work from capture through completion.', ['Create and edit a customer job.', 'Assign authorized members, dates, scope, and status.', 'Open job detail for capture, findings, notes, costs, review, and reports.', 'Complete or archive through dependency-aware actions.']),
    guidePage(snap, 'snap-capture', 'Capture', '/capture', 'Collect private photos and files with validation, scanning, hashing, and offline-aware queue state.', ['Select the owning job or evidence case.', 'Capture or choose an approved file type.', 'Review size, MIME/signature, scan, checksum, and upload result.', 'Retry only a failed queued item; do not duplicate a confirmed upload.', 'Keep the file private unless an authorized report/share flow includes it.']),
    guidePage(snap, 'snap-work', 'Findings and notes', '/work', 'Record structured findings and append-only internal notes against selected work.', ['Select the correct job or evidence case.', 'Create or edit a structured finding.', 'Add an internal note without rewriting prior notes.', 'Review author, timestamp, version, and linked evidence.']),
    guidePage(snap, 'snap-costs', 'Parts and labor', '/costs', 'Track job costs and documented value without mixing platform billing.', ['Add part, labor, or other allowed cost entries.', 'Link entries to the correct job.', 'Review quantity, amount, vendor, and totals.', 'Edit or archive only while financial and report rules permit.']),
    guidePage(snap, 'snap-templates', 'Templates', '/templates', 'Create and apply repeatable tenant-scoped job templates.', ['Create or edit a template.', 'Define scope, steps, expected evidence, and report defaults.', 'Apply it to a new or eligible job.', 'Review the copied plan before field use.']),
    guidePage(snap, 'snap-cases', 'Evidence cases', '/cases', 'Group evidence, findings, decisions, reports, retention, and custody under a durable case.', ['Create and open a case.', 'Link jobs, evidence, findings, reviewers, and reports.', 'Review lifecycle, legal hold, retention, and activity.', 'Archive only after policy and authority checks.']),
    guidePage(snap, 'snap-evidence', 'Evidence integrity', '/evidence', 'Capture, inspect, verify, and preserve private evidence with durable hashes.', ['Review evidence metadata, file validation, scan, checksum, and source.', 'Open only with current tenant authorization.', 'Verify integrity against the stored hash.', 'Link evidence to findings, review, report, and custody events.', 'Never expose raw private files through public URLs.']),
    guidePage(snap, 'snap-findings', 'Case findings', '/findings', 'Record editable findings and append-only review notes against the active case.', ['Create or update an allowed finding with optimistic version checks.', 'Link supporting evidence.', 'Record severity, conclusion, and next action.', 'Add internal review notes without altering history.']),
    guidePage(snap, 'snap-review', 'Review', '/review', 'Approve or reject evidence, jobs, and reports through server-enforced authority.', ['Open pending review work.', 'Inspect evidence, findings, privacy, integrity, and completeness.', 'Approve or reject with a decision note.', 'Confirm the audit and custody event.'], { access: 'Authorized reviewer, organization administrator, owner, or platform administrator.' }),
    guidePage(snap, 'snap-reports', 'Reports', '/reports', 'Generate branded immutable report snapshots from persistent job and review state.', ['Choose an approved job/case and report template.', 'Generate a snapshot from current authorized data.', 'Review version, status, checksum, branding, and included findings/evidence.', 'Approve or supersede through a new report rather than rewriting history.']),
    guidePage(snap, 'snap-share', 'Secure sharing', '/share', 'Create bounded, revocable report links from authorized records.', ['Select an approved report.', 'Set allowed expiry or access boundary.', 'Create the share link and deliver it through an approved channel.', 'Review access activity and revoke immediately when no longer needed.']),
    guidePage(snap, 'snap-exports', 'Exports', '/exports', 'Generate and download PDF, DOCX, or approved hash-bound evidence exports.', ['Choose supported scope and format.', 'Generate an export record.', 'Review status, checksum, and included content.', 'Download through an authorized route.', 'Troubleshoot provider-disabled formats without fabricating a file.']),
    guidePage(snap, 'snap-custody', 'Chain of custody', '/custody', 'Verify the append-only sequence linking evidence and review events.', ['Select a case or evidence record.', 'Review ordered capture, access, hash, review, report, share, hold, and archive events.', 'Verify chain continuity.', 'Use the event detail as provenance, not as permission to access foreign evidence.']),
    guidePage(snap, 'snap-retention', 'Retention', '/retention', 'Set retention dates, legal holds, and archive eligibility with manager authority.', ['Review records approaching retention dates.', 'Set or update allowed retention policy.', 'Place or release a legal hold with a reason.', 'Archive only when the server confirms eligibility.'], { access: 'Authorized manager, organization administrator, owner, or platform administrator.' }),
    guidePage(snap, 'snap-team', 'Team', '/team', 'Review OperatorOS organization members available for proof-work assignment.', ['Search authorized members.', 'Review role and assignment eligibility.', 'Open OperatorOS to invite, remove, or change membership.']),
    guidePage(snap, 'snap-activity', 'Activity', '/activity', 'Review the tenant-scoped field action stream.', ['Filter job, capture, evidence, review, report, share, and retention events.', 'Open the owning record.', 'Use request and actor context to investigate an unexpected change.']),
    guidePage(snap, 'snap-branding', 'Branding', '/branding', 'Manage tenant report identity and approved brand assets.', ['Set allowed report name, colors, and contact presentation.', 'Upload approved brand assets through validation.', 'Preview report presentation.', 'Keep customer evidence and secrets out of brand settings.'], { access: 'Organization administrator, owner, or platform administrator.' }),
    guidePage(snap, 'snap-settings', 'Settings', '/settings', 'Review evidence privacy, access, review, sharing, and integration boundaries.', ['Confirm OperatorOS identity, organization, role, and entitlement.', 'Review upload, scan, export, and share readiness.', 'Set allowed module defaults.', 'Open OperatorOS for identity, membership, plan, or module-access changes.']),
  ],
};

export const STUDYFORGE_GUIDE: HelpGuide = {
  id: 'studyforge-ai', name: 'StudyForge AI', kind: 'companion-application', accent: '#c4b5fd',
  description: 'Private sources, study sets, flashcards, quizzes, sessions, source-grounded AI drafts, progress, and exports.',
  availability: 'Active module; AI generation depends on configured provider and usage availability', startHref: `${study}/`,
  pages: [
    guidePage(study, 'study-dashboard', 'Dashboard', '/', 'Continue study sets, sessions, quiz work, plans, and exam preparation.', ['If the workspace is empty, set the learning rhythm and create one complete set from existing notes.', 'Follow the Learning Focus Brief for the nearest exam, weak quiz results, and interrupted active sets.', 'Use the primary action to resume the exact learning step.', 'Open sources before requesting grounded generation.']),
    guidePage(study, 'study-sources', 'Sources and notes', '/sources', 'Keep private notes and approved documents attached to the learning records they support.', ['Create subjects and source records.', 'Write private notes or upload an approved document.', 'Review validation, privacy, excerpt, and source linkage.', 'Use sources in AI Studio without exposing them across tenants.']),
    guidePage(study, 'study-sets', 'Study sets', '/sets', 'Organize folders and create durable study sets.', ['Create folders and sets.', 'Add or edit set metadata and source relationships.', 'Manage draft, review, and published learning material.', 'Open the same set after refresh through its durable route.']),
    guidePage(study, 'study-flashcards', 'Flashcards', '/flashcards', 'Review published cards and persist spaced-repetition progress.', ['Choose an authorized deck.', 'Reveal answers and record recall outcome.', 'Persist next-review scheduling per user.', 'Review card history without changing another learner’s progress.']),
    guidePage(study, 'study-quizzes', 'Quizzes', '/quizzes', 'Create, publish, attempt, and grade quizzes with server-owned scores.', ['Review or edit a draft quiz and questions.', 'Publish only after human review.', 'Start and submit an attempt.', 'Review server-calculated score, answer feedback, and history.']),
    guidePage(study, 'study-sessions', 'Sessions and plans', '/sessions', 'Run study plans, flashcard sessions, countdowns, and completion tracking.', ['Create or open a study plan.', 'Start a timed or untimed session.', 'Complete planned flashcard, quiz, or reading work.', 'Record completion and review durable session history.']),
    guidePage(study, 'study-studio', 'AI Studio', '/studio', 'Create human-reviewed drafts from authorized sources with honest provider state.', ['Choose subject, source excerpts, output type, and learning goal.', 'Review provider and usage readiness.', 'Generate a bounded flashcard, quiz, or plan draft with citations.', 'Verify cited excerpts, edit the draft, and publish only after review.']),
    guidePage(study, 'study-progress', 'Progress and exports', '/progress', 'Review scores, recall, sessions, activity, and authorized portable exports.', ['Filter personal progress by set, subject, or date.', 'Review quiz score, flashcard recall, plan, and session trends.', 'Generate a supported export.', 'Download only authorized learner or manager scope.']),
    guidePage(study, 'study-settings', 'Settings', '/settings', 'Manage learning preferences and review OperatorOS-owned plan and usage state.', ['Set allowed study preferences.', 'Review organization, role, entitlement, provider, and usage posture.', 'Open OperatorOS for account, membership, billing, or tool access.']),
  ],
};

export const DEPLOY_OPS_GUIDE: HelpGuide = {
  id: 'ninja-launch-kit', name: 'Deploy Ops', kind: 'companion-application', accent: '#67e8f9',
  description: 'Release packages, templates, configuration, artifacts, approvals, readiness evidence, rollback planning, and exports.',
  availability: 'Active module; records release evidence but does not claim provider deployment', startHref: `${deploy}/dashboard`,
  pages: [
    guidePage(deploy, 'deploy-dashboard', 'Dashboard', '/dashboard', 'See release packages, generation usage, exports, approvals, tasks, and readiness evidence.', ['If the workspace is empty, choose a template, answer the brief once, and review the generated package.', 'Follow the Launch Readiness Brief for overdue gates, unfinished packages, missing exports, and unlaunched workspaces.', 'Use the primary action to cross from package creation into the owning readiness route.', 'Keep source/local evidence separate from provider and live acceptance.']),
    guidePage(deploy, 'deploy-releases', 'Releases and packages', '/projects', 'Create and reopen tenant-scoped release packages.', ['Create a release package with product, environment intent, and target identity.', 'Review phases, milestones, tasks, dependencies, status, and evidence.', 'Open durable package detail after refresh.', 'Do not mark provider deployment successful without recorded external evidence.']),
    guidePage(deploy, 'deploy-templates', 'Templates', '/templates', 'Choose from the reviewed template catalog without leaking locked prefills.', ['Search and filter templates.', 'Preview allowed template purpose and fields.', 'Create a release from a template.', 'Review all copied configuration before use.']),
    guidePage(deploy, 'deploy-configuration', 'Configuration and release brief', '/brief', 'Define audience, environment intent, rollout notes, and reusable release direction.', ['Edit allowed release brief fields.', 'Record environment, audience, dependencies, risk, communication, and rollout direction.', 'Use provider-aware AI drafting only when enabled.', 'Submit generated material for human review.']),
    guidePage(deploy, 'deploy-artifacts', 'Artifacts', '/deliverables', 'Review stored deliverables, communications, evidence, and release briefs.', ['Create or upload an approved artifact.', 'Link it to the correct release, phase, or task.', 'Review validation, scan, checksum, version, and approval state.', 'Keep secrets and customer data out of release artifacts.']),
    guidePage(deploy, 'deploy-readiness', 'Readiness and approvals', '/review', 'Manage tasks, evidence, approvals, rollback notes, and release proof.', ['Review completeness and blocking tasks.', 'Record source/local, CI, database, provider, DNS, and live evidence separately.', 'Approve or reject through authorized review.', 'Require rollback notes and exact release identity before promotion.', 'Keep readiness blocked when a required gate is unproven.']),
    guidePage(deploy, 'deploy-exports', 'Export history', '/exports', 'Download authorized formats with durable checksum evidence.', ['Choose a release and export format.', 'Generate an export snapshot.', 'Review status, checksum, and included evidence.', 'Download the artifact and preserve its release association.']),
    guidePage(deploy, 'deploy-settings', 'Settings', '/settings', 'Review plan limits, administration, and safe provider configuration.', ['Confirm organization, role, entitlement, and usage.', 'Review provider and attachment readiness.', 'Set allowed release-workspace preferences.', 'Open OperatorOS for identity, membership, billing, or module access.']),
  ],
};

export const CALLCOMMAND_GUIDE: HelpGuide = {
  id: 'callcommand-ai', name: 'CallCommand AI', kind: 'companion-application', accent: '#5eead4',
  description: 'Secure MSP phone intake, call records, consent-bound media, analysis, ticket-first actions, providers, associations, and assurance.',
  availability: 'Active source/local module; live Twilio and BMS workflows require approved provider onboarding', startHref: `${call}/`,
  pages: [
    guidePage(call, 'call-switchboard', 'Switchboard', '/', 'Monitor call posture and operator-controlled sessions without overstating provider availability.', ['If setup is incomplete, follow the Receptionist Readiness Brief in its ranked order.', 'Use the guided setup for number choice, receptionist, workflow, simulator, and provider health.', 'Review manual reconciliation and urgent caller follow-up before routine activity.', 'Start only explicit test or approved provider flows; provider purchase and go-live remain confirmed actions.']),
    guidePage(call, 'call-calls', 'Calls', '/calls', 'Review durable call records, outcomes, provenance, and validated report artifacts.', ['Search and filter calls by status, channel, organization, or date.', 'Open call detail and event history.', 'Review purpose, consent, assurance, provider, disposition, and linked work.', 'Use test adapters only when clearly labeled.']),
    guidePage(call, 'call-recordings', 'Recordings', '/recordings', 'Review media availability under consent, provider, retention, and access controls.', ['Filter recording records.', 'Confirm consent and provider state before playback.', 'Review retention and access context.', 'Keep disabled or missing media honest rather than fabricating playback.']),
    guidePage(call, 'call-transcripts', 'Transcripts', '/transcripts', 'Review persisted transcripts without treating generated analysis as provider fact.', ['Open a consent-authorized transcript.', 'Review source, timestamps, processing state, and redaction.', 'Request supported processing when configured.', 'Keep transcript and analysis provenance separate.']),
    guidePage(call, 'call-analysis', 'Analysis', '/analysis', 'Inspect summaries, sentiment, priority, extracted fields, and deterministic flow results.', ['Select a persisted transcript/call.', 'Review provider or deterministic analysis provenance.', 'Validate extracted issue, urgency, identity, and routing fields.', 'Accept only bounded suggestions into a human-reviewed action.']),
    guidePage(call, 'call-actions', 'Actions', '/actions', 'Review idempotent ticket, lead, task, case, and allowlisted action outcomes.', ['Inspect queued, completed, failed, or suppressed actions.', 'Confirm organization and association assurance before execution.', 'Retry only through the documented idempotent path.', 'Keep prohibited account, credential, destructive, or unsupported automation blocked.']),
    guidePage(call, 'call-automations', 'Automations', '/automations', 'Manage receptionist profiles, versioned flows, channels, and allowlisted automation rules.', ['Create or edit a receptionist profile.', 'Build and validate a bounded flow version.', 'Configure business hours, routing, consent, and allowed actions.', 'Review and activate only an approved version.', 'Use kill switches when provider or policy trust changes.']),
    guidePage(call, 'call-numbers', 'Numbers and channels', '/numbers', 'Configure channels, business hours, consent behavior, and transfer targets.', ['Register an approved phone number or channel.', 'Set exact inbound purpose and organization routing.', 'Maintain bounded transfer targets.', 'Review signed webhook readiness and channel state.'], { access: 'Organization administrator, owner, or platform administrator.' }),
    guidePage(call, 'call-providers', 'Providers', '/providers', 'Review telephony and MSP adapters, schema fingerprints, health reasons, and kill switches.', ['Configure secret references and public callback metadata separately.', 'Verify exact webhook signatures and destination routing.', 'Test the approved adapter path.', 'Review health, error, last event, and kill-switch state.', 'Never expose raw credentials in browser configuration.'], { access: 'Organization administrator, owner, or platform administrator.' }),
    guidePage(call, 'call-organizations', 'Organizations and support contacts', '/organizations', 'Manage Directory-backed support profiles, trusted lines, contacts, and rotatable SupportLinks.', ['Select a shared Directory organization.', 'Create or update the bounded support profile.', 'Associate trusted phone lines and support contacts.', 'Issue, rotate, revoke, and review SupportLinks.', 'Keep unrecognized callers at the no-automation assurance level.']),
    guidePage(call, 'call-compliance', 'Compliance and call evidence', '/compliance', 'Review consent, prohibited actions, assurance levels, hash-linked audit, and onboarding gates.', ['Inspect consent and suppression state.', 'Review policy and action catalog.', 'Trace hash-linked intake, association, case, action, and provider evidence.', 'Use onboarding checks and kill switches to keep unsafe automation disabled.']),
    guidePage(call, 'call-settings', 'Settings', '/settings', 'Keep ticket-first automation and incident-mode controls under OperatorOS authority.', ['Review organization, role, entitlement, provider, and incident posture.', 'Set allowed module defaults.', 'Enable or disable bounded incident behavior.', 'Open OperatorOS for account, membership, billing, or module access.']),
  ],
};

export const SCRIPT_OPS_GUIDE: HelpGuide = {
  id: 'ninjamation', name: 'Script Ops', kind: 'companion-application', accent: '#7dd3fc',
  description: 'Reviewed defensive script catalog, immutable versions, pinned-source synchronization, AI drafts, approval, and audited downloads.',
  availability: 'Active module; web, API, and server-side script execution is prohibited', startHref: `${script}/library`,
  pages: [
    guidePage(script, 'script-dashboard', 'Dashboard', '/dashboard', 'See reviewed scripts, catalog provenance, drafting, synchronization, downloads, and usage posture.', ['If the workspace is empty, search the pinned library before authoring a new script.', 'Follow the Script Delivery Brief for critical findings, approval work, failed sync, and approved-version gaps.', 'Use guarded drafting only when the library has no suitable reviewed source.', 'Keep approval human-controlled and execution outside OperatorOS.']),
    guidePage(script, 'script-library', 'Script library', '/library', 'Search, inspect, favorite, and download approved immutable script versions.', ['Search and filter by platform, category, tag, approval, or risk.', 'Open script detail and review source, description, prerequisites, findings, checksum, and version.', 'Favorite allowed entries.', 'Download only the currently approved version and inspect it before use.'], { notes: ['Script Ops delivers reviewed source. It never executes scripts in the browser, web server, or API process.'] }),
    guidePage(script, 'script-sources', 'Sources and synchronization', '/sources', 'Synchronize only the allowlisted catalog and preserve commit, blob, checksum, and retry evidence.', ['Review source allowlist and pinned identity.', 'Start an authorized synchronization.', 'Inspect created, updated, skipped, rejected, and failed results.', 'Review immutable provenance and retry only supported failed work.'], { access: 'Synchronization controls require an authorized administrator.' }),
    guidePage(script, 'script-ai', 'AI drafting', '/generate', 'Create unapproved defensive drafts with provider, safety, usage, and hash provenance.', ['Describe the defensive task, target platform, inputs, safety, validation, and rollback.', 'Review provider and usage readiness.', 'Generate one inert draft.', 'Inspect static analysis and provenance.', 'Edit and submit for review; never execute from this page.']),
    guidePage(script, 'script-review', 'Review queue', '/review', 'Submit, approve, reject, or retire scripts without executing source.', ['Open a pending version and review code, provenance, findings, documentation, and checksum.', 'Require critical findings to be resolved.', 'Approve, reject, request revision, or retire through an authorized decision.', 'Confirm the immutable approved-version pointer and audit event.'], { access: 'Approval decisions require an organization administrator, owner, or platform administrator.' }),
    guidePage(script, 'script-downloads', 'Download audit', '/runs', 'Review durable download evidence while execution remains prohibited.', ['Filter by script, version, user, or date.', 'Review approved version, checksum, actor, and request context.', 'Download again only from the current authorized version.', 'Use the record for delivery evidence, not execution status.']),
    guidePage(script, 'script-versions', 'Versions', '/versions', 'Inspect script version, synchronization, checksum, approval, and safety history.', ['Open version history for a script.', 'Compare immutable metadata and findings.', 'Review which version is current and approved.', 'Do not overwrite an approved version; create a new draft.']),
    guidePage(script, 'script-settings', 'Settings', '/settings', 'Review account, plan usage, administration, and shared synchronization policy.', ['Confirm organization, role, entitlement, AI usage, and provider posture.', 'Review source allowlist and approval policy.', 'Open OperatorOS for identity, membership, billing, or module access.']),
    guidePage(script, 'script-admin', 'Administration', '/admin', 'Create inert drafts and manage synchronization policy without executing imported source.', ['Create a draft record from authorized source or manual input.', 'Review catalog source policy and synchronization state.', 'Manage allowed administrative settings.', 'Keep runtime execution disabled.'], { access: 'Organization administrator, owner, or platform administrator.' }),
  ],
};

export const OUTCALL_GUIDE: HelpGuide = {
  id: 'outcall', name: 'OutCall', kind: 'companion-application', accent: '#c4b5fd',
  description: 'Discreet exit assistance using one verified self-owned destination, private triggers, bounded calls, history, privacy, and safety controls.',
  availability: 'Coming soon in the public catalog; source/local workflows require verified provider onboarding', startHref: `${outcall}/`,
  pages: [
    guidePage(outcall, 'outcall-overview', 'OutCall overview', '/', 'Check safety acknowledgement, verified destination, rescue profile, schedule, and provider readiness.', ['Review whether the safety acknowledgement is current.', 'Confirm one verified self-owned destination.', 'Review neutral assistance profile and provider state.', 'Open schedules, triggers, calls, or privacy controls.'], { notes: ['OutCall is not an emergency service, monitoring service, or substitute for contacting local emergency services.'] }),
    guidePage(outcall, 'outcall-contacts', 'Verified destination and rescue profiles', '/contacts', 'Configure neutral assistance messages without an arbitrary-recipient or bulk contact list.', ['Create or edit a neutral rescue profile.', 'Select only the independently verified self-owned destination.', 'Review script, caller ID, keypad, and privacy boundaries.', 'Keep arbitrary contacts and bulk audiences unsupported.']),
    guidePage(outcall, 'outcall-schedules', 'Schedules', '/schedules', 'Request an immediate or future call only to the verified destination.', ['Choose profile, timing, and bounded context.', 'Review verification, provider, rate-limit, and safety readiness.', 'Create the schedule once.', 'Cancel before provider attempt when allowed.', 'Review authoritative request and delivery state.']),
    guidePage(outcall, 'outcall-triggers', 'Private triggers', '/campaigns', 'Configure exact-match private SMS phrases for one bounded assistance call.', ['Create a private trigger phrase.', 'Link the allowed verified destination and rescue profile.', 'Review activation, replay, rate-limit, and masking controls.', 'Disable or rotate a compromised phrase.', 'Keep bulk campaigns intentionally unsupported.']),
    guidePage(outcall, 'outcall-calls', 'Calls', '/calls', 'Review requested, scheduled, attempted, provider-confirmed, failed, or canceled call records.', ['Filter and open call requests.', 'Review exact destination masking, profile, trigger, provider, and status history.', 'Cancel eligible future work.', 'Treat unknown provider state as unknown, not success.']),
    guidePage(outcall, 'outcall-reminders', 'Reminders', '/reminders', 'Schedule a future exit-assistance call without recurring marketing or audience targeting.', ['Choose the verified destination and neutral profile.', 'Set one future time.', 'Review provider and verification readiness.', 'Cancel or inspect the resulting schedule.']),
    guidePage(outcall, 'outcall-verification', 'Verification', '/verification', 'Independently confirm the only mobile number OutCall may call.', ['Enter the self-owned mobile number.', 'Request a bounded provider verification code.', 'Submit the code within its validity window.', 'Review verified, expired, failed, or rate-limited state.', 'Reverify after a destination change.']),
    guidePage(outcall, 'outcall-delivery', 'Delivery readiness', '/delivery', 'Distinguish configured request handling from provider-confirmed call delivery.', ['Review provider, callback signature, public URL, rate limit, and destination verification posture.', 'Run only the allowed test path.', 'Inspect last request, callback, error, and delivery evidence.', 'Keep live actions disabled until every required check is ready.']),
    guidePage(outcall, 'outcall-history', 'History', '/history', 'Review durable call requests and outcomes.', ['Filter by date, status, profile, or trigger.', 'Open masked request and provider event history.', 'Confirm cancel, attempt, answer, DTMF, delivery, or failure evidence.', 'Export only through the privacy page.']),
    guidePage(outcall, 'outcall-compliance', 'Privacy and safety', '/compliance', 'Export or delete private data and review the explicit non-emergency boundary.', ['Review stored profiles, triggers, schedules, calls, and provider evidence.', 'Generate an authorized privacy export.', 'Delete private OutCall data only after reauthentication and dependency checks.', 'Review masking, retention, consent, and emergency disclaimers.']),
    guidePage(outcall, 'outcall-settings', 'Settings', '/settings', 'Review readiness and safety limits under OperatorOS identity and entitlement authority.', ['Confirm organization, role, entitlement, verification, and provider state.', 'Review safety acknowledgement and allowed defaults.', 'Open OperatorOS for identity, membership, billing, or module access.']),
  ],
};

export const COMPANION_MODULE_GUIDES = [
  FAULTLINELAB_GUIDE,
  POOL_HALL_GUIDE,
  BRANDFORGE_GUIDE,
  SNAPPROOF_GUIDE,
  STUDYFORGE_GUIDE,
  DEPLOY_OPS_GUIDE,
  CALLCOMMAND_GUIDE,
  SCRIPT_OPS_GUIDE,
  OUTCALL_GUIDE,
] as const;
