/** Short explanations of product terms; these never imply execution or access. */
export const MODULE_GLOSSARY: Record<string, readonly [string, string][]> = {
  operatoros: [['Organization', 'The team or business whose records you are working with.'], ['App access', 'The apps and actions your account is allowed to use.'], ['Add-on', 'An extra paid feature or app on your plan.']],
  tradeflowkit: [['Lead', 'A person or business that may become a customer.'], ['Quote', 'A price you offer before the customer agrees to the work.'], ['Invoice', 'A request for payment. Creating an invoice does not mean it has been paid.']],
  techdeck: [['SLA', 'The response and resolution targets agreed for support work.'], ['IPAM', 'Your inventory of network addresses and subnets.'], ['Runbook', 'A reviewed set of steps a technician can follow. Saving it does not run it.']],
  pulsedesk: [['Escalation', 'Asking the responsible team or manager to address work that needs more attention.'], ['Queue', 'A list of requests waiting for a team to handle.'], ['Response target', 'When the team is expected to respond to a request.']],
  torqueshed: [['Diagnostic', 'A record of the problem, tests, findings, and repair decisions.'], ['Live Bay', 'A shared space where technicians work through a diagnosis.'], ['Proof of fix', 'The recorded test or observation showing whether the repair worked.']],
  faultlinelab: [['Evidence', 'A clue or test result you use to work out the cause.'], ['Hypothesis', 'A possible cause to test before choosing a repair.'], ['Debrief', 'Feedback on your investigation after you finish the challenge.']],
  'ninja-pool-hall': [['Rack', 'One game, starting with the balls arranged on the table.'], ['Hot-seat', 'Two people taking turns on the same device.'], ['CPU opponent', 'The computer player.']],
  brandforgeos: [['Brand kit', 'Your saved business name, colors, style, and voice.'], ['Audience profile', 'A description of the people you want to reach.'], ['Campaign', 'A group of related marketing content and tasks with one goal.']],
  snapproofos: [['Evidence', 'Photos, files, and notes that support what you report.'], ['Chain of custody', 'The recorded history of how a file was collected, accessed, and reviewed.'], ['Retention', 'How long records must be kept before they can be archived or removed.']],
  'studyforge-ai': [['Study set', 'Related notes, cards, and questions for one topic.'], ['Recall', 'Remembering an answer without looking at the source.'], ['AI draft', 'Suggested study material you should check against your sources before using.']],
  'ninja-launch-kit': [['Launch package', 'Prepared campaign content, design instructions, and tasks for your team to review.'], ['Visual brief', 'Instructions for making an image or design. It is not a finished image.'], ['Approval', 'A recorded review decision. Approval does not publish the campaign.']],
  'callcommand-ai': [['Intake', 'Collecting the caller’s reason for calling and the details needed to follow up.'], ['Disposition', 'The outcome you record for a call.'], ['Simulation', 'A practice call flow. It does not prove live phone service is connected.']],
  ninjamation: [['Revision', 'A saved version of a script.'], ['Approval', 'A reviewer’s decision that a particular version may be used.'], ['Download', 'Getting the script file. Downloading it does not run it on a device.']],
  outcall: [['Verified number', 'Your own phone number after completing the ownership check.'], ['Trigger phrase', 'A private phrase used to request a call when the service is available.']],
};
