import { guidePage } from './page';
import type { HelpGuide } from './types';

const tfk = 'https://tradeflowkit.operatoros.net';
const pulse = 'https://pulsedesk.operatoros.net';
const tech = 'https://techdeck.operatoros.net';
const torque = 'https://torqueshed.operatoros.net';

export const TRADEFLOWKIT_GUIDE: HelpGuide = {
  id: 'tradeflowkit', name: 'TradeFlowKit', kind: 'main-module', accent: '#f97316',
  description: 'Lead-to-cash, work management, customer records, business payments, directory, and operating analytics.',
  availability: 'Active module; provider-backed payment delivery remains configuration-dependent', startHref: `${tfk}/dashboard`,
  pages: [
    guidePage(tfk, 'tfk-dashboard', 'Dashboard', '/dashboard', 'See lead, work, revenue, collection, and task posture and search the entire tenant workspace.', ['Use global search across customers, jobs, tasks, quotes, and invoices.', 'Review persisted operating metrics and attention items.', 'Jump to leads, customers, jobs, workflows, tasks, recurring work, revenue documents, payments, analytics, or Directory.', 'Toggle the module theme without changing stored business data.']),
    guidePage(tfk, 'tfk-leads', 'Leads', '/leads', 'Capture, qualify, follow up, message, bulk-manage, and convert service opportunities.', ['Create and edit a consent-aware lead.', 'Filter, save views, select bounded batches, and apply safe bulk updates.', 'Queue provider-gated email or SMS follow-up with authoritative destination evidence.', 'Convert a qualified lead into linked customer and numbered job records.', 'Archive retained leads without deleting linked business history.']),
    guidePage(tfk, 'tfk-customers', 'Customers', '/customers', 'Manage customer profiles and follow their related jobs, quotes, invoices, payments, and activity.', ['Create, search, open, and edit customer records.', 'Review linked service and revenue history.', 'Use Directory relationships without duplicating shared organization identity.', 'Archive only when dependency rules allow; restore retained records from Trash.']),
    guidePage(tfk, 'tfk-jobs', 'Jobs', '/jobs', 'Schedule and progress customer work while coordinating tasks, workflow stage, and persistence.', ['Create and edit a numbered customer job.', 'Assign workflow stages, dates, ownership, status, and service context.', 'Create, update, order, and complete job-scoped tasks.', 'Open durable job detail links and verify changes after refresh.', 'Archive in dependency order without silently deleting shared customer records.']),
    guidePage(tfk, 'tfk-quotes', 'Quotes', '/quotes', 'Prepare customer quotes and move them through an auditable delivery and response lifecycle.', ['Create a draft quote with customer and line items.', 'Edit safe draft fields and totals.', 'Issue or send through configured delivery, then track response state.', 'Open the secure customer document when a share token exists.', 'Convert approved work into the supported downstream invoice flow.']),
    guidePage(tfk, 'tfk-invoices', 'Invoices', '/invoices', 'Issue invoices, monitor balances, share customer documents, and retain authoritative payment history.', ['Create an invoice directly or from approved business context.', 'Edit allowed draft fields and line items.', 'Issue and share an immutable customer-facing snapshot.', 'Review balance, payment, refund, and settlement history.', 'Refuse history-destructive changes once financial state is authoritative.']),
    guidePage(tfk, 'tfk-workflows', 'Workflows', '/workflows', 'Define reusable job and task stages and apply them to active work.', ['Create and edit a tenant-scoped workflow.', 'Add, order, and update stages.', 'Assign a workflow to jobs and move work through allowed stages.', 'Preserve optimistic versions and audit history during concurrent edits.']),
    guidePage(tfk, 'tfk-tasks', 'Team tasks', '/tasks', 'Search and manage organization-wide job tasks without losing their customer and job context.', ['Filter by owner, job, status, priority, due date, or search text.', 'Open the parent job from a task result.', 'Create or edit allowed task fields.', 'Complete, reopen, reorder, or archive tasks with version checks.']),
    guidePage(tfk, 'tfk-recurring', 'Recurring jobs', '/recurring-jobs', 'Create and monitor repeat work handled by the shared audited scheduler.', ['Create a recurrence with bounded interval and job context.', 'Pause or resume future enqueueing.', 'Review last and next run state.', 'Confirm idempotent scheduler outcomes rather than assuming a background run succeeded.']),
    guidePage(tfk, 'tfk-activity', 'Activity', '/activity', 'Review tenant-scoped operational changes across work management and revenue flows.', ['Filter recent job, task, recurrence, workflow, lead, and document events.', 'Inspect actor, action, target, time, and safe context.', 'Use activity to confirm a mutation without treating it as a substitute for provider settlement evidence.']),
    guidePage(tfk, 'tfk-payments', 'Payments', '/payments', 'Review customer invoice balances and record business payments separately from OperatorOS subscription billing.', ['Filter unpaid, partial, paid, failed, or refunded business documents.', 'Record an approved manual payment with reference and amount.', 'Use configured Stripe Connect flows only when onboarding and webhook state are ready.', 'Review settlement, replay, refund, and failure evidence.'], { notes: ['This page handles business customer payments. OperatorOS plan and add-on billing stays in the OperatorOS console.'] }),
    guidePage(tfk, 'tfk-analytics', 'Analytics', '/analytics', 'Understand performance from persisted lead, work, task, invoice, and collection records.', ['Review lead funnel, job posture, task pressure, invoiced totals, collections, and outstanding balance.', 'Change bounded date or status filters.', 'Follow a metric back to the owning record list instead of treating it as a static counter.']),
    guidePage(tfk, 'tfk-directory', 'Business Directory', '/directory', 'Reuse organizations, contacts, and sites shared across tenant modules.', ['Search and maintain organization records.', 'Create and edit contacts and addressed sites.', 'Link shared records to TradeFlowKit workflow context.', 'Archive only with authorized tenant scope and dependency checks.']),
    guidePage(tfk, 'tfk-settings', 'Settings', '/settings', 'Configure TradeFlowKit operating defaults, lead intake, theme, and provider readiness under OperatorOS authority.', ['Review role, entitlement, plan, and organization context.', 'Configure supported lead intake and workflow defaults.', 'Inspect provider readiness without exposing credentials.', 'Open OperatorOS for identity, membership, subscription, or module-access changes.']),
    guidePage(tfk, 'tfk-trash', 'Trash', '/trash', 'Review and restore retained business records while preserving dependency rules.', ['List archived customers, jobs, tasks, leads, and supported documents.', 'Inspect why a record was retained or cannot be restored.', 'Restore in a safe parent-before-child order.', 'Keep permanent deletion unavailable when financial, audit, or shared identity history must remain.'], { access: 'Organization administrator, owner, or platform administrator.' }),
    guidePage(tfk, 'tfk-subscription', 'Subscription', '/subscription', 'Return to the OperatorOS-owned plan, invoice, checkout, and module-access controls.', ['Open Workspace plan or organization billing.', 'Review current TradeFlowKit entitlement.', 'Start supported subscription changes in OperatorOS only.']),
    guidePage(tfk, 'tfk-call-recovery', 'Call recovery', '/call-recovery', 'Continue an eligible missed-call recovery workflow through the OutCall companion application.', ['Review whether OutCall is enabled for the organization.', 'Keep lead qualification and conversion inside TradeFlowKit.', 'Use only verified-self, provider-ready OutCall workflows.']),
    guidePage(tfk, 'tfk-admin', 'Administration', '/admin', 'Open the authoritative OperatorOS controls for membership, access, and commercial state.', ['Manage organization members in OperatorOS.', 'Review module entitlement and plan state.', 'Avoid creating a second TradeFlowKit identity, role, or billing authority.'], { access: 'Organization administrator, owner, or platform administrator.' }),
  ],
};

export const PULSEDESK_GUIDE: HelpGuide = {
  id: 'pulsedesk', name: 'PulseDesk', kind: 'main-module', accent: '#38bdf8',
  description: 'Healthcare operations coordination for requests, assignments, facilities, equipment, supplies, knowledge, and inbound communication.',
  availability: 'Active module; PHI-minimized operations boundary and provider gates apply', startHref: `${pulse}/dashboard`,
  pages: [
    guidePage(pulse, 'pulse-overview', 'Operations overview', '/', 'See operational request pressure, SLA posture, assignments, equipment, supply, and facility work.', ['Review open, urgent, overdue, unassigned, and recently changed work.', 'See equipment, supply, facility, connector, and time posture.', 'Open the request queue or focused operations page from a metric.'], { notes: ['PulseDesk coordinates operations. Do not store patient charts, clinical records, or unnecessary PHI.'] }),
    guidePage(pulse, 'pulse-requests', 'Requests and work queues', '/requests', 'Triage and resolve PHI-minimized operational requests with durable SLA and communication history.', ['Create a request or open an approved public-intake result.', 'Filter by queue, priority, status, assignee, facility, or search.', 'Assign, respond, add private operational notes, record time, and progress status.', 'Review SLA targets, messages, attachments, and activity on request detail.', 'Close or reopen with version-aware server authorization.']),
    guidePage(pulse, 'pulse-assignments', 'Assignments and escalation', '/assignments', 'Route work to authorized departments, queues, teams, and members and manage escalation posture.', ['Review unassigned and escalated work.', 'Create or maintain department and queue definitions.', 'Assign requests to an allowed member or team.', 'Apply SLA policies and track escalation events.', 'Use administrator controls without widening OperatorOS roles.'], { access: 'Read access is role-based; queue, assignment, and policy changes require organization administration.' }),
    guidePage(pulse, 'pulse-contacts', 'Facilities and contacts', '/contacts', 'Maintain shared service clients, facilities, contacts, and vendors used by operational work.', ['Search shared Directory organizations, contacts, and sites.', 'Create or edit facility and service contact context.', 'Maintain vendor relationships for operational fulfillment.', 'Open linked requests, equipment, or facility work.', 'Avoid clinical demographics and patient records.']),
    guidePage(pulse, 'pulse-operations', 'Equipment, supplies, and facilities', '/operations', 'Coordinate operational assets, restock needs, and physical-facility requests.', ['Register and review equipment without storing patient data.', 'Report an equipment issue and link it to a request.', 'Create, prioritize, fulfill, or close supply requests.', 'Track facility requests and vendor context.', 'Use status and activity evidence to confirm progress.']),
    guidePage(pulse, 'pulse-inbound', 'Inbound communication', '/inbound', 'Review authorized mailbox and email-to-request delivery state.', ['Inspect configured inbound channel readiness.', 'Review accepted, duplicate, rejected, or failed messages.', 'Open the resulting operational request when one was created.', 'Use message identifiers and safe error codes for troubleshooting without exposing credentials.']),
    guidePage(pulse, 'pulse-analytics', 'Analytics', '/analytics', 'Review demand, SLA pressure, assignment, equipment, supply, facility, and time posture from persisted records.', ['Filter the reporting window and operational dimensions.', 'Review request volume, response, resolution, overdue, and workload trends.', 'Inspect equipment, supply, facility, and time summaries.', 'Follow a result to the owning operational list.']),
    guidePage(pulse, 'pulse-knowledge', 'Knowledge', '/knowledge', 'Maintain requester guidance and internal service procedures within the operational-data boundary.', ['Create, edit, search, and organize knowledge entries.', 'Separate requester-safe guidance from internal procedures.', 'Review and publish approved content.', 'Link relevant guidance to recurring operational issues.']),
    guidePage(pulse, 'pulse-integrations', 'Integrations', '/integrations', 'Configure organization-scoped email connectors and verify fail-closed provider state.', ['Create a connector using encrypted credential references.', 'Test an authorized connector with bounded non-PHI content.', 'Review ingest, duplicate, health, and last-error state.', 'Disable or revoke a connector immediately when trust changes.'], { access: 'Organization administrator, owner, or platform administrator.', notes: ['A configured connector is not considered healthy until its verification result succeeds.'] }),
    guidePage(pulse, 'pulse-settings', 'Settings', '/settings', 'Manage queues, SLA policies, notification preferences, access, and the healthcare operational-data boundary.', ['Review OperatorOS-owned organization, membership, role, and entitlement context.', 'Maintain allowed queue and SLA settings.', 'Configure notification preferences.', 'Review privacy guidance and provider readiness.', 'Open OperatorOS for subscription or identity changes.'], { access: 'Some configuration controls require organization administration.' }),
  ],
};

export const TECHDECK_GUIDE: HelpGuide = {
  id: 'techdeck', name: 'TechDeck', kind: 'main-module', accent: '#22d3ee',
  description: 'Engineer-first MSP operations for tickets, infrastructure, documentation, evidence, time, trust, and integrations.',
  availability: 'Active module; command execution is intentionally outside the web product boundary', startHref: `${tech}/`,
  pages: [
    guidePage(tech, 'tech-overview', 'Operations overview', '/', 'Prioritize service work, managed systems, lifecycle risk, evidence, and trust operations.', ['Review ticket pressure, asset health, lifecycle dates, evidence, time, and integration posture.', 'Open tickets, clients, assets, network, or knowledge from focused shortcuts.', 'Confirm current organization and access before editing managed records.']),
    guidePage(tech, 'tech-tickets', 'Tickets', '/tickets', 'Triage, assign, progress, and close tenant-scoped support work with SLA context.', ['Create, search, filter, and open tickets.', 'Set client, site, priority, status, queue, assignee, and SLA context.', 'Add authorized replies, internal notes, attachments, and time entries.', 'Review activity and linked configuration items.', 'Resolve or reopen through version-aware mutations.']),
    guidePage(tech, 'tech-clients', 'Clients', '/clients', 'Manage shared client, site, contact, and service context used by TechDeck.', ['Search Directory organizations, sites, and contacts.', 'Create or edit allowed shared records.', 'Open related tickets, assets, network records, and time.', 'Preserve cross-module identity instead of cloning client records.']),
    guidePage(tech, 'tech-assets', 'Assets', '/assets', 'Register managed configuration items and keep technical and health context current.', ['Create and classify tenant-scoped assets.', 'Link client, site, owner, identifiers, and lifecycle data.', 'Record health, alert, relationship, and technical context.', 'Open related evidence, tickets, network records, and documentation.', 'Archive with dependency checks.']),
    guidePage(tech, 'tech-network', 'Network / IPAM', '/network', 'Map firewalls, switches, addresses, subnets, VLANs, and their relationships.', ['Create typed network devices and relationships.', 'Maintain subnets, VLANs, IP addresses, and assignments.', 'Search by client, site, type, or address context.', 'Link network evidence and affected tickets.', 'Prevent cross-tenant enumeration and conflicting assignments.']),
    guidePage(tech, 'tech-lifecycle', 'Lifecycle', '/lifecycle', 'Review warranty, renewal, expiration, incomplete-record, and health pressure.', ['Filter upcoming or overdue lifecycle dates.', 'Review warranty, license, certificate, renewal, and end-of-life posture.', 'Open the owning asset or client record.', 'Use the view for planning; confirm changes on the source record.']),
    guidePage(tech, 'tech-documentation', 'Documentation', '/documentation', 'Create versioned, reviewable technical knowledge for managed environments.', ['Create, search, edit, and categorize documentation.', 'Link documents to clients, sites, assets, and tickets.', 'Review version history and approval state.', 'Use bounded attachments without storing raw credentials.']),
    guidePage(tech, 'tech-runbooks', 'Runbooks', '/runbooks', 'Maintain approval-controlled documentation-only procedures.', ['Create and version a procedure.', 'Record prerequisites, steps, rollback, and validation guidance.', 'Submit or approve through authorized review.', 'Download or consult approved instructions.', 'Keep arbitrary command execution outside TechDeck.'], { notes: ['Runbooks document procedures. TechDeck does not execute arbitrary scripts or commands.'] }),
    guidePage(tech, 'tech-evidence', 'Evidence', '/evidence', 'Capture observations, snapshots, tests, and attachments against managed systems.', ['Create an evidence record with source and observation context.', 'Attach a validated private file when enabled.', 'Link evidence to client, site, asset, ticket, or report.', 'Review checksum, scan, access, and activity state.']),
    guidePage(tech, 'tech-reports', 'Reports', '/reports', 'Generate checksummed infrastructure, lifecycle, ticket, evidence, and time snapshots.', ['Choose report scope and date range.', 'Generate a snapshot from persistent records.', 'Review checksum, status, and included sections.', 'Download an authorized artifact and keep it tied to the report record.']),
    guidePage(tech, 'tech-time', 'Time', '/time', 'Record technician work against the correct client, ticket, site, or configuration item.', ['Create and edit allowed time entries.', 'Link time to a service context.', 'Filter by technician, client, ticket, billable state, or date.', 'Confirm totals from persisted entries.']),
    guidePage(tech, 'tech-calendar', 'Calendar', '/calendar', 'Schedule appointments and manage recurring service-ticket rules.', ['Create and update service appointments.', 'Associate work with clients, sites, tickets, and members.', 'Create bounded recurring-ticket rules.', 'Pause, resume, and review scheduler outcomes.']),
    guidePage(tech, 'tech-portal', 'Client portal', '/portal', 'Control client and site visibility for authorized ticket and evidence collaboration.', ['Review portal access and visibility policy.', 'Select which tickets or evidence may be exposed.', 'Inspect portal activity and authorization state.', 'Keep internal notes and unrestricted tenant data private.']),
    guidePage(tech, 'tech-licenses', 'Licensing', '/licenses', 'Issue, validate, revoke, and audit product licenses without exposing raw keys after creation.', ['Create a license for an approved product and customer.', 'Copy the raw key only at the one permitted creation moment.', 'Validate status through the supported interface.', 'Revoke, expire, or inspect usage and audit state.'], { access: 'License management requires an authorized administrative role.' }),
    guidePage(tech, 'tech-status', 'Status', '/status', 'Maintain service components, incidents, updates, and public history.', ['Create and update service components.', 'Open, update, resolve, and publish incidents.', 'Review public status-page history.', 'Keep internal evidence and secrets out of public incident text.']),
    guidePage(tech, 'tech-compliance', 'Compliance', '/compliance', 'Collect evidence safely and produce deterministic integrity packets.', ['Create secure intake or compliance scope.', 'Review received evidence and validation state.', 'Generate a deterministic packet with integrity metadata.', 'Export only authorized customer-safe content.']),
    guidePage(tech, 'tech-webhooks', 'Webhooks', '/webhooks', 'Manage bounded signed outbound integration delivery.', ['Create an approved HTTPS endpoint and event scope.', 'Rotate or revoke signing configuration safely.', 'Review delivery, retry, response, and dead-letter history.', 'Retry idempotently without exposing the signing secret.'], { access: 'Organization administrator, owner, or platform administrator.' }),
    guidePage(tech, 'tech-api-tokens', 'API tokens', '/api-tokens', 'Issue revocable, scoped headless identities while keeping OperatorOS authority intact.', ['Create a token with the minimum needed scope and expiry.', 'Copy the raw value only at creation.', 'Review last use and bounded audit state.', 'Revoke immediately when no longer needed.'], { access: 'Organization administrator, owner, or platform administrator.' }),
    guidePage(tech, 'tech-settings', 'Settings', '/settings', 'Review OperatorOS-owned access and TechDeck operating boundaries.', ['Inspect current organization, role, entitlement, and provider posture.', 'Maintain allowed module defaults.', 'Open OperatorOS for identity, membership, plan, or tool-access changes.', 'Review the no-arbitrary-execution and credential-reference boundaries.']),
  ],
};

export const TORQUESHED_GUIDE: HelpGuide = {
  id: 'torqueshed', name: 'TorqueShed', kind: 'companion-application', accent: '#f59e0b',
  description: 'Vehicle records, service history, builds, evidence-first diagnostics, live bays, marketplace, community, and portable workshop records.',
  availability: 'Active module; Torque Assist and credit purchase depend on configured providers', startHref: `${torque}/`,
  pages: [
    guidePage(torque, 'torque-overview', 'Garage overview', '/', 'See vehicles, service work, builds, diagnostics, reminders, spend, and community activity that need attention.', ['Review garage, service, diagnostic, build, live-bay, marketplace, and reminder summaries.', 'Search workshop records.', 'Start a vehicle, service, build, or diagnostic workflow.']),
    guidePage(torque, 'torque-garage', 'Garage', '/garage', 'Create and maintain durable vehicle records and their service and diagnostic history.', ['Add a vehicle with bounded identity and specification fields.', 'Search, filter, open, and edit vehicles.', 'Review linked service, build, diagnostic, cost, file, and activity history.', 'Protect private maintenance and diagnostic notes.']),
    guidePage(torque, 'torque-service', 'Service', '/service', 'Record completed maintenance and repair work, parts, vendors, costs, and reminders.', ['Create a service record for the correct vehicle.', 'Record work performed, mileage, dates, parts, vendor, cost, and notes.', 'Create or resolve maintenance reminders.', 'Review cumulative service history and spend.']),
    guidePage(torque, 'torque-builds', 'Builds', '/builds', 'Plan vehicle build stages, tasks, parts, journal evidence, and project costs.', ['Create and edit a vehicle-linked build.', 'Add, order, assign, and complete build tasks.', 'Track parts and cost entries.', 'Open build detail and journal milestones.', 'Preserve progress after refresh and reconnect.']),
    guidePage(torque, 'torque-journal', 'Journal', '/journal', 'Capture durable build notes, milestones, media, and costs.', ['Create a timestamped build entry.', 'Link a vehicle or build.', 'Attach approved media or cost context.', 'Review chronological evidence without overwriting prior history.']),
    guidePage(torque, 'torque-diagnostics', 'Diagnostics', '/diagnostics', 'Start and review evidence-first diagnostic sessions.', ['Create a session with concern, symptoms, visibility, codes, and safety context.', 'Record tests, measurements, evidence, hypotheses, findings, and confirmed fix.', 'Open durable diagnostic detail and timeline.', 'Use Torque Assist only after evidence is recorded and credit/provider state is clear.'], { notes: ['Torque Assist supports diagnostic planning. It is not a verified repair, service information, or a substitute for proper tools and qualified judgment.'] }),
    guidePage(torque, 'torque-assist', 'Torque Assist', '/diagnostics/:diagnosticId/assist', 'Use recorded evidence with reserved credits and provider-honest results.', ['Select an authorized diagnostic session.', 'Review the exact credit price and current balance.', 'Submit bounded symptoms, codes, tests, and evidence.', 'Inspect ranked hypotheses, supporting and contradicting evidence, next tests, safety warnings, and escalation guidance.', 'Confirm reservation settlement or refund state when the provider fails.'], { openPath: '/diagnostics', notes: ['Open a diagnostic first, then choose Torque Assist from that diagnostic record.'] }),
    guidePage(torque, 'torque-live-bays', 'Live Bays', '/live-bays', 'Open, reconnect to, and review collaborative diagnostic work bays.', ['Create or join an authorized bay.', 'Record shared session actions and evidence.', 'Reconnect after an interruption using persisted history.', 'Close a bay and retain the durable record.']),
    guidePage(torque, 'torque-templates', 'Templates and vendors', '/templates', 'Maintain reusable diagnostic plans and trusted service vendors.', ['Create and edit diagnostic templates.', 'Add ordered tests and evidence expectations.', 'Maintain vendor identity and service context.', 'Apply a template without replacing session-specific evidence.']),
    guidePage(torque, 'torque-marketplace', 'Marketplace', '/marketplace', 'Publish and inquire about tenant-safe parts listings.', ['Create a listing with condition, price, location, and approved media.', 'Search, filter, and open listing detail.', 'Send an inquiry without exposing private contact data publicly.', 'Close, archive, or moderate listings through authorized actions.']),
    guidePage(torque, 'torque-community', 'Community', '/community', 'Share proof-aware posts with privacy and moderation controls.', ['Create, edit, and browse posts.', 'Comment and react with like, helpful, or insightful.', 'Report content and review moderation outcomes.', 'Keep private diagnostic, vehicle, and customer data out of public posts.']),
    guidePage(torque, 'torque-credits', 'Credits and usage', '/billing/credits', 'Buy test- or live-mode credit packs when configured and review the authoritative balance and ledger.', ['Review pack price, provider mode, and current balance.', 'Start checkout only when the displayed provider state is ready.', 'Review reservations, debits, refunds, and settlement events.', 'Reconcile provider results before treating a purchase as credited.'], { notes: ['Credits are module usage capacity. OperatorOS subscription billing remains a separate platform concern.'] }),
    guidePage(torque, 'torque-activity', 'Activity', '/activity', 'Review tenant-scoped workshop changes and notifications.', ['Filter recent vehicle, service, build, diagnostic, marketplace, and community activity.', 'Open the owning record.', 'Use the event trail to confirm actions and troubleshoot conflicts.']),
    guidePage(torque, 'torque-search', 'Search', '/search', 'Find vehicles, builds, diagnostics, service work, and shared records.', ['Enter bounded search text.', 'Filter by record type or workshop context.', 'Open the canonical detail route for a result.', 'Confirm organization scope before editing.']),
    guidePage(torque, 'torque-exports', 'Exports', '/exports', 'Create and download authorized portable workshop records.', ['Choose a supported vehicle, service, build, or diagnostic scope.', 'Generate an export snapshot.', 'Review status, checksum, and included data.', 'Download only when authorization is confirmed.']),
    guidePage(torque, 'torque-settings', 'Settings', '/settings', 'Review privacy, provider readiness, defaults, and native-device authorization.', ['Review OperatorOS identity, organization, and entitlement context.', 'Configure workshop display and allowed defaults.', 'Inspect Torque Assist, Stripe, attachment, and realtime readiness.', 'Authorize or revoke a native client through the bounded device flow.']),
    guidePage(torque, 'torque-profile', 'Profile', '/profile', 'Review OperatorOS-owned player/operator identity and organization context.', ['Confirm the immutable OperatorOS subject and selected organization.', 'Review allowed public/community profile fields.', 'Open OperatorOS for account credential or membership changes.']),
  ],
};

export const PRIMARY_MODULE_GUIDES = [
  TRADEFLOWKIT_GUIDE,
  PULSEDESK_GUIDE,
  TECHDECK_GUIDE,
  TORQUESHED_GUIDE,
] as const;
