import { guidePage } from './page';
import type { HelpGuide } from './types';

const tfk = 'https://tradeflowkit.operatoros.net';
const pulse = 'https://pulsedesk.operatoros.net';
const tech = 'https://techdeck.operatoros.net';
const torque = 'https://torqueshed.operatoros.net';

export const TRADEFLOWKIT_GUIDE: HelpGuide = {
  id: 'tradeflowkit', name: 'TradeFlowKit', kind: 'main-module', accent: '#f97316',
  description: 'Lead-to-cash, work management, customer records, business payments, directory, and operating analytics.',
  availability: 'Available now. Email, SMS, and online payment delivery require the related service to be connected first.', startHref: `${tfk}/dashboard`,
  pages: [
    guidePage(tfk, 'tfk-dashboard', 'Dashboard', '/dashboard', 'See the sales, delivery, billing, and collection work that needs attention next.', ['Search customers, jobs, tasks, quotes, and invoices.', 'Review current totals and items that need action.', 'Open the right work area directly from the dashboard.', 'Change the display theme without affecting business records.']),
    guidePage(tfk, 'tfk-leads', 'Leads', '/leads', 'Capture opportunities, follow up with permission, and turn qualified leads into paying work.', ['Create and update a lead.', 'Filter leads, save useful views, and update a selected group.', 'Send email or SMS follow-up after the related service and destination are confirmed.', 'Convert a qualified lead into a customer and numbered job.', 'Archive an inactive lead without removing linked business history.']),
    guidePage(tfk, 'tfk-customers', 'Customers', '/customers', 'Keep each customer connected to their jobs, quotes, invoices, payments, and activity.', ['Create, search, open, and edit customer records.', 'Review service and revenue history.', 'Reuse existing organization, contact, and site details.', 'Archive a record when allowed and restore it from Trash when needed.']),
    guidePage(tfk, 'tfk-jobs', 'Jobs', '/jobs', 'Schedule customer work, assign the next steps, and track it through completion.', ['Create and edit a numbered customer job.', 'Set dates, owner, status, service details, and workflow stage.', 'Create, order, update, and complete job tasks.', 'Reopen the job later and confirm the latest changes.', 'Archive linked records in the order shown so customer history remains intact.']),
    guidePage(tfk, 'tfk-quotes', 'Quotes', '/quotes', 'Prepare a quote, send it to the customer, track the response, and move accepted work toward billing.', ['Create a draft quote with the customer and line items.', 'Review the details and totals.', 'Send it through a connected delivery service and track the response.', 'Open the secure customer document when sharing is available.', 'Create the invoice from approved work instead of entering it again.']),
    guidePage(tfk, 'tfk-invoices', 'Invoices', '/invoices', 'Send invoices, follow balances, share customer documents, and keep payment history complete.', ['Create an invoice directly or from approved work.', 'Edit the draft details and line items.', 'Issue and share the customer copy.', 'Review balances, payments, refunds, and settlement results.', 'Use corrections and refunds instead of deleting established financial history.']),
    guidePage(tfk, 'tfk-workflows', 'Workflows', '/workflows', 'Create a repeatable path for common jobs and apply it to active work.', ['Create and edit a workflow for your organization.', 'Add, order, and update the stages.', 'Assign the workflow to jobs and move work through each stage.', 'Refresh before retrying if another team member changed the workflow at the same time.']),
    guidePage(tfk, 'tfk-tasks', 'Team tasks', '/tasks', 'Search and manage organization-wide job tasks without losing their customer and job context.', ['Filter by owner, job, status, priority, due date, or search text.', 'Open the parent job from a task result.', 'Create or edit allowed task fields.', 'Complete, reopen, reorder, or archive tasks with version checks.']),
    guidePage(tfk, 'tfk-recurring', 'Recurring jobs', '/recurring-jobs', 'Schedule repeat service and see when the next customer job will be created.', ['Choose the schedule and job details.', 'Pause or resume future jobs.', 'Review the last result and next scheduled date.', 'Confirm that a job was created before treating the scheduled run as complete.']),
    guidePage(tfk, 'tfk-activity', 'Activity', '/activity', 'See who changed jobs, tasks, schedules, workflows, leads, and customer documents.', ['Filter recent business activity.', 'Review the person, action, item, time, and relevant details.', 'Use this history to confirm an in-app change; confirm external payments with the payment service.']),
    guidePage(tfk, 'tfk-payments', 'Payments', '/payments', 'Review invoice balances and record customer payments separately from your OperatorOS subscription.', ['Filter unpaid, partial, paid, failed, or refunded documents.', 'Record an approved manual payment with its reference and amount.', 'Use Stripe Connect only after setup and payment notifications are working.', 'Review settlements, duplicate notifications, refunds, and failures.'], { notes: ['This page handles payments from your customers. OperatorOS plan and add-on billing stays in the OperatorOS console.'] }),
    guidePage(tfk, 'tfk-analytics', 'Analytics', '/analytics', 'See where sales, delivery, billing, and collections are moving or getting stuck.', ['Review the lead funnel, jobs, task pressure, invoiced totals, collections, and outstanding balances.', 'Change the date or status filters.', 'Open the related record list to understand any total.']),
    guidePage(tfk, 'tfk-directory', 'Business Directory', '/directory', 'Keep organizations, contacts, and sites ready to use across customer and job workflows.', ['Search and maintain organizations.', 'Create and edit contacts and service locations.', 'Use those shared details in TradeFlowKit.', 'Archive records only when linked work allows it.']),
    guidePage(tfk, 'tfk-settings', 'Settings', '/settings', 'Set TradeFlowKit defaults, lead intake preferences, theme, and connected services.', ['Review your organization, team role, plan, and app access.', 'Set lead intake and workflow defaults.', 'Check whether connected services are ready without exposing credentials.', 'Use OperatorOS to change account, membership, subscription, or app access.']),
    guidePage(tfk, 'tfk-trash', 'Trash', '/trash', 'Review and restore retained business records while preserving dependency rules.', ['List archived customers, jobs, tasks, leads, and supported documents.', 'Inspect why a record was retained or cannot be restored.', 'Restore in a safe parent-before-child order.', 'Keep permanent deletion unavailable when financial, audit, or shared identity history must remain.'], { access: 'Organization administrator, owner, or platform administrator.' }),
    guidePage(tfk, 'tfk-subscription', 'Subscription', '/subscription', 'Open the OperatorOS page for plans, invoices, checkout, and app access.', ['Open the workspace plan or organization billing page.', 'Review whether TradeFlowKit is included.', 'Make supported subscription changes in OperatorOS.']),
    guidePage(tfk, 'tfk-call-recovery', 'Call recovery', '/call-recovery', 'Use OutCall to continue an eligible missed-call follow-up.', ['Check whether OutCall is available for the organization.', 'Keep lead qualification and conversion inside TradeFlowKit.', 'Use OutCall only after the destination number and calling service are ready.']),
    guidePage(tfk, 'tfk-admin', 'Administration', '/admin', 'Open OperatorOS to manage team members, app access, and billing.', ['Manage organization members in OperatorOS.', 'Review app access and plan status.', 'Use OperatorOS for account roles and billing instead of creating separate controls in TradeFlowKit.'], { access: 'Organization administrator, owner, or platform administrator.' }),
  ],
};

export const PULSEDESK_GUIDE: HelpGuide = {
  id: 'pulsedesk', name: 'PulseDesk', kind: 'main-module', accent: '#38bdf8',
  description: 'Healthcare operations coordination for requests, assignments, facilities, equipment, supplies, knowledge, and inbound communication.',
  availability: 'Available now for operational coordination. Keep patient charts and unnecessary health information out of PulseDesk.', startHref: `${pulse}/dashboard`,
  pages: [
    guidePage(pulse, 'pulse-overview', 'Operations overview', '/', 'See urgent requests, department workload, equipment needs, supply pressure, and facility work.', ['Review open, urgent, overdue, unassigned, and recently changed work.', 'See equipment, supplies, facilities, protected intake, and time at a glance.', 'Open the request queue or operations page from any total.'], { notes: ['PulseDesk coordinates operations. Do not store patient charts, clinical records, or unnecessary patient information.'] }),
    guidePage(pulse, 'pulse-requests', 'Requests and work queues', '/requests', 'Triage, assign, update, and resolve operational requests while keeping patient details out.', ['Create a request or open one received through approved public intake.', 'Filter by queue, priority, status, assignee, facility, or search.', 'Assign work, respond, add private operational notes, record time, and update status.', 'Review response targets, messages, attachments, and activity on request detail.', 'Close or reopen the request when your role allows it.']),
    guidePage(pulse, 'pulse-assignments', 'Assignments and escalation', '/assignments', 'Give each request a responsible team and escalate work before it stalls.', ['Review unassigned and escalated work.', 'Create or maintain departments and queues.', 'Assign requests to an available member or team.', 'Apply response policies and follow escalation events.', 'Use administration controls only when your team role allows it.'], { access: 'Anyone with PulseDesk access can review work. Queue, assignment, and policy changes require an organization administrator.' }),
    guidePage(pulse, 'pulse-contacts', 'Facilities and contacts', '/contacts', 'Maintain shared service clients, facilities, contacts, and vendors used by operational work.', ['Search shared Directory organizations, contacts, and sites.', 'Create or edit facility and service contact context.', 'Maintain vendor relationships for operational fulfillment.', 'Open linked requests, equipment, or facility work.', 'Avoid clinical demographics and patient records.']),
    guidePage(pulse, 'pulse-operations', 'Equipment, supplies, and facilities', '/operations', 'Track equipment issues, restock needs, vendor work, and facility requests through completion.', ['Register and review equipment without storing patient data.', 'Report an equipment issue and link it to a request.', 'Create, prioritize, fulfill, or close supply requests.', 'Track facility requests and vendor details.', 'Review status and activity to confirm progress.']),
    guidePage(pulse, 'pulse-inbound', 'Request intake', '/inbound', 'Review protected public requests and see whether email intake is available.', ['Use the protected public form for operational requests available today.', 'Review requests that were accepted, received twice, rejected, or could not be created.', 'Open the resulting request when one was created.', 'Treat SendGrid, standard mailboxes, Google Workspace, and Microsoft 365 connections as unavailable until PulseDesk shows a working live connection.']),
    guidePage(pulse, 'pulse-analytics', 'Analytics', '/analytics', 'Find trends in demand, missed response targets, assignments, equipment, supplies, facilities, and time.', ['Choose the reporting period and filters.', 'Review request volume, response, resolution, overdue, and workload trends.', 'Inspect equipment, supply, facility, and time summaries.', 'Open the related work list to investigate a result.']),
    guidePage(pulse, 'pulse-knowledge', 'Knowledge', '/knowledge', 'Maintain requester guidance and internal service procedures within the operational-data boundary.', ['Create, edit, search, and organize knowledge entries.', 'Separate requester-safe guidance from internal procedures.', 'Review and publish approved content.', 'Link relevant guidance to recurring operational issues.']),
    guidePage(pulse, 'pulse-integrations', 'Mailbox connections', '/integrations', 'See what request intake works now and what will be needed for a future mailbox connection.', ['Review the protected public request intake available today.', 'Confirm that direct SendGrid, IMAP, Google Workspace, and Microsoft 365 mailbox connections are marked unavailable.', 'Use the safe local connection check only in an explicitly labeled non-production environment.', 'Keep patient names, MRNs, diagnoses, and treatment details out of all operational intake.'], { access: 'Workspace manager, organization administrator, owner, or platform administrator.', notes: ['A setup preview is not a live mailbox connection and does not prove message delivery.'] }),
    guidePage(pulse, 'pulse-settings', 'Access and privacy guidance', '/settings', 'Review what belongs in PulseDesk, where team access is managed, and which request channels are available now.', ['Confirm that requests remain operational and exclude unnecessary patient information.', 'Review whether protected public intake is available.', 'Mailbox import is not connected yet; use the protected request form or create requests directly.', 'Use OperatorOS for team access, subscription, or account changes.']),
  ],
};

export const TECHDECK_GUIDE: HelpGuide = {
  id: 'techdeck', name: 'TechDeck', kind: 'main-module', accent: '#22d3ee',
  description: 'MSP operations for tickets, client infrastructure, documentation, service records, technician time, and integrations.',
  availability: 'Available now. TechDeck documents procedures and service results; it does not run commands on managed systems.', startHref: `${tech}/`,
  pages: [
    guidePage(tech, 'tech-overview', 'Operations overview', '/', 'See the tickets, systems, deadlines, and client commitments that need attention now.', ['Review ticket pressure, system health, lifecycle dates, service records, time, and connections.', 'Open tickets, clients, assets, network, or documentation from the shortcuts.', 'Confirm the current organization before editing managed records.']),
    guidePage(tech, 'tech-tickets', 'Tickets', '/tickets', 'Triage, assign, update, and close support work without losing priority or response targets.', ['Create, search, filter, and open tickets.', 'Set client, site, priority, status, queue, assignee, and response targets.', 'Add replies, internal notes, attachments, and time entries.', 'Review activity and linked systems.', 'Resolve or reopen the ticket when your role allows it.']),
    guidePage(tech, 'tech-clients', 'Clients', '/clients', 'Keep each client, site, contact, and service relationship ready for the technician handling the work.', ['Search organizations, sites, and contacts.', 'Create or edit shared business details.', 'Open related tickets, systems, network records, and time.', 'Reuse the existing client record across OperatorOS apps.']),
    guidePage(tech, 'tech-assets', 'Assets', '/assets', 'Track the client systems your team supports and keep their health and technical details current.', ['Create and classify a managed system.', 'Link the client, site, owner, identifiers, and lifecycle dates.', 'Record health, alerts, relationships, and service details.', 'Open related service records, tickets, network details, and documentation.', 'Archive the item when linked work allows it.']),
    guidePage(tech, 'tech-network', 'Network / IPAM', '/network', 'Map firewalls, switches, addresses, subnets, VLANs, and how they connect.', ['Create network devices and relationships.', 'Maintain subnets, VLANs, IP addresses, and assignments.', 'Search by client, site, type, or address.', 'Link test results and affected tickets.', 'Resolve address conflicts before saving assignments.']),
    guidePage(tech, 'tech-lifecycle', 'Lifecycle', '/lifecycle', 'Review warranty, renewal, expiration, incomplete-record, and health pressure.', ['Filter upcoming or overdue lifecycle dates.', 'Review warranty, license, certificate, renewal, and end-of-life posture.', 'Open the owning asset or client record.', 'Use the view for planning; confirm changes on the original asset or client record.']),
    guidePage(tech, 'tech-documentation', 'Documentation', '/documentation', 'Create and maintain technical knowledge technicians can trust in managed environments.', ['Create, search, edit, and categorize documentation.', 'Link documents to clients, sites, systems, and tickets.', 'Review revision history and approval status.', 'Attach only approved files and never store raw passwords or secret values.']),
    guidePage(tech, 'tech-runbooks', 'Runbooks', '/runbooks', 'Prepare approved step-by-step procedures for repeat service work.', ['Create a procedure and its revisions.', 'Record prerequisites, steps, rollback, and validation guidance.', 'Submit it for review and approval.', 'Download or consult the approved instructions.', 'Run any commands outside TechDeck using your normal approved tools.'], { notes: ['Runbooks document procedures. TechDeck does not execute scripts or commands.'] }),
    guidePage(tech, 'tech-evidence', 'Evidence', '/evidence', 'Attach observations, snapshots, test results, and files to the systems and tickets they support.', ['Create a service record with the origin and observation details.', 'Attach an approved private file when available.', 'Link it to the client, site, system, ticket, or report.', 'Review file checks, access, and activity under Technical details.']),
    guidePage(tech, 'tech-reports', 'Reports', '/reports', 'Create consistent reports covering infrastructure, lifecycle, tickets, service results, and time.', ['Choose the report scope and date range.', 'Generate it from the current records.', 'Review the included sections and completion status.', 'Download the report and keep it linked to the saved report entry.']),
    guidePage(tech, 'tech-time', 'Time', '/time', 'Record technician work against the correct client, ticket, site, or managed system.', ['Create and edit time entries.', 'Link time to the related service work.', 'Filter by technician, client, ticket, billable state, or date.', 'Confirm totals from the saved entries.']),
    guidePage(tech, 'tech-calendar', 'Calendar', '/calendar', 'Schedule appointments and create repeat tickets for routine service.', ['Create and update service appointments.', 'Connect the work to clients, sites, tickets, and team members.', 'Choose the schedule for recurring tickets.', 'Pause, resume, and review each result.']),
    guidePage(tech, 'tech-portal', 'Client portal', '/portal', 'Choose which tickets and service records each client or site can see.', ['Review client access and visibility rules.', 'Select the tickets or service records the client may see.', 'Review portal activity.', 'Keep internal notes and other client information private.']),
    guidePage(tech, 'tech-licenses', 'Licensing', '/licenses', 'Issue, validate, revoke, and audit product licenses without exposing raw keys after creation.', ['Create a license for an approved product and customer.', 'Copy the raw key only at the one permitted creation moment.', 'Validate status through the supported interface.', 'Revoke, expire, or inspect usage and audit state.'], { access: 'License management requires an authorized administrative role.' }),
    guidePage(tech, 'tech-status', 'Status', '/status', 'Maintain service components, incidents, updates, and public history.', ['Create and update service components.', 'Open, update, resolve, and publish incidents.', 'Review public status-page history.', 'Keep internal evidence and secrets out of public incident text.']),
    guidePage(tech, 'tech-compliance', 'Compliance', '/compliance', 'Collect approved files and results, then prepare a consistent compliance package.', ['Choose the review scope or secure intake method.', 'Review received files and validation results.', 'Generate the compliance package with verification details.', 'Export only content approved for the customer.']),
    guidePage(tech, 'tech-webhooks', 'Webhooks', '/webhooks', 'Send selected TechDeck updates to approved systems and follow delivery problems.', ['Add an approved HTTPS destination and choose the events it receives.', 'Replace or revoke the signing setup when needed.', 'Review deliveries, retries, responses, and messages still needing attention.', 'Retry supported deliveries without exposing the signing secret.'], { access: 'Organization administrator, owner, or platform administrator.' }),
    guidePage(tech, 'tech-api-tokens', 'API tokens', '/api-tokens', 'Give an integration limited, replaceable access to TechDeck.', ['Create a token with only the permissions and lifetime it needs.', 'Copy the full value at creation; it will not be shown again.', 'Review its last use and change history.', 'Revoke it immediately when no longer needed.'], { access: 'Organization administrator, owner, or platform administrator.' }),
    guidePage(tech, 'tech-settings', 'Access and service boundaries', '/settings', 'Review who manages the workspace, where team access changes happen, and what TechDeck runbooks can safely do.', ['Confirm your current organization and workspace role.', 'Review which records TechDeck keeps for service delivery.', 'Remember that runbooks are technician-reviewed instructions and do not execute arbitrary commands.', 'Use OperatorOS for account, membership, plan, or app-access changes.']),
  ],
};

export const TORQUESHED_GUIDE: HelpGuide = {
  id: 'torqueshed', name: 'TorqueShed', kind: 'companion-application', accent: '#f59e0b',
  description: 'Vehicle history, service work, project builds, step-by-step diagnostics, live bays, parts listings, and workshop records.',
  availability: 'Available now. Torque Assist and credit purchase require the related services to be connected first.', startHref: `${torque}/`,
  pages: [
    guidePage(torque, 'torque-overview', 'Garage overview', '/', 'See vehicles, service work, builds, diagnostics, reminders, spend, and community activity that need attention.', ['Review garage, service, diagnostic, build, live-bay, marketplace, and reminder summaries.', 'Search workshop records.', 'Start a vehicle, service, build, or diagnostic workflow.']),
    guidePage(torque, 'torque-garage', 'Garage', '/garage', 'Keep each vehicle connected to its service, build, cost, and diagnostic history.', ['Add a vehicle with the details your team needs.', 'Search, filter, open, and edit vehicles.', 'Review linked service, builds, diagnostics, costs, files, and activity.', 'Keep private maintenance and diagnostic notes out of public areas.']),
    guidePage(torque, 'torque-service', 'Service', '/service', 'Record completed maintenance and repair work, parts, vendors, costs, and reminders.', ['Create a service record for the correct vehicle.', 'Record work performed, mileage, dates, parts, vendor, cost, and notes.', 'Create or resolve maintenance reminders.', 'Review cumulative service history and spend.']),
    guidePage(torque, 'torque-builds', 'Builds', '/builds', 'Plan a vehicle build with stages, tasks, parts, journal entries, and project costs.', ['Create and edit a build for the correct vehicle.', 'Add, order, assign, and complete build tasks.', 'Track parts and costs.', 'Open build details and journal milestones.', 'Return later with the latest progress still available.']),
    guidePage(torque, 'torque-journal', 'Journal', '/journal', 'Capture build notes, milestones, photos, files, and costs as the project changes.', ['Create a dated build entry.', 'Link it to the vehicle or build.', 'Attach approved photos, files, or cost details.', 'Review the project story in order without replacing older entries.']),
    guidePage(torque, 'torque-diagnostics', 'Diagnostics', '/diagnostics', 'Work through symptoms, codes, tests, findings, and confirmed fixes step by step.', ['Start with the concern, symptoms, visible conditions, codes, and safety details.', 'Record tests, measurements, photos, files, possible causes, findings, and the confirmed fix.', 'Review the full diagnostic timeline.', 'Use Torque Assist only after recording the available facts and checking the displayed credit cost.'], { notes: ['Torque Assist helps plan diagnostic work. It does not verify a repair or replace proper tools, service information, or qualified judgment.'] }),
    guidePage(torque, 'torque-assist', 'Torque Assist', '/diagnostics/:diagnosticId/assist', 'Use the facts already recorded to suggest the next diagnostic step.', ['Open the diagnostic session you want help with.', 'Review the credit price and current balance.', 'Submit the recorded symptoms, codes, tests, and findings.', 'Review possible causes, facts for and against each one, next tests, safety warnings, and escalation guidance.', 'Check whether credits were used or returned if the connected service fails.'], { openPath: '/diagnostics', notes: ['Open a diagnostic first, then choose Torque Assist from that diagnostic record.'] }),
    guidePage(torque, 'torque-live-bays', 'Live Bays', '/live-bays', 'Work through a diagnosis with other technicians and return after an interruption.', ['Create or join a bay you can access.', 'Record shared actions, notes, photos, files, and results.', 'Reconnect with the prior history intact.', 'Close the bay and keep its record for later review.']),
    guidePage(torque, 'torque-templates', 'Templates and vendors', '/templates', 'Maintain reusable diagnostic plans and trusted service vendors.', ['Create and edit diagnostic templates.', 'Add ordered tests and evidence expectations.', 'Maintain vendor identity and service context.', 'Apply a template without replacing session-specific evidence.']),
    guidePage(torque, 'torque-marketplace', 'Marketplace', '/marketplace', 'Offer parts and respond to inquiries without exposing private workshop details.', ['Create a listing with condition, price, location, and approved photos.', 'Search, filter, and open listing details.', 'Send an inquiry without publishing private contact details.', 'Close, archive, or moderate listings when your role allows it.']),
    guidePage(torque, 'torque-community', 'Community', '/community', 'Share repairs, diagnostic results, and project updates with privacy and moderation controls.', ['Create, edit, and browse posts.', 'Comment and react with like, helpful, or insightful.', 'Report inappropriate content and review moderation results.', 'Keep private diagnostic, vehicle, and customer data out of public posts.']),
    guidePage(torque, 'torque-credits', 'Credits and usage', '/billing/credits', 'Review Torque Assist credits and purchase a test or live pack when the payment service is ready.', ['Review the pack price, service mode, and current balance.', 'Start checkout only when the page says the payment service is ready.', 'Review reserved, used, returned, and completed credits.', 'Wait for payment confirmation before treating a purchase as available.'], { notes: ['Credits pay for Torque Assist usage. Your OperatorOS subscription is managed separately.'] }),
    guidePage(torque, 'torque-activity', 'Activity', '/activity', 'See recent workshop changes and notifications.', ['Filter vehicle, service, build, diagnostic, marketplace, and community activity.', 'Open the related record.', 'Use the history to confirm actions and resolve conflicting edits.']),
    guidePage(torque, 'torque-search', 'Search', '/search', 'Find vehicles, builds, diagnostics, service work, and shared records.', ['Enter your search.', 'Filter by record type or workshop area.', 'Open the matching detail page.', 'Confirm the correct organization before editing.']),
    guidePage(torque, 'torque-exports', 'Exports', '/exports', 'Create and download workshop records for a vehicle, service, build, or diagnosis.', ['Choose what the export should cover.', 'Create the export.', 'Review its status, included data, and verification details.', 'Download it when your role allows it.']),
    guidePage(torque, 'torque-settings', 'Garage settings', '/settings', 'Choose workshop units, default privacy, profile visibility, and the alerts you want to receive.', ['Choose imperial or metric units.', 'Set the default visibility for new garage work.', 'Choose whether your community profile can be discovered.', 'Turn community, marketplace, and garage alerts on or off.', 'Save and confirm the new preferences after reload.']),
    guidePage(torque, 'torque-profile', 'Profile', '/profile', 'Review the profile and organization TorqueShed uses for your work.', ['Confirm the signed-in account and selected organization.', 'Review the profile details allowed in the community.', 'Use OperatorOS for password, account, or membership changes.']),
  ],
};

export const PRIMARY_MODULE_GUIDES = [
  TRADEFLOWKIT_GUIDE,
  PULSEDESK_GUIDE,
  TECHDECK_GUIDE,
  TORQUESHED_GUIDE,
] as const;
