'use client';

import dynamic from 'next/dynamic';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import React, { useCallback, useMemo } from 'react';
import { Activity, BarChart3, Brain, FileText, Grid2X2, GraduationCap, Layers3, Library, LifeBuoy, Settings, Sparkles, UserRound } from 'lucide-react';
import { useAuth } from '@/components/AuthProvider';
import { ModuleApplicationShell, type ModuleRouteManifestGroup, type ModuleThemeTokens } from '@/components/module-application-shell';
import { useTenant } from '@/components/TenantProvider';
import { getActiveTenantId } from '@/lib/auth';
import { buildOperatorOSHelpUrl, DEFAULT_OPERATOROS_NAVIGATION_URLS } from '../../../../../packages/modules/navigation.js';

const Workspace = dynamic(() => import('./StudyForgeShell'), { loading: () => <div role="status" aria-busy="true"><Activity size={18}/> Loading this learning route…</div> });
const theme: ModuleThemeTokens = { id:'studyforge-indigo-learning',colorScheme:'dark',density:'comfortable',colors:{background:'#070a13',panel:'#10162a',panelRaised:'#171f38',text:'#f8f7ff',muted:'#b9bfd2',border:'#3e4a69',primary:'#c4b5fd',secondary:'#7c3aed',accent:'#60a5fa',danger:'#fb7185',success:'#6ee7b7',focus:'#fbbf24'},radius:{small:'8px',medium:'13px',large:'19px'},typography:{body:'"Inter Variable",ui-sans-serif,system-ui,sans-serif',heading:'"Inter Variable",ui-sans-serif,system-ui,sans-serif',accent:'ui-monospace,"Cascadia Code",monospace'},imagery:{overlay:'radial-gradient(circle at 86% 0,rgba(124,58,237,.2),transparent 34rem),radial-gradient(circle at 4% 16%,rgba(37,99,235,.12),transparent 28rem)'}};
const nav: readonly ModuleRouteManifestGroup[]=[{id:'learn',label:'Learning workspace',items:[
  {id:'overview',canonicalPath:'/',label:'Dashboard',icon:GraduationCap,activeMatch:{kind:'exact'}},{id:'sources',canonicalPath:'/sources',label:'Sources & notes',icon:FileText,activeMatch:{kind:'prefix'}},{id:'sets',canonicalPath:'/sets',label:'Study sets',icon:Layers3,activeMatch:{kind:'prefix'}},{id:'flashcards',canonicalPath:'/flashcards',label:'Flashcards',icon:Library,activeMatch:{kind:'prefix'}},{id:'quizzes',canonicalPath:'/quizzes',label:'Quizzes',icon:Brain,activeMatch:{kind:'prefix'}},{id:'sessions',canonicalPath:'/sessions',label:'Sessions',icon:GraduationCap,activeMatch:{kind:'prefix'}},
]},{id:'insight',label:'Insight and control',items:[{id:'studio',canonicalPath:'/studio',label:'AI Studio',icon:Sparkles,activeMatch:{kind:'prefix'}},{id:'progress',canonicalPath:'/progress',label:'Progress & exports',icon:BarChart3,activeMatch:{kind:'prefix'}},{id:'settings',canonicalPath:'/settings',label:'Settings',icon:Settings,activeMatch:{kind:'prefix'}}]}];
const copy:Record<string,{eyebrow:string;title:string;subtitle:string}>={overview:{eyebrow:'Learning command',title:'StudyForge AI dashboard',subtitle:'Continue real study sets, sessions, quiz work, and exam preparation.'},sources:{eyebrow:'Grounded learning',title:'Sources and notes',subtitle:'Keep private notes and approved documents attached to the learning records they support.'},sets:{eyebrow:'Reusable learning systems',title:'Study sets',subtitle:'Organize folders, create complete sets, and reopen durable set records.'},flashcards:{eyebrow:'Recall practice',title:'Flashcards',subtitle:'Review published cards and persist spaced-repetition progress.'},quizzes:{eyebrow:'Server-authoritative assessment',title:'Quizzes and tests',subtitle:'Review, publish, attempt, and grade quizzes without client-trusted scores.'},sessions:{eyebrow:'Learning rhythm',title:'Sessions and plans',subtitle:'Run study plans, flashcard sessions, countdowns, and completion tracking.'},studio:{eyebrow:'Source-grounded generation',title:'AI Studio',subtitle:'Create human-reviewed drafts from authorized sources with honest provider state.'},progress:{eyebrow:'Durable progress',title:'Progress and exports',subtitle:'Review scores, recall, sessions, activity, and authorized portable exports.'},settings:{eyebrow:'Workspace control',title:'StudyForge AI settings',subtitle:'Manage learning preferences and review OperatorOS-owned plan and usage state.'}};
function area(path?:string){const root=(path||'/').split(/[?#]/u,1)[0].replace(/^\/modules\/studyforge-ai\/?/u,'').split('/').filter(Boolean)[0]||'overview';if(['app','dashboard'].includes(root))return'overview';if(['sources','notes','subjects','courses'].includes(root))return'sources';if(['sets','folders'].includes(root))return'sets';if(['flashcards','decks','cards'].includes(root))return'flashcards';if(root==='quizzes')return'quizzes';if(['sessions','plans','exams'].includes(root))return'sessions';if(root==='studio')return'studio';if(['progress','analytics','exports'].includes(root))return'progress';if(['settings','account','admin','pricing'].includes(root))return'settings';return'overview'}
export default function StudyForgeRouteShell({routePath}:{baseUrl?:string;routePath?:string}){const pathname=usePathname();const {user,loading:a}=useAuth();const {activeTenant,activeRole,loading:t}=useTenant();const tenantId=activeTenant?.id??user?.currentTenantId??getActiveTenantId();const current=area(routePath||pathname);const source=pathname.startsWith('/app/')||pathname.startsWith('/modules/');const hrefFor=useCallback((p:string)=>source?`/modules/studyforge-ai${p==='/'?'/dashboard':p}`:p,[source]);const navigation=useMemo(()=>nav.map(g=>({...g,items:g.items.map(i=>({...i,canonicalPath:hrefFor(i.canonicalPath)}))})),[hrefFor]);return <ModuleApplicationShell moduleId="studyforge-ai" moduleName="StudyForge AI" theme={theme} currentPath={hrefFor(current==='overview'?'/':`/${current}`)} navigation={navigation} brand={<Link href={hrefFor('/')} style={{color:'#f8f7ff',textDecoration:'none',fontWeight:900}}>StudyForge <span style={{color:'#c4b5fd'}}>AI</span></Link>} organization={{label:'Organization',value:activeTenant?.name??tenantId??'No organization selected'}} accessContext={{label:'Access',value:user?.platformRole==='super_admin'?'Platform administrator':activeRole??'member'}} utilityActions={[{label:'My Apps',href:DEFAULT_OPERATOROS_NAVIGATION_URLS.appsUrl,icon:Grid2X2},{label:'Profile',href:DEFAULT_OPERATOROS_NAVIGATION_URLS.profileUrl,icon:UserRound},{label:'Help',href:buildOperatorOSHelpUrl({module:'studyforge-ai',page:current==='overview'?'/':`/${current}`}),icon:LifeBuoy}]} page={copy[current]} state={a||t?'loading':!tenantId?'empty':'ready'} stateMessage={!tenantId?'Choose an organization before opening StudyForge AI.':undefined} mobileNavigation="drawer" testId="studyforge-module-shell" pageHeaderTestId="studyforge-module-header">{tenantId&&<Workspace key={`${tenantId}-${current}-${routePath??''}`} routePath={routePath||`/${current}`} embedded view={current} hrefFor={hrefFor}/>}</ModuleApplicationShell>}
