'use client';

import { useCallback, useEffect, useMemo, useRef, useState, type CSSProperties, type FormEvent } from 'react';
import { Activity, Bell, BookOpen, Download, FileCheck2, Flag, Gauge, Link2, PackagePlus, Radio, Search, Send, Settings2, ShieldCheck, Sparkles, Wrench } from 'lucide-react';
import { moduleShellApi, type TorqueShedDiagnostic, type TorqueShedVehicle } from '@/lib/auth';

type Row = Record<string, any>;
const field: CSSProperties={width:'100%',boxSizing:'border-box',border:'1px solid #3f3425',borderRadius:10,background:'#0b0d0f',color:'#f8fafc',padding:'11px 12px'};
const action: CSSProperties={minHeight:42,border:0,borderRadius:10,background:'#f59e0b',color:'#171108',fontWeight:900,padding:'9px 14px',cursor:'pointer',display:'inline-flex',gap:7,alignItems:'center',justifyContent:'center'};
const panel: CSSProperties={border:'1px solid #3f3425',borderRadius:16,background:'linear-gradient(155deg,#17191c 0%,#0d0f11 72%)',boxShadow:'0 18px 50px rgba(0,0,0,.25)',padding:18};
const label: CSSProperties={display:'grid',gap:6,color:'#b9b3aa',fontSize:13};
const empty: CSSProperties={border:'1px dashed #4a4032',borderRadius:12,padding:18,color:'#918b83',textAlign:'center'};
const money=(value:unknown)=>new Intl.NumberFormat(undefined,{style:'currency',currency:'USD'}).format(Number(value||0)/100);
const stableKey=(prefix:string)=>`${prefix}:${globalThis.crypto?.randomUUID?.()??Date.now()}`;
function message(error:unknown){void error;return 'TorqueShed could not confirm that action. Refresh and try again; saved records were not removed.';}

export function TorqueShedJournalPanel({builds}:{builds:Row[]}){
  const [selected,setSelected]=useState(''); const [workspace,setWorkspace]=useState<Row|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
  const load=useCallback(async(id:string)=>{if(!id){setWorkspace(null);return;}setBusy(true);setError('');try{setWorkspace(await moduleShellApi.torqueshed.getBuildWorkspace(id));}catch(next){setError(message(next));}finally{setBusy(false);}},[]);
  useEffect(()=>{const id=selected||String(builds[0]?.id||'');if(id&&id!==selected)setSelected(id);if(id)void load(id);},[builds,load,selected]);
  async function saveJournal(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,data=new FormData(form);setBusy(true);setError('');try{await moduleShellApi.torqueshed.addBuildJournalEntry(selected,{entryType:data.get('entryType'),title:data.get('title'),body:data.get('body'),mileage:Number(data.get('mileage'))||undefined,costMinor:Math.round((Number(data.get('cost'))||0)*100)||undefined,laborMinutes:Number(data.get('laborMinutes'))||undefined,visibility:data.get('visibility'),occurredAt:new Date().toISOString()});form.reset();await load(selected);}catch(next){setError(message(next));}finally{setBusy(false);}}
  async function savePart(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,data=new FormData(form);setBusy(true);setError('');try{await moduleShellApi.torqueshed.addBuildPart(selected,{name:data.get('name'),manufacturer:data.get('manufacturer'),partNumber:data.get('partNumber'),category:data.get('category'),status:data.get('status'),quantity:Number(data.get('quantity'))||1,unitCostMinor:Math.round((Number(data.get('cost'))||0)*100)||undefined,notes:data.get('notes')});form.reset();await load(selected);}catch(next){setError(message(next));}finally{setBusy(false);}}
  const journal=(workspace?.journal||[]) as Row[],parts=(workspace?.parts||[]) as Row[];
  const totals=useMemo(()=>({parts:parts.reduce((sum,row)=>sum+Number(row.unitCostMinor||0)*Number(row.quantity||1),0),journal:journal.reduce((sum,row)=>sum+Number(row.costMinor||0),0),hours:journal.reduce((sum,row)=>sum+Number(row.laborMinutes||0),0)/60}),[journal,parts]);
  return <section id="torqueshed-journal" data-testid="torqueshed-journal" className="ts28-grid">
    <div style={{...panel,gridColumn:'1/-1'}} className="ts28-hero"><div><span className="ts28-kicker">Build journal</span><h2>Document every wrench turn.</h2><p>Stages, modifications, costs, evidence and milestones stay attached to the real build record.</p></div><BookOpen size={40}/></div>
    {error&&<div role="alert" className="ts28-alert">{error}</div>}
    <article style={panel}><label style={label}>Active build<select value={selected} onChange={event=>{setSelected(event.target.value);void load(event.target.value);}} style={field}>{builds.map(build=><option key={build.id} value={build.id}>{build.title}</option>)}</select></label><div className="ts28-stats"><b>{parts.length}<small> parts</small></b><b>{money(totals.parts+totals.journal)}<small> tracked</small></b><b>{totals.hours.toFixed(1)}<small> hours</small></b></div>
      <form onSubmit={saveJournal} className="ts28-form"><h3><Flag size={17}/> Add journal entry</h3><div className="ts28-two"><label style={label}>Entry type<select name="entryType" style={field}><option value="entry">Journal entry</option><option value="milestone">Milestone</option><option value="stage_update">Stage update</option><option value="cost_update">Cost update</option></select></label><label style={label}>Visibility<select name="visibility" style={field}><option value="private">Private garage</option><option value="tenant">Team</option><option value="public">Public build page</option></select></label></div><label style={label}>Title<input required minLength={2} maxLength={180} name="title" style={field}/></label><label style={label}>What changed<textarea name="body" rows={4} style={field}/></label><div className="ts28-three"><label style={label}>Mileage<input name="mileage" type="number" min="0" style={field}/></label><label style={label}>Cost ($)<input name="cost" type="number" min="0" step="0.01" style={field}/></label><label style={label}>Labor minutes<input name="laborMinutes" type="number" min="0" style={field}/></label></div><button disabled={busy||!selected} style={action}><Sparkles size={16}/> Save entry</button></form>
    </article>
    <article style={panel}><form onSubmit={savePart} className="ts28-form"><h3><PackagePlus size={17}/> Add modification or part</h3><label style={label}>Part / modification<input required name="name" maxLength={180} style={field}/></label><div className="ts28-two"><label style={label}>Manufacturer<input name="manufacturer" style={field}/></label><label style={label}>Part number<input name="partNumber" style={field}/></label></div><div className="ts28-three"><label style={label}>Category<input name="category" placeholder="Suspension" style={field}/></label><label style={label}>Status<select name="status" style={field}><option value="planned">Planned</option><option value="ordered">Ordered</option><option value="installed">Installed</option><option value="removed">Removed</option></select></label><label style={label}>Quantity<input name="quantity" type="number" min="1" defaultValue="1" style={field}/></label></div><label style={label}>Unit cost ($)<input name="cost" type="number" min="0" step="0.01" style={field}/></label><label style={label}>Fitment / install notes<textarea name="notes" rows={3} style={field}/></label><button disabled={busy||!selected} style={action}><Wrench size={16}/> Track part</button></form>
      <div className="ts28-list">{parts.length?parts.map(part=><div key={part.id} className="ts28-row"><div><b>{part.name}</b><small>{[part.manufacturer,part.partNumber].filter(Boolean).join(' · ')||'No manufacturer details'}</small></div><span>{part.status}</span><strong>{money(Number(part.unitCostMinor||0)*Number(part.quantity||1))}</strong></div>):<div style={empty}>No parts tracked on this build yet.</div>}</div>
    </article>
    <article style={{...panel,gridColumn:'1/-1'}}><h3>Build timeline</h3><div className="ts28-timeline">{journal.length?journal.map(entry=><div key={entry.id} className="ts28-event"><i/><div><span>{String(entry.entryType).replaceAll('_',' ')}</span><h4>{entry.title}</h4><p>{entry.body||'No additional notes.'}</p><small>{new Date(entry.occurredAt).toLocaleString()} {entry.mileage?`· ${Number(entry.mileage).toLocaleString()} mi`:''} {entry.costMinor?`· ${money(entry.costMinor)}`:''}</small></div></div>):<div style={empty}>The first journal entry becomes the opening chapter of this build.</div>}</div></article>
  </section>;
}

export function TorqueShedLiveBayPanel({vehicles,builds,diagnostics}:{vehicles:TorqueShedVehicle[];builds:Row[];diagnostics:TorqueShedDiagnostic[]}){
  const [bays,setBays]=useState<Row[]>([]),[active,setActive]=useState<Row|null>(null),[messages,setMessages]=useState<Row[]>([]),[cursor,setCursor]=useState(0),[connected,setConnected]=useState(false),[error,setError]=useState(''); const cursorRef=useRef(0);
  const loadBays=useCallback(async()=>{try{const result=await moduleShellApi.torqueshed.listLiveBays();setBays(result.bays);if(!active&&result.bays[0])setActive(result.bays[0]);}catch(next){setError(message(next));}},[active]);
  const sync=useCallback(async()=>{if(!active?.id)return;try{const result=await moduleShellApi.torqueshed.getLiveBay(String(active.id),cursorRef.current);setMessages(current=>{const merged=new Map(current.map(row=>[row.id,row]));for(const row of result.messages)merged.set(row.id,row);return [...merged.values()].sort((a,b)=>Number(a.sequence)-Number(b.sequence));});cursorRef.current=result.cursor;setCursor(result.cursor);setActive(result.bay);setConnected(true);setError('');}catch(next){setConnected(false);setError(message(next));}},[active?.id]);
  useEffect(()=>{void loadBays();},[loadBays]);
  useEffect(()=>{cursorRef.current=0;setCursor(0);setMessages([]);if(active?.id)void sync();},[active?.id,sync]);
  useEffect(()=>{if(!active?.id||active.status==='closed')return;const timer=window.setInterval(()=>void sync(),2000);return()=>window.clearInterval(timer);},[active?.id,active?.status,sync]);
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,data=new FormData(form),context=String(data.get('context')||'');const [kind,value]=context.split(':');try{const result=await moduleShellApi.torqueshed.createLiveBay({title:data.get('title'),visibility:data.get('visibility'),...(kind==='vehicle'?{vehicleId:value}:kind==='build'?{buildId:value}:{diagnosticId:value})});form.reset();setBays(current=>[result.bay,...current]);setActive(result.bay);}catch(next){setError(message(next));}}
  async function send(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,data=new FormData(form),body=String(data.get('body')||'').trim();if(!body||!active)return;try{await moduleShellApi.torqueshed.sendLiveBayMessage(String(active.id),{clientMessageId:stableKey('bay'),body});form.reset();await sync();}catch(next){setError(message(next));}}
  const contextOptions=[...vehicles.map(v=>({id:`vehicle:${v.id}`,name:`Vehicle · ${v.nickname||`${v.year} ${v.make} ${v.model}`}`})),...builds.map(b=>({id:`build:${b.id}`,name:`Build · ${b.title}`})),...diagnostics.map(d=>({id:`diagnostic:${d.id}`,name:`Diagnostic · ${d.title}`}))];
  return <section id="torqueshed-live-bay" data-testid="torqueshed-live-bay" className="ts28-live"><aside style={panel}><div className="ts28-live-title"><div><span className="ts28-kicker">Live bay</span><h2>Garage collaboration</h2></div><Radio className={connected?'ts28-pulse':''} color={connected?'#22c55e':'#78716c'}/></div><p className="ts28-muted">Durable, authorized collaboration with sequenced history and automatic reconnect.</p><form onSubmit={create} className="ts28-form"><label style={label}>Bay title<input required name="title" style={field} placeholder="No-crank diagnosis"/></label><label style={label}>Garage context<select required name="context" style={field}><option value="">Choose a record</option>{contextOptions.map(option=><option key={option.id} value={option.id}>{option.name}</option>)}</select></label><label style={label}>Visibility<select name="visibility" style={field}><option value="private">Invited members</option><option value="tenant">Garage team</option></select></label><button style={action}><Radio size={16}/> Open live bay</button></form><div className="ts28-bays">{bays.map(bay=><button key={bay.id} onClick={()=>setActive(bay)} className={active?.id===bay.id?'active':''}><b>{bay.title}</b><span>{bay.status} · {bay.lastSequence||0} messages</span></button>)}</div></aside>
    <article style={panel} className="ts28-chat"><header><div><h3>{active?.title||'Select a live bay'}</h3><small>{connected?'Connected · missed messages recovered':active?'Reconnecting…':'No bay selected'} · cursor {cursor}</small></div>{active?.status==='active'&&<button style={{...action,background:'transparent',color:'#fca5a5',border:'1px solid #7f1d1d'}} onClick={async()=>{await moduleShellApi.torqueshed.closeLiveBay(String(active.id));await sync();}}>Close bay</button>}</header>{error&&<div role="alert" className="ts28-alert">{error}</div>}<div className="ts28-messages" aria-live="polite">{messages.length?messages.map(row=><div key={row.id} className="ts28-message"><div><b>{row.senderDisplayName||'Garage member'}</b><time>#{row.sequence} · {new Date(row.createdAt).toLocaleTimeString()}</time></div><p>{row.body}</p></div>):<div style={empty}>{active?'The bay is open. Send the first update.':'Open or choose a bay to collaborate.'}</div>}</div><form onSubmit={send} className="ts28-send"><label className="sr-only" htmlFor="bay-message">Message</label><input id="bay-message" name="body" required maxLength={5000} disabled={!active||active.status==='closed'} style={field} placeholder="Share an observation, reading, or next test…"/><button disabled={!active||active.status==='closed'} style={action}><Send size={16}/><span>Send</span></button></form><p className="ts28-safe"><ShieldCheck size={15}/> Messages persist, posting is member-authorized, duplicate-safe, and rate-limited. Use evidence uploads for files.</p></article>
  </section>;
}

export function TorqueShedUtilityPanel({diagnostics}:{diagnostics:TorqueShedDiagnostic[]}){
  const [activityRows,setActivityRows]=useState<Row[]>([]),[notifications,setNotifications]=useState<Row[]>([]),[exports,setExports]=useState<Row[]>([]),[settings,setSettings]=useState<Row|null>(null),[results,setResults]=useState<Row[]>([]),[report,setReport]=useState<Row|null>(null),[share,setShare]=useState(''),[error,setError]=useState('');
  const load=useCallback(async()=>{try{const [a,n,e,s]=await Promise.all([moduleShellApi.torqueshed.listActivity(),moduleShellApi.torqueshed.listNotifications(),moduleShellApi.torqueshed.listExports(),moduleShellApi.torqueshed.getSettings()]);setActivityRows(a.events);setNotifications(n.notifications);setExports(e.exports);setSettings(s.settings);}catch(next){setError(message(next));}},[]);
  useEffect(()=>{void load();},[load]);
  async function search(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);try{setResults((await moduleShellApi.torqueshed.searchProduct(String(data.get('q')))).results);}catch(next){setError(message(next));}}
  async function saveSettings(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);try{const result=await moduleShellApi.torqueshed.saveSettings({units:data.get('units'),defaultGarageVisibility:data.get('visibility'),reducedMotion:data.get('reducedMotion')==='on',profileDiscoverable:data.get('discoverable')==='on',communityNotifications:data.get('communityNotifications')==='on',marketplaceNotifications:data.get('marketplaceNotifications')==='on',garageNotifications:data.get('garageNotifications')==='on'});setSettings(result.settings);}catch(next){setError(message(next));}}
  async function openReport(diagnosticId:string){try{setReport(await moduleShellApi.torqueshed.getDiagnosticReport(diagnosticId));setShare('');}catch(next){setError(message(next));}}
  async function makeShare(){if(!report?.report?.diagnostic?.id)return;try{const result=await moduleShellApi.torqueshed.createShareLink({resourceType:'diagnostic_report',resourceId:report.report.diagnostic.id,allowDownload:false});setShare(`${window.location.origin}${result.shareLink.url}`);}catch(next){setError(message(next));}}
  return <section id="torqueshed-tools" data-testid="torqueshed-tools" className="ts28-grid"><div style={{...panel,gridColumn:'1/-1'}} className="ts28-hero"><div><span className="ts28-kicker">Garage command tools</span><h2>Find it, prove it, take it with you.</h2><p>Search every active surface, review activity, manage notifications, produce reports and request deterministic exports.</p></div><Gauge size={40}/></div>{error&&<div role="alert" className="ts28-alert">{error}</div>}
    <article style={panel}><h3><Search size={17}/> Product search</h3><form onSubmit={search} className="ts28-send"><input required minLength={2} name="q" aria-label="Search TorqueShed" style={field} placeholder="Vehicle, build, diagnostic, listing or post"/><button style={action}><Search size={16}/>Search</button></form><div className="ts28-list">{results.map(row=><div key={`${row.resultType}:${row.id}`} className="ts28-row"><div><b>{row.title||row.nickname||`${row.year||''} ${row.make||''} ${row.model||''}`}</b><small>{String(row.resultType||'record').replaceAll('_',' ')}</small></div><span>{row.status||'active'}</span></div>)}{!results.length&&<div style={empty}>Search stays inside authorized tenant and privacy boundaries.</div>}</div></article>
    <article style={panel}><h3><FileCheck2 size={17}/> Diagnostic report</h3><label style={label}>Diagnostic session<select style={field} onChange={event=>event.target.value&&void openReport(event.target.value)} defaultValue=""><option value="">Choose a session</option>{diagnostics.map(d=><option key={d.id} value={d.id}>{d.title}</option>)}</select></label>{report&&<div className="ts28-report"><b>{report.report.diagnostic.title}</b><p>{report.report.diagnostic.customerConcern}</p><small>{report.report.troubleCodes.length} DTCs · {report.report.observations.length} observations · {report.report.evidence.length} evidence files</small><button onClick={()=>void makeShare()} style={{...action,marginTop:10}}><Link2 size={16}/> Create revocable share link</button>{share&&<output>{share}</output>}</div>}</article>
    <article style={panel}><h3><Activity size={17}/> Activity</h3><div className="ts28-list">{activityRows.slice(0,12).map(row=><div key={row.id} className="ts28-row"><div><b>{row.summary}</b><small>{String(row.eventType).replaceAll('_',' ')} · {new Date(row.createdAt).toLocaleString()}</small></div></div>)}{!activityRows.length&&<div style={empty}>Garage actions will appear here.</div>}</div></article>
    <article style={panel}><h3><Bell size={17}/> Notifications</h3><div className="ts28-list">{notifications.slice(0,12).map(row=><div key={row.id} className="ts28-row"><div><b>{row.title}</b><small>{row.message}</small></div><span>{row.readAt?'read':'new'}</span></div>)}{!notifications.length&&<div style={empty}>You are all caught up.</div>}</div></article>
    <article style={panel}><h3><Settings2 size={17}/> Garage settings</h3>{settings&&<form onSubmit={saveSettings} className="ts28-form"><div className="ts28-two"><label style={label}>Units<select name="units" defaultValue={settings.units} style={field}><option value="imperial">Imperial</option><option value="metric">Metric</option></select></label><label style={label}>Default privacy<select name="visibility" defaultValue={settings.defaultGarageVisibility} style={field}><option value="private">Private</option><option value="tenant">Garage team</option><option value="public_build">Public build</option></select></label></div>{[['reducedMotion','Reduce motion'],['discoverable','Discoverable profile'],['communityNotifications','Community alerts'],['marketplaceNotifications','Marketplace alerts'],['garageNotifications','Garage alerts']].map(([name,title])=><label key={name} className="ts28-check"><input type="checkbox" name={name} defaultChecked={name==='reducedMotion'?settings.reducedMotion:settings[name]!==false}/>{title}</label>)}<button style={action}>Save settings</button></form>}</article>
    <article style={panel}><h3><Download size={17}/> Portable history</h3><p className="ts28-muted">Exports run through the shared audited job system and are retained as scanned attachments.</p><div className="ts28-actions"><button style={action} onClick={async()=>{await moduleShellApi.torqueshed.requestExport('json',stableKey('export'));await load();}}><Download size={16}/> JSON export</button><button style={{...action,background:'transparent',color:'#fbbf24',border:'1px solid #92400e'}} onClick={async()=>{await moduleShellApi.torqueshed.requestExport('csv',stableKey('export'));await load();}}>CSV export</button></div><div className="ts28-list">{exports.slice(0,8).map(row=><div key={row.id} className="ts28-row"><div><b>{String(row.format).toUpperCase()} history</b><small>{new Date(row.createdAt).toLocaleString()}</small></div><span>{row.status}</span></div>)}</div></article>
  </section>;
}
