process.env.SESSION_SECRET ||= 'operatoros-pulsedesk-phase27-test-v1';
process.env.APP_ENV ||= 'test';
process.env.NODE_ENV ||= 'test';
import { after,before,test } from 'node:test';
import assert from 'node:assert/strict';
import { createHmac } from 'node:crypto';
import { eq,sql } from 'drizzle-orm';
import { db } from '../src/db.js';
import { modules,tenantModules } from '../src/schema.js';
import { cleanupModule,cleanupUser,createTestModule,createTestUser,ensureSchemaReady } from './_setup.js';

let app:any;let owner:any;let foreign:any;let moduleRow:any;let moduleCreated=false;let signToken:typeof import('../src/lib/auth.js').signToken;
const headers=(who:any)=>({authorization:`Bearer ${signToken({userId:who.id,email:who.email,role:who.role,tokenVersion:who.tokenVersion,sessionType:'platform'})}`,'x-tenant-id':who.currentTenantId});
const inject=(method:string,url:string,who:any,payload?:unknown)=>app.inject({method,url,headers:headers(who),...(payload===undefined?{}:{payload})});

before(async()=>{await ensureSchemaReady();({signToken}=await import('../src/lib/auth.js'));owner=await createTestUser();foreign=await createTestUser();[moduleRow]=await db.select().from(modules).where(eq(modules.slug,'pulsedesk')).limit(1);if(!moduleRow){moduleRow=await createTestModule('pulsedesk');moduleCreated=true;}await db.insert(tenantModules).values([{tenantId:owner.currentTenantId,moduleId:moduleRow.id,status:'enabled',source:'admin',allowAllMembers:true},{tenantId:foreign.currentTenantId,moduleId:moduleRow.id,status:'enabled',source:'admin',allowAllMembers:true}]);const Fastify=(await import('fastify')).default;const cookie=(await import('@fastify/cookie')).default;const {registerPulseDeskLiteralRoutes}=await import('../src/routes/pulsedesk-literal-routes.js');app=Fastify();await app.register(cookie);await registerPulseDeskLiteralRoutes(app);await app.ready();});
after(async()=>{if(app)await app.close();for(const who of [owner,foreign])if(who){const t=who.currentTenantId;await db.execute(sql`DELETE FROM pulsedesk_public_intake_windows WHERE policy_id IN (SELECT id FROM pulsedesk_public_intake_policies WHERE tenant_id=${t})`);for(const table of ['pulsedesk_public_intake_policies','pulsedesk_connector_events','pulsedesk_inbound_messages','pulsedesk_mail_connectors','pulsedesk_requests','pulsedesk_request_sequences','shared_provider_configs','shared_secret_references'])await db.execute(sql.raw(`DELETE FROM ${table} WHERE tenant_id = '${t.replaceAll("'","''")}'`));await cleanupUser(who.id);}if(moduleRow&&moduleCreated)await cleanupModule(moduleRow.id);});

test('Phase 27 connector ingestion, OAuth, deduplication, privacy, public intake, and tenant isolation',async()=>{
  const ids:string[]=[];
  for(const provider of ['sendgrid','imap','google','microsoft']){
    const created=await inject('POST','/v1/modules/pulsedesk/connectors',owner,{provider,label:`${provider} operations`,mailboxAddress:`${provider}@example.invalid`,mode:'test',secretReference:`vault://phase27/${provider}`,callbackReady:true});assert.equal(created.statusCode,201,created.body);ids.push(created.json().id);
    const ingested=await inject('POST',`/v1/modules/pulsedesk/connectors/${created.json().id}/test-ingest`,owner,{messageId:`phase27-${provider}`,from:'requester@example.invalid',subject:`Operational ${provider} equipment support request`,attachmentsClean:true});assert.equal(ingested.statusCode,201,ingested.body);assert.equal(ingested.json().duplicate,false);
    const duplicate=await inject('POST',`/v1/modules/pulsedesk/connectors/${created.json().id}/test-ingest`,owner,{messageId:`phase27-${provider}`,from:'spoof@example.invalid',subject:`Operational ${provider} equipment support request`,attachmentsClean:true});assert.equal(duplicate.statusCode,200,duplicate.body);assert.equal(duplicate.json().duplicate,true);
    if(provider==='sendgrid'){
      const inbound=`/v1/public/pulsedesk/inbound/sendgrid/${created.json().inbound_alias}`;const message={messageId:'phase27-public-sendgrid',from:'requester@example.invalid',subject:'Facilities generator inspection request',attachmentCount:0};
      const spoofed=await app.inject({method:'POST',url:inbound,payload:message});assert.equal(spoofed.statusCode,401,spoofed.body);
      const acceptedInbound=await app.inject({method:'POST',url:inbound,headers:{'x-pulsedesk-test-adapter':'deterministic'},payload:message});assert.equal(acceptedInbound.statusCode,201,acceptedInbound.body);
      const duplicateInbound=await app.inject({method:'POST',url:inbound,headers:{'x-pulsedesk-test-adapter':'deterministic'},payload:message});assert.equal(duplicateInbound.statusCode,200,duplicateInbound.body);assert.equal(duplicateInbound.json().duplicate,true);
      const quarantined=await app.inject({method:'POST',url:inbound,headers:{'x-pulsedesk-test-adapter':'deterministic'},payload:{...message,messageId:'phase27-quarantined',attachmentCount:1,attachmentsClean:false}});assert.equal(quarantined.statusCode,422,quarantined.body);assert.equal(quarantined.json().quarantined,true);
    }
  }
  const google=ids[2];const start=await inject('POST',`/v1/modules/pulsedesk/connectors/${google}/oauth/start`,owner,{});assert.equal(start.statusCode,200,start.body);const bad=await inject('POST',`/v1/modules/pulsedesk/connectors/${google}/oauth/callback`,owner,{state:'tampered'});assert.equal(bad.statusCode,400,bad.body);const restarted=await inject('POST',`/v1/modules/pulsedesk/connectors/${google}/oauth/start`,owner,{});const callback=await inject('POST',`/v1/modules/pulsedesk/connectors/${google}/oauth/callback`,owner,{state:restarted.json().state});assert.equal(callback.statusCode,200,callback.body);
  const liveSecret='phase27-live-hmac-secret';const live=await inject('POST','/v1/modules/pulsedesk/connectors',owner,{provider:'sendgrid',label:'sendgrid authenticated delivery',mailboxAddress:'live-sendgrid@example.invalid',mode:'live',secretReference:liveSecret,callbackReady:true});assert.equal(live.statusCode,201,live.body);await db.execute(sql`UPDATE pulsedesk_mail_connectors SET status='active' WHERE tenant_id=${owner.currentTenantId} AND id=${live.json().id}`);const liveMessage={messageId:'phase27-live-sendgrid',from:'operations@example.invalid',subject:'Authenticated generator maintenance request',attachmentCount:0};const canonical=`${liveMessage.messageId}\n${liveMessage.from}\n${liveMessage.subject}\n0\nunverified`;const signature=createHmac('sha256',liveSecret).update(canonical).digest('hex');const liveSpoof=await app.inject({method:'POST',url:`/v1/public/pulsedesk/inbound/sendgrid/${live.json().inbound_alias}`,headers:{'x-pulsedesk-signature':'0'.repeat(64)},payload:liveMessage});assert.equal(liveSpoof.statusCode,401,liveSpoof.body);const liveAccepted=await app.inject({method:'POST',url:`/v1/public/pulsedesk/inbound/sendgrid/${live.json().inbound_alias}`,headers:{'x-pulsedesk-signature':`sha256=${signature}`},payload:liveMessage});assert.equal(liveAccepted.statusCode,201,liveAccepted.body);
  const foreignList=await inject('GET','/v1/modules/pulsedesk/connectors',foreign);assert.equal(foreignList.statusCode,200);assert.equal(foreignList.json().connectors.length,0);
  const policy=await inject('POST','/v1/modules/pulsedesk/public-intake-policies',owner,{maxRequestsPerHour:3});assert.equal(policy.statusCode,201,policy.body);const slug=policy.json().public_slug;const view=await app.inject({method:'GET',url:`/v1/public/pulsedesk/intake/${slug}`});assert.equal(view.statusCode,200);
  const rejected=await app.inject({method:'POST',url:`/v1/public/pulsedesk/intake/${slug}`,payload:{summary:'Patient diagnosis and medical record problem'}});assert.equal(rejected.statusCode,422,rejected.body);
  const accepted=await app.inject({method:'POST',url:`/v1/public/pulsedesk/intake/${slug}`,payload:{summary:'Radiology room door will not latch',priority:'high',location:'North wing'}});assert.equal(accepted.statusCode,201,accepted.body);assert.match(accepted.json().reference,/^PD-\d+$/);
  const stored=await db.execute(sql`SELECT sender_hash,subject_summary,safe_metadata,status,ticket_id FROM pulsedesk_inbound_messages WHERE tenant_id=${owner.currentTenantId}`);assert.equal(stored.rows.length,7);assert.ok(stored.rows.every((row:any)=>/^[a-f0-9]{64}$/.test(row.sender_hash)));assert.doesNotMatch(JSON.stringify(stored.rows),/requester@example\.invalid|operations@example\.invalid|vault:\/\//);const quarantine=stored.rows.find((row:any)=>row.status==='rejected');assert.ok(quarantine);assert.equal((quarantine as any).ticket_id,null);
});
